### ISSUE TITLE
SMBProtocolDecodingException: Buffer to small for read response

### ISSUE THREAD

**Issue by djdkedev** [AgNO3/jcifs-ng#102]
Version: 2.0.7
Caused by: jcifs.internal.SMBProtocolDecodingException: Buffer to small for read response
	at jcifs.internal.smb2.io.Smb2ReadResponse.readBytesWireFormat(Smb2ReadResponse.java:112)
	at jcifs.internal.smb2.ServerMessageBlock2.decode(ServerMessageBlock2.java:525)
	at jcifs.internal.smb2.ServerMessageBlock2.decode(ServerMessageBlock2.java:507)
	at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1154)
	at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1104)
	at jcifs.util.transport.Transport.loop(Transport.java:459)
	at jcifs.util.transport.Transport.run(Transport.java:762)

Hello,

What could be the cause of this exception?

Thanks,
Dhananjay

**Comment by mbechler** [comment]
Most likely a more high level/application issue, e.g. specifying a too large read size/offset for the buffer supplied in a read() call.

**Comment by djdkedev** [comment]
Thanks! This issue is resolved after correcting the buffer size and read offset.
