### ISSUE TITLE
Unable to access public folder using anonymous credentials

### ISSUE THREAD

**Issue by TJDevSymc** [AgNO3/jcifs-ng#105]
I'm using jcifs-ng 2.0.7 version.
I'm unable to access a public folder using anonymous credentials.

Code:
SmbFile file1 = new SmbFile(filepath, SingletonContext.getInstance().withAnonymousCredentials());

Error:
jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1381)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1522)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:984)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1493)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:601)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:466)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:361)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:339)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.exists(SmbFile.java:821)
	at com.vontu.filesystemcrawler.file.SmbFileAdapter.ensureExists(SmbFileAdapter.java:222)
	at com.vontu.filesystemcrawler.file.FileFactory.createFile(FileFactory.java:74)
	at com.vontu.filesystemcrawler.RootFileFactory.createRootFile(RootFileFactory.java:59)
	... 5 more

I even tried to access the public folder using guest credentials, but got the same error.

**Comment by mbechler** [comment]
Looks to me like the server does not like the SessionSetup exchange in some way. 
There were quite a few changes/in in the SPNEGO/NTLM exchanges for 2.1, so I would suggest trying 2.1/master branch. There is also a change in current master for #98, which does not appear to be the exact same problem but might be related.
Can you provide further information (server implementation, debug log, packet capture)? If you have access, having a look in the server logs could shed some light, too.

**Comment by col-panic** [comment]
I can confirm this with current 2.1.2. The test is executed with the following test code, against Windows Server 2012 R2

```
@Test
public void test() throws MalformedURLException, SmbException{
	try (SmbFile smbFile = new SmbFile("smb://xxx.yy/smb_for_unittest/ZLErD3ZPHCcBj/",
		SingletonContext.getInstance().withAnonymousCredentials())) {
		smbFile.exists();
	}
}
```
and the following wireshark log

![2019-04-26_0955](https://user-images.githubusercontent.com/1679857/56792476-fc654380-6809-11e9-90c2-2424f73edd1a.png)

The share is configured as follows ("Jeder" is german for anybody)

![2019-04-26_0959](https://user-images.githubusercontent.com/1679857/56792536-20c12000-680a-11e9-951d-ea09caa86c15.png)

**Comment by mbechler** [comment]
Not the same issue, in your's the TreeConnect fails not the SessionSetup.

**Comment by pvagner** [comment]
There are multiple android apps using this library e.g. Total Commander or cifs-documents-provider with its source code at https://github.com/wa2c/cifs-documents-provider/ .
I am unable to access public folders with anonymous credentials when using these apps.
Other apps such as smbclient on the command line, gvfs through nautilus, VLC media player both on linux and on android, ghost commander on Android, Windows 10 file explorer can perfectly connect to this anonymous public share.
Except of a few little changes so the anonymous access is possible I am using default samba 4.15.3 setup on Arch Linux.
Can I somehow work this around by tweaking the server config?
```
[global]
  guest account = nobody
security = user
map to guest = Bad Password
  use sendfile = yes
  aio read size = 1
  aio write size = 1

[tmp]
   comment = Temporary file space
   path = /tmp
   read only = no
   public = yes
```

**Comment by mbechler** [comment]
@pvagner can you verify that these are using 2.1.5+, there were some significant changes regarding guest authentication in 2.1.5. Otherwise please provide more details (packet capture of a working and non-working connection would be great) and open a new issue.

**Comment by pvagner** [comment]
cifs-documents-provider is built against v 2.1.5. I am unable to do the capture.
I have even tried patching it with jcifs.smb.client.ipcSigningEnforced set to false for anonymous connections. As brought up in the issue #259.

Successfull anonymous login from VLC for android:
```
[2022/01/05 11:48:32.916744,  3] ../../auth/ntlmssp/ntlmssp_util.c:72(debug_ntlm
ssp_flags)
  Got NTLMSSP neg_flags=0x20080027
[2022/01/05 11:48:32.948962,  3] ../../auth/ntlmssp/ntlmssp_server.c:509(ntlmssp_server_preauth)
  Got user=[] domain=[] workstation=[] len1=0 len2=0
[2022/01/05 11:48:32.949126,  3] ../../source3/auth/auth.c:201(auth_check_ntlm_password)
  check_ntlm_password:  Checking password for unmapped user []\[]@[] with the new password interface
[2022/01/05 11:48:32.949199,  3] ../../source3/auth/auth.c:204(auth_check_ntlm_password)
  check_ntlm_password:  mapped user is: []\[]@[]
[2022/01/05 11:48:32.949278,  3] ../../source3/auth/auth.c:268(auth_check_ntlm_password)
  auth_check_ntlm_password: anonymous authentication for user [] succeeded
[2022/01/05 11:48:32.949408,  3] ../../auth/auth_log.c:635(log_authentication_event_human_readable)
  Auth: [SMB2,(null)] user []\[] at [St, 05 jan 2022 11:48:32.949363 CET] with [
No-Password] status [NT_STATUS_OK] workstation [] remote host [ipv4:192.168.1.250:39986] became [DESKTOP-PC]\[nobody] [S-1-5-21-3320700721-455896420-3684920096-501]. local host [ipv4:192.168.1.9:445] 
  {"timestamp": "2022-01-05T11:48:32.949659+0100", "type": "Authentication", "Authentication": {"version": {"major": 1, "minor": 2}, "eventId": 4624, "logonId": "0", "logonType": 3, "status": "NT_STATUS_OK", "localAddress": "ipv4:192.168.1.9:445", "remoteAddress": "ipv4:192.168.1.250:39986", "serviceDescription": "SMB2
", "authDescription": null, "clientDomain": "", "clientAccount": "", "workstation": "", "becameAccount": "nobody", "becameDomain": "DESKTOP-PC", "becameSid": "S-1-5-21-3320700721-455896420-3684920096-501", "mappedAccount": "", "mappedDomain": "", "netlogonComputer": null, "netlogonTrustAccount": null, "netlogonNegotiateFlags": "0x00000000", "netlogonSecureChannelType": 0, "netlogonTrustAccountSid": null, "passwordType": "No-Password", "duration": 33141}}
```


Failed login from cifs-document-provider (smb v3)
```
[2022/01/05 11:50:09.863659,  3] ../../source3/smbd/smb2_negprot.c:301(smbd_smb2
_request_process_negprot)  Selected protocol SMB3_00
[2022/01/05 11:50:09.924417,  3] ../../auth/ntlmssp/ntlmssp_util.c:72(debug_ntlm
ssp_flags)  Got NTLMSSP neg_flags=0x62088215
[2022/01/05 11:50:10.189126,  3] ../../auth/ntlmssp/ntlmssp_server.c:509(ntlmssp_server_preauth)
  Got user=[] domain=[] workstation=[] len1=24 len2=258
[2022/01/05 11:50:10.189259,  3] ../../source3/auth/auth.c:201(auth_check_ntlm_password)
  check_ntlm_password:  Checking password for unmapped user []\[]@[] with the new password interface
[2022/01/05 11:50:10.189300,  3] ../../source3/auth/auth.c:204(auth_check_ntlm_password)
  check_ntlm_password:  mapped user is: []\[]@[]
[2022/01/05 11:50:10.189334,  2] ../../source3/auth/auth.c:345(auth_check_ntlm_password)
  check_ntlm_password:  Authentication for user [] -> [] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=0
[2022/01/05 11:50:10.189415,  2] ../../auth/auth_log.c:635(log_authentication_event_human_readable)
  Auth: [SMB2,(null)] user []\[] at [St, 05 jan 2022 11:50:10.189393 CET] with [
NTLMv2] status [NT_STATUS_NO_SUCH_USER] workstation [] remote host [ipv4:192.168.1.250:40012] mapped to []\[]. local host [ipv4:192.168.1.9:445] 
  {"timestamp": "2022-01-05T11:50:10.189524+0100", "type": "Authentication", "Authentication": {"version": {"major": 1, "minor": 2}, "eventId": 4625, "logonId":
 "0", "logonType": 3, "status": "NT_STATUS_NO_SUCH_USER", "localAddress": "ipv4:192.168.1.9:445", "remoteAddress": "ipv4:192.168.1.250:40012", "serviceDescription": "SMB2", "authDescription": null, "clientDomain": "", "clientAccount": "", "workstation": "", "becameAccount": null, "becameDomain": null, "becameSid": null, "mappedAccount": "", "mappedDomain": "", "netlogonComputer": null, "netlogonTr
ustAccount": null, "netlogonNegotiateFlags": "0x00000000", "netlogonSecureChannelType": 0, "netlogonTrustAccountSid": null, "passwordType": "NTLMv2", "duration": 265402}}
```

Failed login (smb v210):
```
[2022/01/05 13:50:46.872494,  3] ../../source3/smbd/negprot.c:777(reply_negprot)
  Selected protocol SMB 2.???
[2022/01/05 13:50:46.912506,  3] ../../source3/smbd/smb2_negprot.c:301(smbd_smb2
_request_process_negprot)
  Selected protocol SMB2_10
[2022/01/05 13:50:46.957835,  3] ../../auth/ntlmssp/ntlmssp_util.c:72(debug_ntlm
ssp_flags)
  Got NTLMSSP neg_flags=0x62088215
[2022/01/05 13:50:47.013207,  3] ../../auth/ntlmssp/ntlmssp_server.c:509(ntlmssp
_server_preauth)
  Got user=[] domain=[] workstation=[] len1=24 len2=258
[2022/01/05 13:50:47.013400,  3] ../../source3/auth/auth.c:201(auth_check_ntlm_password)
  check_ntlm_password:  Checking password for unmapped user []\[]@[] with the new password interface
[2022/01/05 13:50:47.013476,  3] ../../source3/auth/auth.c:204(auth_check_ntlm_password)
  check_ntlm_password:  mapped user is: []\[]@[]
[2022/01/05 13:50:47.013554,  2] ../../source3/auth/auth.c:345(auth_check_ntlm_password)
  check_ntlm_password:  Authentication for user [] -> [] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=0
[2022/01/05 13:50:47.013702,  2] ../../auth/auth_log.c:635(log_authentication_event_human_readable)  Auth: [SMB2,(null)] user []\[] at [St, 05 jan 2022 13:50:47.013662 CET] with [NTLMv2] status [NT_STATUS_NO_SUCH_USER] workstation [] remote host [ipv4:192.168.1.250:40240] mapped to []\[]. local host [ipv4:192.168.1.9:445] 
  {"timestamp": "2022-01-05T13:50:47.013875+0100", "type": "Authentication", "Authentication": {"version": {"major": 1, "minor": 2}, "eventId": 4625, "logonId": "0", "logonType": 3, "status": "NT_STATUS_NO_SUCH_USER", "localAddress": "ipv4:192.168.1.9:445", "remoteAddress": "ipv4:192.168.1.250:40240", "serviceDescription": "SMB2", "authDescription": null, "clientDomain": "", "clientAccount": "", "workstation": "", "becameAccount": null, "becameDomain": null, "becameSid": null, "mappedAccount": "", "mappedDomain": "", "netlogonComputer": null, "netlogonTrustAccount": null, "netlogonNegotiateFlags": "0x00000000", "netlogonSecureChannelType": 0, "netlogonTrustAccountSid": null, "passwordType": "NTLMv2", "duration": 56342}}
[2022/01/05 13:50:47.014004,  3] ../../source3/auth/auth_util.c:2310(do_map_to_guest_server_info)  No such user  [] - using guest account
```

**Comment by pvagner** [comment]
Thank you for the hint, I'll look into making it work tonight and if sucessfull I'll submit a PR.
