### ISSUE TITLE
jcifs-ng 2.0.7: Generic 'Transport timeout exception' is thrown when trying to access for Linux SMB3 file share

### ISSUE THREAD

**Issue by TJDevSymc** [AgNO3/jcifs-ng#111]
Generic 'Transport timeout exception' is thrown when trying to access Linux file share(min protocol=SMB3) from another Linux machine(min protocol=2/3) using jcifs-ng 2.0.7. Instead if a specific exception is thrown which clearly states that SMB version is not supported, error handling for such cases will be easier and more transparent to the user.

PFB stack trace:

1) When Linux host(min protocol = SMB2) scans Linux share(min protocol = SMB3):
jcifs.smb.SmbException: Transport8 timedout waiting for response to SmbComSessionSetupAndX[command=SMB_COM_SESSION_SETUP_ANDX,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=37258,uid=0,mid=1,wordCount=13,byteCount=45,andxCommand=0xFF,andxOffset=0,snd_buf_size=0,maxMpxCount=1,VC_NUMBER=1,sessionKey=0,lmHash.length=0,ntHash.length=0,capabilities=4,accountName=user,primaryDomain=,NATIVE_OS=Linux,NATIVE_LANMAN=jCIFS]
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1500)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1457)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:743)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:469)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:361)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:339)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.exists(SmbFile.java:821)
	at com.vontu.filesystemcrawler.file.SmbFileAdapter.ensureExists(SmbFileAdapter.java:222)
	at com.vontu.filesystemcrawler.file.FileFactory.createFile(FileFactory.java:74)
	at com.vontu.filesystemcrawler.RootFileFactory.createRootFile(RootFileFactory.java:59)
	... 5 more
Caused by: jcifs.util.transport.RequestTimeoutException: Transport8 timedout waiting for response to SmbComSessionSetupAndX[command=SMB_COM_SESSION_SETUP_ANDX,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=37258,uid=0,mid=1,wordCount=13,byteCount=45,andxCommand=0xFF,andxOffset=0,snd_buf_size=0,maxMpxCount=1,VC_NUMBER=1,sessionKey=0,lmHash.length=0,ntHash.length=0,capabilities=4,accountName=user,primaryDomain=,NATIVE_OS=Linux,NATIVE_LANMAN=jCIFS]
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:982)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1493)
	... 21 more

2) When Linux host(min protocol = SMB3) scans Linux share(min protocol = SMB3):
jcifs.smb.SmbException: Transport9 timedout waiting for response to SmbComSessionSetupAndX[command=SMB_COM_SESSION_SETUP_ANDX,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=37258,uid=0,mid=1,wordCount=13,byteCount=45,andxCommand=0xFF,andxOffset=0,snd_buf_size=0,maxMpxCount=1,VC_NUMBER=1,sessionKey=0,lmHash.length=0,ntHash.length=0,capabilities=4,accountName=user,primaryDomain=,NATIVE_OS=Linux,NATIVE_LANMAN=jCIFS]
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1500)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1457)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:743)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:469)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:361)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:339)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.exists(SmbFile.java:821)
	at com.vontu.filesystemcrawler.file.SmbFileAdapter.ensureExists(SmbFileAdapter.java:222)
	at com.vontu.filesystemcrawler.file.FileFactory.createFile(FileFactory.java:74)
	at com.vontu.filesystemcrawler.RootFileFactory.createRootFile(RootFileFactory.java:59)
	... 5 more
Caused by: jcifs.util.transport.RequestTimeoutException: Transport9 timedout waiting for response to SmbComSessionSetupAndX[command=SMB_COM_SESSION_SETUP_ANDX,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=37258,uid=0,mid=1,wordCount=13,byteCount=45,andxCommand=0xFF,andxOffset=0,snd_buf_size=0,maxMpxCount=1,VC_NUMBER=1,sessionKey=0,lmHash.length=0,ntHash.length=0,capabilities=4,accountName=user,primaryDomain=,NATIVE_OS=Linux,NATIVE_LANMAN=jCIFS]
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:982)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1493)
	... 21 more

**Comment by mbechler** [comment]
You are somehow ending up with SMB1.
2.0.7 does not have SMB3 support, and the jcifs.smb.client.(min|max)Version also are only available starting with 2.1, so I would expect that your configuration is not doing what you expect it to.

Still it is strange that the negotation would go through without an error, can you provide logging output and/or a packet trace?
