### ISSUE TITLE
实际中遇到的问题

### ISSUE THREAD

**Issue by XINYUHACKER** [AgNO3/jcifs-ng#112]
15:38:51.834 [main] DEBUG jcifs.smb.SmbFile - openUnshared: \format.html flags: 0 access: 1 attrs: 80 options: 0
15:38:51.834 [main] DEBUG jcifs.internal.smb2.create.Smb2CreateRequest - Opening format.html
15:38:51.834 [Transport0] DEBUG jcifs.internal.smb2.create.Smb2CreateResponse - Opened format.html: 103B0000150000003500000015000000
15:38:51.836 [main] DEBUG jcifs.smb.SmbTransportImpl - Error code: 0xC0000011 for Smb2ReadRequest
15:38:51.836 [main] DEBUG jcifs.smb.SmbTreeConnection - Not retrying
jcifs.smb.SmbException: 0xC0000011
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1436)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1547)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1518)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
	at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)
	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)
	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:261)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:139)
	at org.springframework.util.FileCopyUtils.copy(FileCopyUtils.java:107)
	at com.groupds.cdr.provider.extract.file.monitor.config.SmbConfig.recursionFile(SmbConfig.java:42)
	at com.groupds.cdr.provider.extract.file.monitor.config.SmbConfig.recursionFile(SmbConfig.java:49)
	at com.groupds.cdr.provider.extract.file.monitor.config.SmbConfig.main(SmbConfig.java:26)
15:38:51.836 [main] DEBUG jcifs.smb.SmbFileInputStream - Reached end of file
jcifs.smb.SmbException: 0xC0000011
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1436)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1547)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1518)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
	at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)
	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)
	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:261)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:139)
	at org.springframework.util.FileCopyUtils.copy(FileCopyUtils.java:107)
	at com.groupds.cdr.provider.extract.file.monitor.config.SmbConfig.recursionFile(SmbConfig.java:42)
	at com.groupds.cdr.provider.extract.file.monitor.config.SmbConfig.recursionFile(SmbConfig.java:49)
	at com.groupds.cdr.provider.extract.file.monitor.config.SmbConfig.main(SmbConfig.java:26)
我在获取文件列表或者 获取文件流的时候会报错，但不会影响实际的操作，请问这部分异常怎么过滤？？我catch不掉。

**Comment by mbechler** [comment]
Sorry, I don't understand.

Is there an issue? As far as I can tell that is just the end of file indication which seems to be correctly handled by the InputStream.

**Comment by col-panic** [comment]
I see the same exception here. If this is not an error, why log debug it?
