### ISSUE TITLE
Method parse in Type3Message thows ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by McIntozh** [AgNO3/jcifs-ng#120]
When passing the NTLM Authorization as byte-array via the constructor, Type3Message always throws
```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at jcifs.ntlmssp.NtlmMessage.readSecurityBuffer(NtlmMessage.java:121)
	at jcifs.ntlmssp.Type3Message.parse(Type3Message.java:729)
	at jcifs.ntlmssp.Type3Message.<init>(Type3Message.java:321)
	at de.tle.morpheus.viewer.ViewerServlet.isAuthorized(ViewerServlet.java:196)
	at de.tle.morpheus.viewer.ViewerServlet.handle(ViewerServlet.java:85)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)
```
This is because the pos variable is not incremented by 4 after checking the message type.

**Comment by mbechler** [comment]
Created test case and merged pull request. Thanks
