### ISSUE TITLE
when security protocol is SHARE domain can be null

### ISSUE THREAD

**Issue by hgourvest** [AgNO3/jcifs-ng#133]
when security protocol is "SHARE" user can be null, so it crash with a null pointer exception.

https://github.com/AgNO3/jcifs-ng/blob/1dfe0b5e33bb3490dbfd4ed7edb61bbddd19e90a/src/main/java/jcifs/smb/NtlmUtil.java#L176

**Comment by mbechler** [comment]
Can you provide a stacktrace and how you initialize the NtlmPasswordAuthenticator/NtlmPasswordAuthentication? 
As far as I can tell user should never be null at this point.

**Comment by hgourvest** [comment]
I made some experiments with an old Ubuntu (12.04), actually the domain is null, not the user, sorry.
I initialize SmbFile with an URL like this: new SmbFile("smb://user:pass@host/foo/")
To avoid this issue have to use an empty domain, using the ';' character like this:
 new SmbFile("smb://;user:pass@host/foo/")
The default domain ("jcifs.smb.client.domain") is also null, and I don't know how to set it as an empty string, any idea?

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase()' on a null object reference
        at jcifs.smb.NtlmUtil.getLMv2Response(NtlmUtil.java:177)
        at jcifs.smb.NtlmPasswordAuthenticator.getAnsiHash(NtlmPasswordAuthenticator.java:398)
        at jcifs.smb.NtlmPasswordAuthentication.getAnsiHash(NtlmPasswordAuthentication.java:208)
        at jcifs.internal.smb1.com.SmbComTreeConnectAndX.writeParameterWordsWireFormat(SmbComTreeConnectAndX.java:101)
        at jcifs.internal.smb1.AndXServerMessageBlock.writeAndXWireFormat(AndXServerMessageBlock.java:184)
        at jcifs.internal.smb1.AndXServerMessageBlock.encode(AndXServerMessageBlock.java:140)
        at jcifs.smb.SmbTransportImpl.doSend(SmbTransportImpl.java:879)
        at jcifs.util.transport.Transport.doSend(Transport.java:276)
        at jcifs.util.transport.Transport.sendrecv(Transport.java:215)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
        at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
        at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1191)

**Comment by mbechler** [comment]
Sorry for the delay. Thanks for the information. It was the combindation of the userinfo parsing and a null default that made it possible.

If possible I would suggest switching to the new way (through Context) of providing credentials, the URL based stuff may have a couple of more issues.

**Comment by hgourvest** [comment]
Thanks for the advice and the fix.
