### ISSUE TITLE
NullPointerException trying to browse server shares (root of a SMB1 server)

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#136]
I am trying to migrate [nova video player android app](https://github.com/nova-video-player) from jcifs to jcifs-ng (jcifsng branches in aos-Video and aos-FileCoreLibrary).
I am using jcifs-ng-2.1.2-SNAPSHOT.jar from [current git](https://github.com/AgNO3/jcifs-ng/commit/1dfe0b5e33bb3490dbfd4ed7edb61bbddd19e90a).
When trying this [simple java code](https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0) to browse the root of my synology SMB1/2/3 enabled server, I get an error either using SMB1 or SMB2 CIFSContext.
It works when I invoke smbcli on a specific share (`smbcli1 1 smb://server/share/ "" user password`) but not using `smbcli 1 smb://SERVER/ "" user password` for which I get a NullPointerException :
```
Exception in thread "main" java.lang.NullPointerException
	at jcifs.internal.smb1.net.SmbShareInfo.equals(SmbShareInfo.java:129)
	at java.base/java.util.HashMap.getNode(HashMap.java:579)
	at java.base/java.util.HashMap.containsKey(HashMap.java:596)
	at java.base/java.util.HashSet.contains(HashSet.java:204)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:164)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1191)
	at smbcli1.main(smbcli1.java:84)
```
Any insights on what I am doing wrong or should be doing would be welcome.
Thank you for maintaining and making jcifs evolve to support SMB2/3.

**Comment by mbechler** [comment]
This looks to be an incomplete fix for #108. NPE should be fixed in master, however it is still unclear why we end up with an unset name in the first place and what we should do with it. Can you provide a packet capture of the situation when this happens?

**Comment by courville** [comment]
Thanks for getting back to me. Please find below the wireshark pcap with the subnet filter ip.src == 192.168.0.1/24 && ip.dst == 192.168.0.1/24: 
[jcifsng-npe_browse_server_smb1.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2872868/jcifsng-npe_browse_server_smb1.pcap.zip)
 If you need different captures (via tcpdump or anything else please) specify what specific command/filter I should use to reveal quicker the issue.

**Comment by mbechler** [comment]
Thanks. I think this is related to #130 and should be fixed by https://github.com/AgNO3/jcifs-ng/commit/8a7d00afd125d603b98a7318dd81c4d7a5b7b32d

**Comment by courville** [comment]
I have realigned with latest master and unfortunately I get this MalformedURLException now:
```
[main] ERROR jcifs.smb.ShareEnumIterator - Failed to create child URL
java.net.MalformedURLException: Name must not be empty
	at jcifs.smb.SmbFile.checkName(SmbFile.java:580)
	at jcifs.smb.SmbFile.<init>(SmbFile.java:464)
	at jcifs.smb.ShareEnumIterator.adapt(ShareEnumIterator.java:93)
	at jcifs.smb.ShareEnumIterator.advance(ShareEnumIterator.java:66)
	at jcifs.smb.ShareEnumIterator.next(ShareEnumIterator.java:116)
	at jcifs.smb.ShareEnumIterator.next(ShareEnumIterator.java:34)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:292)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli1.main(smbcli1.java:84)
[main] WARN jcifs.smb.SmbTreeConnection - Referral failed, trying next
jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1360)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at smbcli1.main(smbcli1.java:85)
Exception in thread "main" jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1360)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at smbcli1.main(smbcli1.java:85)
[Thread-0] WARN jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport0[DS414<20>/192.168.0.2:445,state=5,signingEnforced=false,usage=1]: [SmbSession[credentials=media,targetHost=ds414,targetDomain=null,uid=58470,connectionState=2,usage=1]]
[Thread-0] WARN jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=media,targetHost=ds414,targetDomain=null,uid=58470,connectionState=3,usage=1]:[SmbTree[share=IPC$,service=IPC,tid=12494,inDfs=false,inDomainDfs=false,connectionState=2,usage=0], SmbTree[share=APP,service=?????,tid=0,inDfs=false,inDomainDfs=false,connectionState=0,usage=0]]
```
Associated pcap is here 
[jcifsng-MalformedURLException_browse_server_smb1.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2872904/jcifsng-MalformedURLException_browse_server_smb1.pcap.zip)

**Comment by mbechler** [comment]
Yes, there appears to be another problem. Only 1024 of the fragment that is supposed to be 1628 byte long is returned in the response. This conincides with the seemingly artificial limit set by SmbPipeHandleImpl for this type of pipes.
I think the correct fix is using further reads to get the remaining data (#130) from the pipe.
I've commited something you could try.

**Comment by courville** [comment]
Thank you very much for your help.
OK now I get SmbAuthException though same user/password works on a child share (i.e. correct authentication).
```
[main] WARN jcifs.smb.SmbTreeConnection - Referral failed, trying next
jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1360)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at smbcli1.main(smbcli1.java:85)
Exception in thread "main" jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1360)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at smbcli1.main(smbcli1.java:85)
[Thread-0] WARN jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport0[DS414<20>/192.168.0.2:445,state=5,signingEnforced=false,usage=1]: [SmbSession[credentials=media,targetHost=ds414,targetDomain=null,uid=37998,connectionState=2,usage=1]]
[Thread-0] WARN jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=media,targetHost=ds414,targetDomain=null,uid=37998,connectionState=3,usage=1]:[SmbTree[share=IPC$,service=IPC,tid=30436,inDfs=false,inDomainDfs=false,connectionState=2,usage=0], SmbTree[share=APP,service=?????,tid=0,inDfs=false,inDomainDfs=false,connectionState=0,usage=0]]
```
Associated new pcap is there 
[jcifsng-SmbAuthException_browse_server_smb1.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2872987/jcifsng-SmbAuthException_browse_server_smb1.pcap.zip)

**Comment by mbechler** [comment]
This is happening connecting to the "app" share for the exists() call. Does the user have access to that? Looks to be using the correct session. 

Not sure whether we changed some behavior there but I think it is correct for exists() to throw on access denied when the resource actually exists. You should be able to catch that.

**Comment by courville** [comment]
> This is happening connecting to the "app" share for the exists() call. Does the user have access to that? Looks to be using the correct session.
> 
> Not sure whether we changed some behavior there but I think it is correct for exists() to throw on access denied when the resource actually exists. You should be able to catch that.

I use the same user/password for root and shares, it works on the shares and jcifs-old was working when browsing root with same credentials. I did checked that I made no mistake...
I can try to get captures with jcifs-old if it helps.

**Comment by mbechler** [comment]
Does a direct connection to the _app_ share work with these credentials?

**Comment by courville** [comment]
> Does a direct connection to the _app_ share work with these credentials?

yes `smbcli 1 smb://ds414/video/ "" login password `works and `smbcli 1 smb://ds414/ "" login password` fails.
pcap of the share browsing is there [jcifsng-browse_server_shares_smb1_working.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2873038/jcifsng-browse_server_shares_smb1_working.pcap.zip)

**Comment by mbechler** [comment]
`smbcli 1 smb://ds414/app/ "" media password` as well?

I can't find the relevant change but I think I remember changing something in the exists() exception behavior, that might now cause it to throw on access denied, before it might just have returned false (or even true). Now you are able to distinguish the different situations.

So you might just have to do something like:
```
boolean exists = false;
try {
  exists = file.exists();
} catch ( SmbAuthException e ) {
  // depending on whether you want shares without access to exist
}
System.out.println(file.getPath() + (exists ? " exists" : " does not exist"));
```

**Comment by courville** [comment]
Indeed there are protected subshares below root that have different credentials.
Former behavior of jcifs-notng was to list the root with all visible shares.
This was providing the ability when clicking to share on which you do not have credentials to ask for these.

**Comment by courville** [comment]
I guess that what I do not entirely understand from a conception standpoint is why I get SmbAuthException during the listing of the root on the shares where I do not get the right credentials.
It should list the shares without investigating deeper.

**Comment by mbechler** [comment]
As far as I get it you can list the shares just fine, the exists() call is what throws

**Comment by courville** [comment]
> As far as I get it you can list the shares just fine, the exists() call is what throws

I think there is something more since with the try/catch on the exists(), I still have with `smbcli 1 smb://ds414/ "" media password` on each shares that I do not have the credentials:

```
[main] WARN jcifs.smb.SmbTreeConnection - Referral failed, trying next
jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1360)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1557)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at smbcli1.main(smbcli1.java:88)
smb://ds414/app/ does not exist
```

**Comment by mbechler** [comment]
Admittedly, logging a warning might be a bit harsh in that case.
What does your code look like now? With the exception you should now be able to distinguish three cases:
- exists + accessible
- exists + inaccessible
- does not exist (however on the share level that probably should not happen)

**Comment by courville** [comment]
> Admittedly, logging a warning might be a bit harsh in that case.
> What does your code look like now? With the exception you should now be able to distinguish three cases:
> 
> * exists + accessible
> * exists + inaccessible
> * does not exist (however on the share level that probably should not happen)

I get it know thanks. New resulting code is there https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0

**Comment by courville** [comment]
OK I cannot resist to thank you for your tremendous support and work.
Now with latest git I can browse with Nova Video Player samba SMB2 shares on synology, win10 (only remaining problem is macos now).
