### ISSUE TITLE
RuntimeCIFSException while browsing SMB server root and share when enabling SMB2

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#137]
Sorry to bother you again but I am continuing my testing on other samba servers (Swisscom Internet BOX now) and with the amended code here https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0 I get RuntimeCIFSException when trying to browse root and shares of a server enabling SMB2 (ok with SMB1).
I am using latest jcifs-ng 2.1.2 snapshot (611185728206737b635becf7e122b9cd1ab9d94f).
- OK `smbcli 1 smb://internetbox-nas/ "" lurker password`, associated pcap file: [jcifsng-swisscom_root_smb1-OK.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2878958/jcifsng-swisscom_root_smb1-OK.pcap.zip)
- NOK RuntimeCIFSException `smbcli 2 smb://internetbox-nas/ "" lurker password`, associated pcap file: [jcifsng-swisscom_root_smb2-NOK.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2878960/jcifsng-swisscom_root_smb2-NOK.pcap.zip)
```
smbFile is a server
[main] WARN jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport0[internetbox-nas/192.168.1.220:445,state=5,signingEnforced=false,usage=3]: [SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=2,usage=3]]
[main] WARN jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=3,usage=3]:[SmbTree[share=IPC$,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
[main] WARN jcifs.smb.SmbTreeImpl - Disconnected tree while still in use SmbTree[share=IPC$,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
[main] WARN jcifs.smb.SmbSessionImpl - Failed to disconnect tree SmbTree[share=IPC$,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:823)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1127)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:760)
	at jcifs.util.transport.Transport.disconnect(Transport.java:686)
	at jcifs.util.transport.Transport.disconnect(Transport.java:657)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:672)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:84)
Exception in thread "main" jcifs.smb.SmbException: smb://internetbox-nas/
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:175)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:84)
Caused by: jcifs.CIFSException: Mismatched attributes validating negotiate info
	at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:736)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:668)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	... 4 more
```
- OK `smbcli 1 smb://internetbox-nas/MARC/ "" lurker password`, associated pcap file: [jcifsng-swisscom_share_smb1-OK.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2878968/jcifsng-swisscom_share_smb1-OK.pcap.zip)
- NOK RuntimeCIFSException `smbcli 2 smb://internetbox-nas/MARC/ "" lurker password`, associated pcap file: [jcifsng-swisscom_share_smb2-NOK.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2878967/jcifsng-swisscom_share_smb2-NOK.pcap.zip)
```
[main] WARN jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport0[internetbox-nas/192.168.1.220:445,state=5,signingEnforced=false,usage=3]: [SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=2,usage=3]]
[main] WARN jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=3,usage=3]:[SmbTree[share=MARC,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
[main] WARN jcifs.smb.SmbTreeImpl - Disconnected tree while still in use SmbTree[share=MARC,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
[main] WARN jcifs.smb.SmbSessionImpl - Failed to disconnect tree SmbTree[share=MARC,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:823)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1127)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:760)
	at jcifs.util.transport.Transport.disconnect(Transport.java:686)
	at jcifs.util.transport.Transport.disconnect(Transport.java:657)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:672)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.getType(SmbFile.java:885)
	at smbcli.main(smbcli.java:71)
smbFile is a filesystem
[main] WARN jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport1[internetbox-nas/192.168.1.220:445,state=5,signingEnforced=false,usage=3]: [SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=2,usage=3]]
[main] WARN jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=3,usage=3]:[SmbTree[share=MARC,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
[main] WARN jcifs.smb.SmbTreeImpl - Disconnected tree while still in use SmbTree[share=MARC,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
[main] WARN jcifs.smb.SmbSessionImpl - Failed to disconnect tree SmbTree[share=MARC,service=null,tid=11,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:823)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1127)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:760)
	at jcifs.util.transport.Transport.disconnect(Transport.java:686)
	at jcifs.util.transport.Transport.disconnect(Transport.java:657)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:672)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:84)
Exception in thread "main" jcifs.smb.SmbException: Failed to connect to server
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:430)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:84)
Caused by: jcifs.CIFSException: Mismatched attributes validating negotiate info
	at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:736)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:668)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	... 5 more
```

**Comment by mbechler** [comment]
The (broken) PCAP seems to be missing the server responses.

**Comment by courville** [comment]
> The (broken) PCAP seems to be missing the server responses.

indeed, my bad: previous post has been edited with correct captures containing hopefully all the exchanges.

**Comment by courville** [comment]
Now everything works as expected.
