### ISSUE TITLE
SmbAuthException (listFiles()) when browsing root of MacOS X SMB2 server (share ok)

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#138]
Continuing testing (and adopting) jcifs-ng for [nova video player](https://github.com/nova-video-player/aos-AVP), I am experiencing issues with MacOS X SMB2 server root browsing. It happens to be ok with a share but not the root. I am still using this test java program: https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0
I am using latest jcifs-ng 2.1.2 snapshot ([6111857](https://github.com/AgNO3/jcifs-ng/commit/611185728206737b635becf7e122b9cd1ab9d94f)). 
- OK `smbcli 2 smb://imarc/tmp/ "" cpasmoi password` with associated pcap file: [jcifs-MacOSX_server-browse_share-OK.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2878820/jcifs-MacOSX_server-browse_share-OK.pcap.zip)
- NOK` smbcli 2 smb://imarc/ "" cpasmoi password` (SmbAuthException in listFiles()) with associated pcap file: [jcifs-MacOSX_server-browse_root-NOK.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2878821/jcifs-MacOSX_server-browse_root-NOK.pcap.zip)

```
Exception in thread "main" jcifs.smb.SmbAuthException: Access is denied.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1410)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFile.openUnshared(SmbFile.java:665)
        at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:169)
        at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
        at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
        at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
        at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
        at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
        at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:92)
        at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:153)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
        at smbcli.main(smbcli.java:116)
```
Please let me know if you want me to do other experiments in order to provide more information.

**Comment by courville** [comment]
Oh forgot yo mention that browsing of server root works when doing `smbclient -Ucpasmoi -L 192.168.0.50`
I can provide the pcap if needed.

**Comment by courville** [comment]
Please note that the above two posts have been edited to replace incomplete pcap files missing server response to correct ones allowing investigation.

**Comment by mbechler** [comment]
A bit of guesswork involved but the server might not like the CREATE disposition of the open call, which seems generally odd and a result of taking over the O_EXCL from the old code (which is odd, too, but I'd rather not change that). Please try the patch I committed.

**Comment by courville** [comment]
> A bit of guesswork involved but the server might not like the CREATE disposition of the open call, which seems generally odd and a result of taking over the O_EXCL from the old code (which is odd, too, but I'd rather not change that). Please try the patch I committed.

I just tested your patch and I confirm that this solves the problem: I can now browse root of MacOSX server. 
Thank you very much!
