### ISSUE TITLE
Release for 2.1 branch due to Bouncy Castle update?

### ISSUE THREAD

**Issue by matheis** [AgNO3/jcifs-ng#140]
Hi Moritz,

we use jcifs-ng in our product and wanted to update Bouncy Castle to the latest version 1.61. In our tests we hit a ClassCastException issue in jcifs.spnego.NegTokenInit

```
Caused by: java.lang.ClassCastException: org.bouncycastle.asn1.DLApplicationSpecific cannot be cast to org.bouncycastle.asn1.DERApplicationSpecific
                at jcifs.spnego.NegTokenInit.parse(NegTokenInit.java:171)
                at jcifs.spnego.NegTokenInit.<init>(NegTokenInit.java:78)
                at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:185)
```

Looking at the code I saw, that you've already fixed it: https://github.com/AgNO3/jcifs-ng/commit/2e8ffdd86334ba26130467f8ee2f8131f289ba29 which is very nice. :)

Could you please prepare a 2.1.x release that includes this change?

Thanks, Ivo

**Comment by mbechler** [comment]
There is some stuff I would like to get some feedback on, but I guess next weekend I'll do a new release.
