### ISSUE TITLE
IOException: Message size exceeds maximum buffer size 655535 in SmbTransportImpl.doRecvSMB2()

### ISSUE THREAD

**Issue by justoperez** [AgNO3/jcifs-ng#15]
We are running against a server running Windows 2008 R2. We get the following exception in SmbTransportImpl.java when calling SmbFile.listFiles() on a directory containing 654 files. The SmbFile.listFiles() call works most of the time, but somehow it fails in this specific directory.

java.io.IOException: Message size 0 exceeds maxiumum buffer size 65535
    at jcifs.smb.SmbTransportImpl.doRecvSMB2(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTransportImpl.doRecv(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.util.transport.Transport.loop(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.util.transport.Transport.run(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at java.lang.Thread.run(Thread.java:785) [?:1.8.0-internal]

These is the stack trace from calling Smb.listFiles(),

[2017-11-18 05:38:50,251] WARN  [-2047669190@qtp-771331191-0] jcifs.util.transport.Transport sendrecv failed
jcifs.util.transport.TransportException: Transport1 error reading response to command=SMB2_QUERY_DIRECTORY,status=0,flags=0x0004,mid=6,wordCount=0,byteCount=34
    at jcifs.util.transport.Transport.waitForResponses(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.util.transport.Transport.sendrecv(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTransportImpl.sendrecv(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTransportImpl.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbSessionImpl.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeImpl.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.send0(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.DirFileEntryEnumIterator2.open(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.DirFileEntryEnumIterator2.<init>(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbEnumerationUtil.doEnum(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbEnumerationUtil.listFiles(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbFile.listFiles(Unknown Source) [jcifs-ng-2.0.1-flx.1.jar:?]

The only JCIFS properties we have set are:

jcifs.smb.client.enableSMB2=true
jcifs.traceResources=true
jcifs.util.loglevel=4

The funny thing is that when we add another folder or file(s) to the directory, then the SmbFile.listFiles() call works fine. So we suspect that there is something odd happening when receiving/parsing the responses in SmbTransportImpl.doRecvSMB2().

I added 'log.warn()' debug messages to doRecvSMB2() to see what is happening in this method and noticed that it throws here,

if ( ( nextCommand != 0 && nextCommand > maximumBufferSize ) || ( nextCommand == 0 && size > maximumBufferSize ) ) {
    throw new IOException(String.format("Message size %d exceeds maxiumum buffer size %d", nextCommand, maximumBufferSize));
}

where nextCommand = 0 and size is 65536 which is one more than the maximumBufferSize of 65535. I notice that maximumBufferSize is initialized in BaseConfiguration.java to 0xFFFF and this value cannot be changed thru a JCIFS property.

Below is the doRecvSMB2() method with the debug log.warn() messages I added. Next to each log.warn() message I annotated the value I get (see comments). I also tried to double the size of the maximumBufferSize to 0x1FFFE but that didn't help. 

Any ideas or suggestions would be greatly appreciated. Not sure what is going on.

    private void doRecvSMB2 ( CommonServerMessageBlock response ) throws IOException, SMBProtocolDecodingException {
    	log.warn("doRecvSMB2: Start HERE");
        int size = ( Encdec.dec_uint16be(this.sbuf, 2) & 0xFFFF ) | ( this.sbuf[ 1 ] & 0xFF ) << 16;
        log.warn("doRecvSMB2: first size="+size); // size=65688 
        if ( size < ( Smb2Constants.SMB2_HEADER_LENGTH + 1 ) ) {
            throw new IOException("Invalid payload size: " + size);
        }

        if ( this.sbuf[ 0 ] != (byte) 0x00 || this.sbuf[ 4 ] != (byte) 0xFE || this.sbuf[ 5 ] != (byte) 'S' || this.sbuf[ 6 ] != (byte) 'M'
                || this.sbuf[ 7 ] != (byte) 'B' ) {
            throw new IOException("Houston we have a synchronization problem");
        }

        int nextCommand = Encdec.dec_uint32le(this.sbuf, 4 + 20);
        log.warn("doRecvSMB2: first nextCommand="+nextCommand); // nextCommand = 152
        int maximumBufferSize = getContext().getConfig().getMaximumBufferSize();
        int msgSize = nextCommand != 0 ? nextCommand : size;
        log.warn("doRecvSMB2: fist msgSize="+msgSize+", maximumBufferSize="+maximumBufferSize); 
                 //  msgSize=152, maximumBufferSize=65535
        if ( msgSize > maximumBufferSize ) {
            throw new IOException(String.format("Message size %d exceeds maxiumum buffer size %d", msgSize, maximumBufferSize));
        }

        ServerMessageBlock2Response cur = (ServerMessageBlock2Response) response;
        byte[] buffer = getContext().getBufferCache().getBuffer();
        try {
            int rl = nextCommand != 0 ? nextCommand : size;
            log.warn("doRecvSMB2: first rl="+rl); // first rl=152

            // read and decode first
            System.arraycopy(this.sbuf, 4, buffer, 0, Smb2Constants.SMB2_HEADER_LENGTH);
            readn(this.in, buffer, Smb2Constants.SMB2_HEADER_LENGTH, rl - Smb2Constants.SMB2_HEADER_LENGTH);

            int len = cur.decode(buffer, 0);

            if ( len > rl ) {
                throw new IOException(String.format("WHAT? ( read %d decoded %d ): %s", rl, len, cur));
            }
            else if ( nextCommand != 0 && len > nextCommand ) {
                throw new IOException("Overlapping commands");
            }
            size -= rl; // size = 65688 - 152 = 65536
            log.warn("doRecvSMB2: second size="+size); // second size=65536
            
            while ( size > 0 && nextCommand != 0 ) {
                cur = (ServerMessageBlock2Response) cur.getNextResponse();
                if ( cur == null ) {
                    log.warn("Response not properly set up");
                    this.in.skip(size);
                    break;
                }

                // read next header
                readn(this.in, buffer, 0, Smb2Constants.SMB2_HEADER_LENGTH);
                nextCommand = Encdec.dec_uint32le(buffer, 20);
                log.warn("doRecvSMB2: nextCommand="+nextCommand); // nextCommand = 0
                
                if ( ( nextCommand != 0 && nextCommand > maximumBufferSize ) || ( nextCommand == 0 && size > maximumBufferSize ) ) {
                	log.warn("doRecvSMB2: Throwing-2 msgSize > maximumBufferSize"); 
                               // size=65536 > maximumBufferSize=65535
                	throw new IOException(String.format("Message size %d exceeds maxiumum buffer size %d", nextCommand, maximumBufferSize));
                }

**Comment by mbechler** [comment]
The response size should be determined by the output buffer size we send which is
```
config.getMaximumBufferSize() - Smb2QueryDirectoryResponse.OVERHEAD; // == Smb2Constants.SMB2_HEADER_LENGTH + 8
```
which It seems to me is missing 4 bytes in the Smb2QueryDirectoryResponse case (for the initial transport header).

You can try setting
```
    public static final int OVERHEAD = Smb2Constants.SMB2_HEADER_LENGTH + 4 + 8;
```
in Smb2QueryDirectoryResponse, I think that should be the issue. I will try to build a testcase to reproduce.

**Comment by mbechler** [comment]
I've been trying pretty hard but so far haven't been able to reproduce the issue. Even if I manage to fill the output buffer completely, the servers I have available (including a 2008r2 one) won't return a response in excess of the maximum buffer size. Maybe there is some strange case which add extra padding.

Adding the 4 bytes of extra tolerance as I suggested certainly won't hurt and I would still assume will fix the problem.

Any chance you would be able to share a network trace showing the issue so that I might be able to figure out what is really happening there?

**Comment by thanh-vn** [comment]
Tried the suggestion as below.  We still see the same issue. 
```
public class Smb2QueryDirectoryResponse extends ServerMessageBlock2Response {

    /**
     * 
     */
    //public static final int OVERHEAD = Smb2Constants.SMB2_HEADER_LENGTH + 8;
    public static final int OVERHEAD = Smb2Constants.SMB2_HEADER_LENGTH + 4 + 8;
```
We did not see any change of the debug values that justoperez added above:
----------------------
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: first size=65688
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: first nextCommand=152
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: fist msgSize=152, maximumBufferSize=65535
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: first rl=152
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: second size=65536
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: nextCommand=0
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - doRecvSMB2: Throwing-2 msgSize > maximumBufferSize
2017-11-18 09:12:47 WARN  SmbTransportImpl:? - Failure decoding message, disconnecting transport
-----------------------

Thanks,

**Comment by mbechler** [comment]
That's the directory listing issue as well? A padding issue could possibly be up to 8 bytes I guess. 

If OVERHEAD is increased and therefor the output buffer size is decreased that response really should be getting smaller (unless the server ignores the value we sent). Really need to look at these buffer sizes in a network dump.

**Comment by justoperez** [comment]
Your comments are much appreciated. As my colleague mentioned, we tried your suggestion but did not make a difference.

I'm including the network trace you requested (it's one cap file that I zipped). I hope this helps you reproduce the issue and see what is happening to the buffer sizes.

If you need any other information please let us know, we are happy to get you anything you need. Thank you very much for your help. 

[smb2_fail.zip](https://github.com/AgNO3/jcifs-ng/files/1484741/smb2_fail.zip)

**Comment by mbechler** [comment]
Thanks. Okay, so the actual payload buffer size is 65462 + 64 + 8 = 65534 which is as expected and would very nicely fit into the 65535 byte buffer, however if that gets padded to an 8 byte boundary, which seems to be the case, we arrive at a total response size of 65536 (and the suggested 4 byte decrease is insufficient). So to fully account for that
```
 public static final int OVERHEAD = Smb2Constants.SMB2_HEADER_LENGTH + 8 + 8;
```
In the long term It's probably better to just increase the max buffer size to 0x10000 so that the alignment can be done, but I'll have to check what needs to be changed for SMB1 then.

**Comment by justoperez** [comment]
Thank you, it worked! 

I changed the OVERHEAD in Smb2QueryDirectoryResponse.java as you recommended in your previous post -> public static final int OVERHEAD = Smb2Constants.SMB2_HEADER_LENGTH + 8 + 8;

Now we can successfully list all the directories that were previously failing.

Just in case it might be helpful to you. Here is a zip file with two tracedumps: one WITH the fix applied (smb2_success.cap) and one WITHOUT the fix (smb2_failure.cap). 

[smb2_tracedumps.zip](https://github.com/AgNO3/jcifs-ng/files/1484985/smb2_tracedumps.zip)

**Comment by thanh-vn** [comment]
Thank you for the suggestion with SMB2.
Please let us know what you think with SMB1 case.

**Comment by mbechler** [comment]
I ended up committing a slightly different fix. Also managed to come up with a reproducer and it looks good so far. Can you check that it works for you, too?

**Comment by thanh-vn** [comment]
Yes, we will try that.  Does that mean only for SM2 fix?  
We just confirmed that the issue happens also for SMB1 when we have jcifs.smb.client.enableSMB2=false.  With SMB1, it is not happening consistently to a folder.  Do you have any suggestion for SMB1?

**Comment by mbechler** [comment]
That specific issue does not apply to SMB1. If there is a simular issue with SMB1 we need to investigate that further.

**Comment by thanh-vn** [comment]
Yes, the fix 'SMB2: properly account for padding in output buffer size calculations' fixed the problem on SMB2.
Thank you!

**Comment by justoperez** [comment]
Thank you for your fix! I'm closing this issue as resolved. 

If we see a problem with SMB1 we will open a different issue.

**Comment by mbechler** [comment]
2.0.3 release is on it's way.

**Comment by courville** [comment]
Strangely with current master I get a similar error message using Android emulator connecting to my macOS developing platform acting as the SMBv2 share on a directory containing 440 files and directories:
```
2021-08-24 17:07:11.808 4537-4537/org.courville.nova D/ListingFragment: startListing smb://10.0.2.2/marcshare/hop/share/
2021-08-24 17:07:11.812 4537-6334/org.courville.nova W/jcifs.smb.SmbTransportImpl: [Transport35] WARN  jcifs.smb.SmbTransportImpl - Failure decoding message, disconnecting transport
    java.io.IOException: Message size 65590 exceeds maxiumum buffer size 65536
        at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1222)
        at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1147)
        at jcifs.util.transport.Transport.loop(Transport.java:459)
        at jcifs.util.transport.Transport.run(Transport.java:779)
        at java.lang.Thread.run(Thread.java:923)
2021-08-24 17:07:11.812 4537-6334/org.courville.nova W/jcifs.smb.SmbTransportImpl: [Transport35] WARN  jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport35[0.0.0.0<00>/10.0.2.2:445,state=5,signingEnforced=false,usage=3]: [SmbSession[credentials=marc,targetHost=10.0.2.2,targetDomain=null,uid=0,connectionState=2,usage=2]]
2021-08-24 17:07:11.812 4537-6334/org.courville.nova W/jcifs.smb.SmbSessionImpl: [Transport35] WARN  jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=marc,targetHost=10.0.2.2,targetDomain=null,uid=0,connectionState=3,usage=2]:[SmbTree[share=MARCSHARE,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]]
2021-08-24 17:07:11.812 4537-6334/org.courville.nova W/jcifs.smb.SmbTreeImpl: [Transport35] WARN  jcifs.smb.SmbTreeImpl - Disconnected tree while still in use SmbTree[share=MARCSHARE,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=3,usage=2]
2021-08-24 17:07:11.813 4537-6338/org.courville.nova W/jcifs.util.transport.Transport: [Thread-126] WARN  jcifs.util.transport.Transport - sendrecv failed
    jcifs.util.transport.TransportException: Transport35 error reading response to command=SMB2_QUERY_DIRECTORY,status=0,flags=0x0004,mid=10,wordCount=0,byteCount=34
        at jcifs.util.transport.Transport.waitForResponses(Transport.java:351)
        at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1025)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1549)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.DirFileEntryEnumIterator2.open(DirFileEntryEnumIterator2.java:96)
        at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67)
        at jcifs.smb.DirFileEntryEnumIterator2.<init>(DirFileEntryEnumIterator2.java:57)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:223)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1287)
        at com.archos.filecorelibrary.jcifs.JcifListingEngine$JcifListingThread.run(JcifListingEngine.java:113)
     Caused by: java.io.IOException: Message size 65590 exceeds maxiumum buffer size 65536
        at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1222)
        at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1147)
        at jcifs.util.transport.Transport.loop(Transport.java:459)
        at jcifs.util.transport.Transport.run(Transport.java:779)
        at java.lang.Thread.run(Thread.java:923)
```
Perhaps not the best way to reply on a close issue: I can open a new one if need be.

**Comment by mbechler** [comment]
A new issue would be great. Can you provide a network capture for this as well?
