### ISSUE TITLE
Can't create file/folder or delete file

### ISSUE THREAD

**Issue by Kitsune2222** [AgNO3/jcifs-ng#150]
val file = SmbFile("smb://192.168.0.173/share/g/2.txt", BaseContext(PropertyConfiguration(System.getProperties())).withAnonymousCredentials())
file.createNewFile()
Error Access Denied. file.canWrite() return true. With other app i'm can modify files on this server.
`jcifs.smb.SmbAuthException: Access is denied.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1410)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1747)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1716)
        at jcifs.smb.SmbFile.createNewFile(SmbFile.java:1798)`

**Comment by Guiorgy** [comment]
I can only say that it works fine for me. Though I am using the SingletoneContext:
```java
Properties properties = new Properties();
properties.setProperty("jcifs.netbios.wins", SHARED_IP);
properties.setProperty("jcifs.smb.client.responseTimeout", "2500");
properties.setProperty("jcifs.smb.client.soTimeout", "5000");
SingletonContext.init(properties);
SingletonContext smbContext = SingletonContext.getInstance();
SmbFile file = new SmbFile(path, smbContext);
```

**Comment by Kitsune2222** [comment]
> ```java
> smbContext = SingletonContext.getInstance()
> ```

It not work, the same error, i'm use latest 2.1.2 version

**Comment by mbechler** [comment]
Are you sure that your server allows anonymous write access? canWrite does not check permissions at all. Do other operations (e.g. list, read) succeed?

**Comment by Kitsune2222** [comment]
> Are you sure that your server allows anonymous write access? canWrite does not check permissions at all. Do other operations (e.g. list, read) succeed?

Yes with others app i'm can write in this anonymous server. With other server with login and password also the same problem? Other operations (list) is succeed.

**Comment by mbechler** [comment]
Can you get me a packet trace of a failed attempt with jcifs-ng, along with one of a working client?

**Comment by Kitsune2222** [comment]
How do it? Sorry for stupid questions, but i'm not good understand network. I'm try use this library in android

**Comment by mbechler** [comment]
Not really sure about android, do you have access to the server system as well? Then you could run wireshark on that system to capture the packet traces.

**Comment by Kitsune2222** [comment]
Log files and screenshots:
https://drive.google.com/open?id=1OdZ99_NIpM7qYqBEf0S5oh5e5lhD3qrq

**Comment by mbechler** [comment]
Thanks. Can you try to get the full context for the working one (connection/session setup is currently missing) and also configure that client to use SMB2 for better comparison.

**Comment by Kitsune2222** [comment]
Updated, no screenshots, because many text.
Now SMB2 client is Windows 10 device, i'm can't find app for android with smb2 support.
If it important:
192.168.0.110 - win 10 client device
192.168.0.153 - android client device
192.168.0.173 - server

**Comment by mbechler** [comment]
Sorry for all the trouble, but I don't think the request that actually creates the folder is in there (these are just "open" calls). Also, unfortunately, the  session setup is still missing - the easiest way to get it reliably might be to restart the system first).

**Comment by Kitsune2222** [comment]
I'm not understand, what else I need to do? 
I'm reboot windows 
Added: Folder Created (SMB2-UPD2).pcapng

**Comment by mbechler** [comment]
This one looks good. Although there are some differences in the create call, I don't think these should really matter.
I think this might be an issue of anonymous/null authentication (client does not provide any credentials) vs. guest authentication (essentially logging in with "wrong" credentials).
Can you try using withGuestCredentials instead of withAnonymousCredentials (although I have to admit, I'm not even sure that options works properly).

**Comment by Kitsune2222** [comment]
With guest the same
Added: jcifs (withGuestCredentials).pcapng

**Comment by mbechler** [comment]
Almost as I had expected, the withGuestCredentials does not seem to do what it is supposed to. Let me try to fix that first and get back to you.

**Comment by Kitsune2222** [comment]
Ok, thanks for help

**Comment by mbechler** [comment]
The guest login stuff should be fixed in master now.

**Comment by Kitsune2222** [comment]
Thank you! Seems problem fixed, now i'm can create folder withGuestCredentials.
Added log screenshot: jcifs (withGuestCredentials-Folder created).png
Also if i'm not mistaken there was the same error with login and password, i'm now not close issue, because check it later and write.

**Comment by Kitsune2222** [comment]
With login and password also is ok, thanks!

**Comment by col-panic** [comment]
I face this error, with the current patched build on a Windows Server 2012 which I can access without problem as guest using the OS X onbard connection

```
jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1410) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:604) ~[jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:620) [jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564) [jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485) [jcifs-ng-2.1.3-SNAPSHOT.jar:na]
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461) [jcifs-ng-2.1.3-SNAPSHOT.jar:na]
```

**Comment by mbechler** [comment]
Please open a seperate issue for that. And more information is needed, preferrable packet traces of the failing jcifs attempt, a successful one and a debug log.

**Comment by col-panic** [comment]
I have added it to #105  as it seems to cover the same bug.

**Comment by mbechler** [comment]
Have you tried latest master, and using withGuestCredentials?

**Comment by col-panic** [comment]
I just fetched and built the current master and switched to guest credentials - it does however still fail.

**Comment by mbechler** [comment]
Again, please open a separate issue for this. Additionally to the trace from #105 (preferrably the capture file itself), please also provide a trace of a working client.

**Comment by col-panic** [comment]
see #166
