### ISSUE TITLE
non authorized guest login on MacOSX does not result in a SmbAuthException

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#152]
When doing `smbcli 2 smb://IELIOTT/ "" GUEST ""` on a MacOSX where the GUEST login is not allowed, an SmbException (Failed to connect) is received instead of an SmbAuthException.
Here is the pcap: [macosx-guest-nosmbauthexception.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/2975131/macosx-guest-nosmbauthexception.pcap.zip)
And the trace log:
```
2019-03-17 13:31:38 ERROR PropertyConfiguration:702 - UniAddress resolveOrder specifies WINS however  WINS server has not been configured
2019-03-17 13:31:38 ERROR PropertyConfiguration:702 - UniAddress resolveOrder specifies WINS however  WINS server has not been configured
2019-03-17 13:31:38 INFO  smbcli:105 - Enabling SMB2
2019-03-17 13:31:44 INFO  smbcli:125 - smbFile is a server
2019-03-17 13:31:44 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport0[IELIOTT/192.168.0.102:445,state=0,signingEnforced=false,usage=1]
2019-03-17 13:31:44 DEBUG Transport:568 - Connecting Transport0
2019-03-17 13:31:44 DEBUG SmbTransportImpl:681 - Connecting in state 1 addr 192.168.0.102
2019-03-17 13:31:44 DEBUG Transport:640 - Interrupting transport thread
2019-03-17 13:31:44 DEBUG Transport:642 - Joining transport thread
2019-03-17 13:31:44 DEBUG Transport:644 - Joined transport thread
2019-03-17 13:31:44 DEBUG SmbTransportPoolImpl:258 - Removing transport connection Transport0[IELIOTT/192.168.0.102:445,state=4,signingEnforced=false,usage=1] (1340565491)
2019-03-17 13:31:44 DEBUG SmbTreeConnection:577 - Referral failed, trying next
jcifs.smb.SmbException: Failed to connect: IELIOTT/192.168.0.102
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:669)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:214)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:561)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:133)
Caused by: jcifs.util.transport.TransportException: java.net.ConnectException: Connection refused (Connection refused)
	at jcifs.util.transport.Transport.run(Transport.java:759)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:490)
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:686)
	at jcifs.util.transport.Transport.run(Transport.java:732)
	... 1 more
2019-03-17 13:31:44 WARN  smbcli:138 - Caught a CIFSException on listFiles
jcifs.smb.SmbException: Failed to connect: IELIOTT/192.168.0.102
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:669)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:214)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:561)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at smbcli.main(smbcli.java:133)
Caused by: jcifs.util.transport.TransportException: java.net.ConnectException: Connection refused (Connection refused)
	at jcifs.util.transport.Transport.run(Transport.java:759)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:490)
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:686)
	at jcifs.util.transport.Transport.run(Transport.java:732)
	... 1 more
2019-03-17 13:31:44 DEBUG SmbTransportPoolImpl:277 - Closing pool
2019-03-17 13:31:44 DEBUG SmbTransportPoolImpl:277 - Closing pool
```
It is not really an issue since I can catch this exception and request proper login but I was wondering if this is the only way.

**Comment by mbechler** [comment]
Judging from the packet capture, the "Connection refused" is correct, i.e. there is no SMB server exposed. Therefor this seems unrelated to authentication.

**Comment by courville** [comment]
Indeed. The strange thing is that the discovery process shows that the share is present.
Issue closed.
