### ISSUE TITLE
jcifs-ng takes longer time to make connection to windows than jcifs

### ISSUE THREAD

**Issue by dingdonghk** [AgNO3/jcifs-ng#154]
I am migrating my code from jcifs to jcifs-ng-2.1.1 to copy file. The java program is executed in unix to copy file (10KB file) from windows server 2016 to NAS. 
In jcifs, copy file just within a second. However, in jcifs-ng, using Smbfile.copyTo function is very slow. 
Then I tried to break down to investigate and find that the connection is too slow. It takes about 5 seconds to make the connect. I tried to edit properties but in vain. 
Could anyone please advise?

````
Properties prop = new Properties();
prop.put( "jcifs.resolveOrder", "DNS" );
System.out.println(df.format(new Date()) + " baseContext....");
Configuration config = new PropertyConfiguration(prop);
CIFSContext baseContext = new BaseContext(config);
NtlmPasswordAuthenticator creds = new NtlmPasswordAuthenticator(ntDomain,ntUser,ntPwd);
testCtx = baseContext.withCredentials(creds);
testCtx.getCredentials();
System.out.println(df.format(new Date()) + " Copy....");

System.out.println(df.format(new Date()) + " Start SMB source");
f_source = new SmbFile(simDirSource + fileNameSource, testCtx );
System.out.println(df.format(new Date()) + " Connect");
f_source.connect();
System.out.println(df.format(new Date()) + " End Copy....");
````

below is the log:
````
2019-03-20 17:40:45.372 baseContext....
2019-03-20 17:40:46.671 Copy....
2019-03-20 17:40:46.672 Start SMB source
2019-03-20 17:40:46.721 Connect
2019-03-20 17:40:51.871 End copy....
````

What is the difference for the two libraries to make connection? 

Status update:
I tried another smb library and add security provider to the smb config. The connection issue solve. However, I can't find the related setting for jcifs-ng. I think it is the cause of the issue. Is there any workaround for using jcifs-ng for smb connection to windows 2016 server?

**Comment by mbechler** [comment]
A debug log or packet capture would be necessary to further look into this.
You could try setting _jcifs.smb.client.dfs.disabled=true_, my initial guess would be that this might be DFS related.

**Comment by dingdonghk** [comment]
I tried setting jcifs.smb.client.dfs.disabled=true, but no change.

I enabled the debug log. This part looks like exception but don't know what action I can take:
```
[main] DEBUG jcifs.smb.SmbTreeConnection - Acquired tree on switch SmbTree[share=SHARE_FOLDER,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
[main] DEBUG jcifs.smb.SmbFile - queryPath: \759.pdf
[main] DEBUG jcifs.internal.smb2.create.Smb2CreateRequest - Opening 759.pdf
[main] DEBUG jcifs.internal.smb2.create.Smb2CloseRequest - Closing FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (\759.pdf)
[Transport0] DEBUG jcifs.internal.smb2.create.Smb2CreateResponse - Opened 759.pdf: A90C00002A000000010000002A000000
[Transport0] DEBUG jcifs.smb.SmbTransportImpl - Compound next command 0 read size 128 remain 128
[Transport0] DEBUG jcifs.internal.smb2.create.Smb2CloseResponse - Closed FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (\759.pdf)
[main] DEBUG jcifs.smb.SmbFile - openUnshared: \759.pdf flags: 0 access: 1 attrs: 80 options: 0
[main] DEBUG jcifs.internal.smb2.create.Smb2CreateRequest - Opening 759.pdf
[Transport0] DEBUG jcifs.internal.smb2.create.Smb2CreateResponse - Opened 759.pdf: AA0C00002A000000050000002A000000
[main] DEBUG jcifs.smb.SmbFile - openUnshared: \759.pdf flags: 52 access: 102 attrs: 20 options: 0
[main] DEBUG jcifs.internal.smb2.create.Smb2CreateRequest - Opening 759.pdf
[Transport1] DEBUG jcifs.internal.smb2.create.Smb2CreateResponse - Opened 759.pdf: D4030000000000000100000000000000
[JCIFS-WriterThread] DEBUG jcifs.smb.SmbFileOutputStream - write: fid=FileHandle \759.pdf [fid=D4030000000000000100000000000000,tree=2,flags=52,access=102,attrs=0,options=0],off=0,len=4936
[main] DEBUG jcifs.smb.SmbTransportImpl - Error code: 0xC0000011 for Smb2ReadRequest
[main] DEBUG jcifs.smb.SmbTreeConnection - Not retrying
jcifs.smb.SmbException: 0xC0000011
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1441)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)
        at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)
        at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:261)
        at jcifs.smb.SmbCopyUtil.copyFile(SmbCopyUtil.java:138)
        at jcifs.smb.SmbFile.copyRecursive(SmbFile.java:1361)
        at jcifs.smb.SmbFile.copyTo(SmbFile.java:1412)
        at project1.jcifsng_tuning.fileCopy(jcifsng_tuning.java:152)
        at project1.jcifsng_tuning.main(jcifsng_tuning.java:69)
[main] DEBUG jcifs.smb.SmbFileInputStream - Reached end of file
jcifs.smb.SmbException: 0xC0000011
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1441)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)
        at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)
        at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:261)
        at jcifs.smb.SmbCopyUtil.copyFile(SmbCopyUtil.java:138)
        at jcifs.smb.SmbFile.copyRecursive(SmbFile.java:1361)
        at jcifs.smb.SmbFile.copyTo(SmbFile.java:1412)
        at project1.jcifsng_tuning.fileCopy(jcifsng_tuning.java:152)
        at project1.jcifsng_tuning.main(jcifsng_tuning.java:69)
[main] DEBUG jcifs.smb.SmbCopyUtil - Copied a total of 4936 bytes
[main] DEBUG jcifs.smb.SmbFileHandleImpl - Closing file handle FileHandle \759.pdf [fid=D4030000000000000100000000000000,tree=2,flags=52,access=102,attrs=0,options=0]
[main] DEBUG jcifs.internal.smb2.create.Smb2CloseRequest - Closing D4030000000000000100000000000000 ()
[Transport1] DEBUG jcifs.internal.smb2.create.Smb2CloseResponse - Closed D4030000000000000100000000000000 ()
[main] DEBUG jcifs.smb.SmbFileHandleImpl - Closing file handle FileHandle \759.pdf [fid=AA0C00002A000000050000002A000000,tree=1,flags=0,access=1,attrs=0,options=0]
[main] DEBUG jcifs.internal.smb2.create.Smb2CloseRequest - Closing AA0C00002A000000050000002A000000 ()
[Transport0] DEBUG jcifs.internal.smb2.create.Smb2CloseResponse - Closed AA0C00002A000000050000002A000000 ()
[main] DEBUG jcifs.smb.SmbTreeConnection - Tree connection no longer in use, release tree SmbTree[share=TARGET_SHARE,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
```

**Comment by mbechler** [comment]
That is very strange. Between the two log lines there really isn't happening anything interesting (IO, computation, locking...) but they are about 3 seconds apart. The actual message exchanges seem to appear just fine.

```
2019-04-01 17:07:35.164 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is <source_server>
2019-04-01 17:07:38.254 [main] DEBUG jcifs.smb.NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.30, 1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2, 1.2.840.113554.1.2.2.3, 1.3.6.1.4.1.311.2.2.10],mic=null]
```

The same should be true for
```
2019-04-01 17:07:38.395 [main] DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0
2019-04-01 17:07:42.894 [main] DEBUG jcifs.smb.NtlmContext - Sign key is 94B3FEECF5A70CB03ACCC6895DC47CF1
```

I don't think that a trace log or packet capture will help much there. Maybe you can try debugging or profiling the code to see where it is hanging.

**Comment by dingdonghk** [comment]
Not sure if it is related to the connection between windows and unix. I try to run the java in windows to copy file from another windows to NAS. The performance is ok. I would discuss with my supervisor for the next move.

**Comment by dingdonghk** [comment]
update: we have give up tracing as we still cannot find out the root cause. Not sure if it is related to SMB protocol.
Thanks for your help!
