### ISSUE TITLE
Can not connect SMB202(java.io.IOException: transport closed in negotiate)

### ISSUE THREAD

**Issue by Sentaroh** [AgNO3/jcifs-ng#156]
SMB202 just to make the session disconnected without Negotiate being completed. SMB202 wouldn't be able to use?

****Test code****
	Properties prop=new Properties();
	
	prop.setProperty("jcifs.smb.client.minVersion", "SMB202");
	prop.setProperty("jcifs.smb.client.maxVersion", "SMB202");

        BaseContext bc = new BaseContext(new PropertyConfiguration(prop));
        NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "","android","xx");
        CIFSContext ct = bc.withCredentials(creds);

        SmbFile in_file = new SmbFile("smb://192.168.200.40/share", ct);

        try {
       		String[] fl=in_file.list();
        } catch(SmbException e) {
        	System.out.println( e.getMessage()+", "+String.format("0x%08x", e.getNtStatus() ));
        	e.printStackTrace();
        }

****Log****
[Trace] jcifs.sm
[smb202.zip](https://github.com/AgNO3/jcifs-ng/files/3069994/smb202.zip)

b.DfsImpl Resolving \192.168.200.40\share 
[Trace] jcifs.smb.SmbTransportPoolImpl Exclusive false enforced signing false 
[Debug] jcifs.smb.SmbTransportPoolImpl New transport connection Transport0[0.0.0.0<00>/192.168.200.40:445,state=0,signingEnforced=false,usage=1] 
[Debug] jcifs.util.transport.Transport Connecting Transport0 
[Debug] jcifs.smb.SmbTransportImpl Connecting in state 1 addr 192.168.200.40 
[Trace] jcifs.smb.SmbTransportImpl SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=12691,uid=0,mid=0,wordCount=0,byteCount=22,wordCount=0,dialects=NT LM 0.12] 
[Trace] jcifs.smb.SmbTransportImpl FF534D4272000000001803C8000000000000000000000000FFFF93310000000000160002534D4220322E3F3F3F0002534D4220322E30303200 
[Trace] jcifs.smb.SmbTransportImpl Wrote negotiate request 
[Trace] jcifs.smb.SmbTransportImpl New data read: Transport0[0.0.0.0<00>/192.168.200.40:445,state=1,signingEnforced=false,usage=1] 
[Trace] jcifs.smb.SmbTransportImpl FE534D4240000000000000000000010001000000000000000000000000000000 
[Trace] jcifs.smb.SmbTransportImpl Read negotiate response 
[Trace] jcifs.smb.SmbTransportImpl command=SMB2_NEGOTIATE,status=0,flags=0x0000,mid=1,wordCount=0,byteCount=40 
[Trace] jcifs.smb.SmbTransportImpl FE534D4240000000000000000000000200000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000024000100010000000100000000000000000000000000000000000000000000000000000002020100 
[Trace] jcifs.smb.SmbTransportImpl Wrote negotiate request 
[Debug] jcifs.util.transport.Transport Interrupting transport thread 
[Debug] jcifs.util.transport.Transport Joining transport thread 
[Debug] jcifs.util.transport.Transport Joined transport thread 
[Debug] jcifs.smb.SmbTransportPoolImpl Removing transport connection Transport0[0.0.0.0<00>/192.168.200.40:445,state=4,signingEnforced=false,usage=1] (640070680) 
[Trace] jcifs.util.transport.Transport Release transport 0 Transport0[0.0.0.0<00>/192.168.200.40:445,state=4,signingEnforced=false,usage=0] 
[Trace] jcifs.util.transport.Transport Transport usage dropped to zero Transport0[0.0.0.0<00>/192.168.200.40:445,state=4,signingEnforced=false,usage=0] 
[Debug] jcifs.smb.SmbTreeConnection Referral failed, trying next 
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/192.168.200.40
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:669)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:214)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:1)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:561)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:243)
	at jcifs.smb.SmbFile.list(SmbFile.java:1141)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:38)
Caused by: jcifs.util.transport.TransportException: java.io.IOException: transport closed in negotiate
	at jcifs.util.transport.Transport.run(Transport.java:759)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: transport closed in negotiate
	at jcifs.smb.SmbTransportImpl.negotiatePeek(SmbTransportImpl.java:584)
	at jcifs.smb.SmbTransportImpl.negotiate2(SmbTransportImpl.java:627)
	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:532)
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:686)
	at jcifs.util.transport.Transport.run(Transport.java:732)
	... 1 more

Failed to connect: 0.0.0.0<00>/192.168.200.40, 0xc0000001
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/192.168.200.40
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:669)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:214)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:1)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:561)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:243)
	at jcifs.smb.SmbFile.list(SmbFile.java:1141)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:38)
Caused by: jcifs.util.transport.TransportException: java.io.IOException: transport closed in negotiate
	at jcifs.util.transport.Transport.run(Transport.java:759)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: transport closed in negotiate
	at jcifs.smb.SmbTransportImpl.negotiatePeek(SmbTransportImpl.java:584)
	at jcifs.smb.SmbTransportImpl.negotiate2(SmbTransportImpl.java:627)
	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:532)
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:686)
	at jcifs.util.transport.Transport.run(Transport.java:732)
	... 1 more
[Debug] jcifs.smb.SmbTransportPoolImpl Closing pool

**Comment by Sentaroh** [comment]
Additional Information
****Excerpt from SAMBA Config***
[global]
*
max protocol = SMB2_02
min protocol = SMB2_02
*

**Comment by mbechler** [comment]
The negotation shown looks completely fine, the only thing I notice is the all-0s client GUID, which should not be used in recent versions. Which version are you using?

**Comment by Sentaroh** [comment]
Downloaded from Master branch 3 days ago.

**Comment by mbechler** [comment]
Ah right, clientGuid is for SMB2.1+ and must be 0 for 2.02, so that should be fine, too.   
So the negotiation looks completely fine to me, can you try to get some debugging information from the server, maybe that way we can find out what is happening.

**Comment by Sentaroh** [comment]
There is an error message on the Samba side.
[SMB202_20190413.zip](https://github.com/AgNO3/jcifs-ng/files/3076350/SMB202_20190413.zip)
[2019/04/13 23:49:44.193732, 10, pid=2756, effective(0, 0), real(0, 0)] ../source3/smbd/smb2_server.c:2018(smbd_smb2_request_dispatch)
  smbd_smb2_request_dispatch: opcode[SMB2_OP_NEGPROT] mid = 1
[2019/04/13 23:49:44.193747, 10, pid=2756, effective(0, 0), real(0, 0)] ../source3/smbd/smb2_server.c:1061(smbd_server_connection_terminate_ex)
  smbd_server_connection_terminate_ex: reason[NT_STATUS_INVALID_PARAMETER] at ../source3/smbd/smb2_server.c:3591

**Comment by mbechler** [comment]
Thanks. The exact samba version would be very helpful to track down the source location.

**Comment by Sentaroh** [comment]
Samba version is: 4.3.11-Ubuntu.

**Comment by mbechler** [comment]
I think I found it, while doing multi protocol negotiation if the server does only support a single protocol version no further negotiation is required and the spec mandates that it does not continue which samba enforces (I don't think windows does). I will look into a patch (likely next weekend). If needed, you might be able to work around that by directly using smb2 negotiation (jcifs.smb.client.useSMB2Negotiation=true).

**Comment by mbechler** [comment]
Quick follow up, for future reference: vista and server 2008 (non r2) could be affected as well, these are 2.02 only and I have a test environment for neither.

**Comment by mbechler** [comment]
Should be fixed now, please give it a try.

**Comment by Sentaroh** [comment]
In Samba 4.3.11 Transport is disconnected Transport4, 0xc0000001 occurs (jcifs.smb.client.useSMB2Negotiation=true to prevent errors from occurring), and Samba 4.7.6 is successful.
I think it's a problem with samba, so I solved the problem. Thank you for your immediate response.
