### ISSUE TITLE
Can jcifs-ng log in without a password?

### ISSUE THREAD

**Issue by Sentaroh** [AgNO3/jcifs-ng#158]
When I try to log in with only the account name jcifs.smb.SmbAuthException: Logon failure: Unknown user name or bad password.
Is an account name and password required to log in?

testuser configured with SMBPASSWD with no password

Samba version : 4.7.6-Ubuntu

jcifs-ng version : Download from master branch(after commit #157) 

[without_password_log.zip](https://github.com/AgNO3/jcifs-ng/files/3100992/without_password_log.zip)

Test code:
        BaseContext bc = new BaseContext(new PropertyConfiguration(prop));
        NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "","testuser",null);
        CIFSContext ct = bc.withCredentials(creds);
        SmbFile in_file = new SmbFile("smb://192.168.200.115/share/", ct);//Samba1
        try {
        	SmbFile[] fl=in_file.listFiles();
        	for(SmbFile fn:fl) System.out.println("name="+fn.getName());
        } catch(SmbException e) {
        	System.out.println( e.getMessage()+", "+String.format("0x%08x", e.getNtStatus() ));
        	e.printStackTrace();
        }

Log:
[Trace] jcifs.smb.DfsImpl Resolving \192.168.200.115\share 
[Trace] jcifs.smb.SmbTransportPoolImpl Exclusive false enforced signing false 
[Debug] jcifs.smb.SmbTransportPoolImpl New transport connection Transport0[0.0.0.0<00>/192.168.200.115:445,state=0,signingEnforced=false,usage=1] 
[Debug] jcifs.util.transport.Transport Connecting Transport0 
[Debug] jcifs.smb.SmbTransportImpl Connecting in state 1 addr 192.168.200.115 
[Trace] jcifs.smb.SmbTransportImpl SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=64399,uid=0,mid=0,wordCount=0,byteCount=34,wordCount=0,dialects=NT LM 0.12] 
[Trace] jcifs.smb.SmbTransportImpl FF534D4272000000001803C8000000000000000000000000FFFF8FFB00000000002200024E54204C4D20302E31320002534D4220322E3F3F3F0002534D4220322E30303200 
[Trace] jcifs.smb.SmbTransportImpl Wrote negotiate request 
[Trace] jcifs.smb.SmbTransportImpl New data read: Transport0[0.0.0.0<00>/192.168.200.115:445,state=1,signingEnforced=false,usage=1] 
[Trace] jcifs.smb.SmbTransportImpl FE534D4240000000000000000000010001000000000000000000000000000000 
[Trace] jcifs.smb.SmbTransportImpl Read negotiate response 
[Trace] jcifs.smb.SmbTransportImpl command=SMB2_NEGOTIATE,status=0,flags=0x0000,mid=1,wordCount=0,byteCount=40 
[Trace] jcifs.smb.SmbTransportImpl FE534D424000000000000000000000020000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000002400020001000000010000001246EDF28C3C04A0661DC967AD28A6E9000000000000000002021002 
[Trace] jcifs.smb.SmbTransportImpl Wrote negotiate request 
[Trace] jcifs.smb.SmbTransportImpl New data read: Transport0[0.0.0.0<00>/192.168.200.115:445,state=1,signingEnforced=false,usage=1] 
[Trace] jcifs.smb.SmbTransportImpl FE534D4240000000000000000000010001000000000000000100000000000000 
[Trace] jcifs.smb.SmbTransportImpl Read negotiate response 
[Trace] jcifs.smb.SmbTransportImpl Smb2NegotiateResponse[command=SMB2_NEGOTIATE,status=0,flags=0x0001,mid=1,wordCount=0,byteCount=0,dialectRevision=528,securityMode=0x1,capabilities=0x00000007,serverTime=Sun Apr 21 15:59:57 JST 2019 
[Trace] jcifs.smb.SmbTransportImpl  
[Debug] jcifs.smb.SmbTransportImpl Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@6325e37e 
[Debug] jcifs.smb.SmbTransportImpl Signature negotiation enforced false (server false) enabled false (server true) 
[Trace] jcifs.util.transport.Transport Acquire transport 2 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=2] 
[Trace] jcifs.util.transport.Transport Release transport 1 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=1] 
[Trace] jcifs.smb.SmbTransportImpl Currently 0 session(s) active for Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=1] 
[Trace] jcifs.util.transport.Transport Acquire transport 2 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=2] 
[Debug] jcifs.smb.SmbTransportImpl Establishing new session SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0 
[Trace] jcifs.smb.SmbSessionImpl Acquire session 2 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=2] 
[Trace] jcifs.smb.SmbTreeImpl Acquire tree 1 SmbTree[share=SHARE,service=?????,tid=-1,inDfs=false,inDomainDfs=false,connectionState=0,usage=1] 
[Trace] jcifs.smb.SmbTreeConnection doConnect: 192.168.200.115 
[Trace] jcifs.smb.SmbSessionImpl Acquire session 3 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=3] 
[Trace] jcifs.util.transport.Transport Acquire transport 3 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=3] 
[Debug] jcifs.smb.SmbTreeImpl treeConnect: unc=\\192.168.200.115\SHARE,service=????? 
[Trace] jcifs.util.transport.Transport Acquire transport 4 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=4] 
[Trace] jcifs.util.transport.Transport Acquire transport 5 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=5] 
[Debug] jcifs.smb.SmbSessionImpl sessionSetup: testuser 
[Debug] jcifs.smb.SmbSessionImpl Remote host is 192.168.200.115 
[Debug] jcifs.smb.NtlmPasswordAuthenticator Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.10],mic=null] 
[Trace] jcifs.smb.NtlmContext Type1Message[suppliedDomain=,suppliedWorkstation=null,flags=0x62088215] 
[Trace] jcifs.smb.NtlmContext 4E544C4D53535000010000001582086200000000280000000000000028000000060100000000000F 
[Trace] jcifs.smb.SmbTransportImpl Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 
[Trace] jcifs.smb.SmbTransportImpl jcifs.internal.smb2.session.Smb2SessionSetupRequest costs 1 avail 1 (Transport0) 
[Trace] jcifs.smb.SmbTransportImpl Request credits 512 
[Trace] jcifs.smb.SmbTransportImpl Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 
[Trace] jcifs.smb.SmbTransportImpl command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=2,wordCount=0,byteCount=98 
[Trace] jcifs.smb.SmbTransportImpl FE534D4240000000000000000100000200000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000019000001010000000000000058004A000000000000000000604806062B0601050502A03E303CA00E300C060A2B06010401823702020AA22A04284E544C4D53535000010000001582086200000000280000000000000028000000060100000000000F000000000000 
[Trace] jcifs.smb.SmbTransportImpl New data read: Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=5] 
[Trace] jcifs.smb.SmbTransportImpl FE534D4240000000160000C00100010001000000000000000200000000000000 
[Debug] jcifs.smb.SmbTransportImpl Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0 
[Trace] jcifs.smb.SmbTransportImpl Adding credits 1 
[Trace] jcifs.smb.SmbTransportImpl Response is command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0 
[Trace] jcifs.smb.NtlmContext Type2Message[target=SEN-SAMBA2,challenge=<8 bytes>,context=null,targetInformation=<94 bytes>,flags=0x628A8215] 
[Trace] jcifs.smb.NtlmContext 4E544C4D5353500002000000140014003800000015828A62976EE375A01347DF00000000000000005E005E004C000000060100000000000F530045004E002D00530041004D0042004100320002001400530045004E002D00530041004D0042004100320001001400530045004E002D00530041004D0042004100320004000200000003001400730065006E002D00730061006D006200610032000700080048A1A4D40FF8D40100000000 
[Trace] jcifs.smb.NtlmContext Type3Message[domain=,user=testuser,workstation=null,lmResponse=null,ntResponse=null,sessionKey=null,flags=0x62088215] 
[Trace] jcifs.smb.NtlmContext 4E544C4D5353500002000000140014003800000015828A62976EE375A01347DF00000000000000005E005E004C000000060100000000000F530045004E002D00530041004D0042004100320002001400530045004E002D00530041004D0042004100320001001400530045004E002D00530041004D0042004100320004000200000003001400730065006E002D00730061006D006200610032000700080048A1A4D40FF8D40100000000 
[Trace] jcifs.smb.SmbTransportImpl Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 
[Trace] jcifs.smb.SmbTransportImpl jcifs.internal.smb2.session.Smb2SessionSetupRequest costs 1 avail 1 (Transport0) 
[Trace] jcifs.smb.SmbTransportImpl Request credits 512 
[Trace] jcifs.smb.SmbTransportImpl Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 
[Trace] jcifs.smb.SmbTransportImpl command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=3,wordCount=0,byteCount=120 
[Trace] jcifs.smb.SmbTransportImpl FE534D42400000000000000001000002000000000000000003000000000000000000000000000000B18816A40000000000000000000000000000000000000000190000010100000000000000580060000000000000000000A15E305CA25A04584E544C4D535350000300000000000000480000000000000048000000000000004800000010001000480000000000000058000000000000005800000015820862060100000000000F74006500730074007500730065007200 
[Trace] jcifs.smb.SmbTransportImpl New data read: Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=5] 
[Trace] jcifs.smb.SmbTransportImpl FE534D42400000006D0000C00100010001000000000000000300000000000000 
[Trace] jcifs.smb.SmbTransportImpl Adding credits 1 
[Debug] jcifs.smb.SmbSessionImpl Session setup failed 
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1426)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:604)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:610)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:284)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:43)

[Trace] jcifs.util.transport.Transport Acquire transport 6 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=6] 
[Trace] jcifs.util.transport.Transport Release transport 5 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=5] 
[Trace] jcifs.util.transport.Transport Release transport 4 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=4] 
[Trace] jcifs.util.transport.Transport Release transport 3 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=3] 
[Debug] jcifs.smb.SmbTreeImpl Disconnect tree on treeConnectFailure 
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1426)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:604)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:610)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:284)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:43)

[Trace] jcifs.smb.SmbSessionImpl Acquire session 4 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=4] 
[Trace] jcifs.util.transport.Transport Acquire transport 4 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=4] 
[Trace] jcifs.util.transport.Transport Release transport 3 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=3] 
[Trace] jcifs.smb.SmbSessionImpl Release session 3 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=3] 
[Trace] jcifs.util.transport.Transport Release transport 2 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=2] 
[Trace] jcifs.smb.SmbSessionImpl Release session 2 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=2] 
[Debug] jcifs.smb.SmbTreeConnection Authentication failed 
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1426)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:604)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:610)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:284)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:43)

[Trace] jcifs.smb.SmbSessionImpl Acquire session 3 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=3] 
[Trace] jcifs.smb.SmbTreeImpl Release tree 0 SmbTree[share=SHARE,service=?????,tid=-1,inDfs=false,inDomainDfs=false,connectionState=0,usage=0] 
[Debug] jcifs.smb.SmbTreeImpl Usage dropped to zero, release session 
[Trace] jcifs.smb.SmbSessionImpl Release session 2 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=2] 
[Trace] jcifs.smb.SmbSessionImpl Release session 1 SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=1] 
[Trace] jcifs.util.transport.Transport Release transport 1 Transport0[0.0.0.0<00>/192.168.200.115:445,state=3,signingEnforced=false,usage=1] 
[Debug] jcifs.smb.SmbTreeConnection Referral failed, trying next 
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1426)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:604)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:610)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:284)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:43)

Logon failure: unknown user name or bad password., 0xc000006d
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1426)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:604)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:610)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:564)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:485)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:461)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:422)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:284)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:43)
[Debug] jcifs.smb.SmbTransportPoolImpl Closing pool 
[Warn ] jcifs.smb.SmbTransportImpl Disconnecting transport while still in use Transport0[0.0.0.0<00>/192.168.200.115:445,state=5,signingEnforced=false,usage=1]: [SmbSession[credentials=testuser,targetHost=192.168.200.115,targetDomain=null,uid=0,connectionState=0,usage=1]] 
[Debug] jcifs.smb.SmbTransportImpl Disconnecting transport Transport0[0.0.0.0<00>/192.168.200.115:445,state=5,signingEnforced=false,usage=1] 
[Trace] jcifs.smb.SmbTransportImpl Currently 1 session(s) active for Transport0[0.0.0.0<00>/192.168.200.115:445,state=5,signingEnforced=false,usage=1] 
[Trace] jcifs.util.transport.Transport Acquire transport 2 Transport0[0.0.0.0<00>/192.168.200.115:445,state=5,signingEnforced=false,usage=2] 
[Trace] jcifs.util.transport.Transport Release transport 1 Transport0[0.0.0.0<00>/192.168.200.115:445,state=5,signingEnforced=false,usage=1] 
[Trace] jcifs.smb.SmbTransportImpl Socket closed 
[Debug] jcifs.smb.SmbTransportPoolImpl Removing transport connection Transport0[0.0.0.0<00>/192.168.200.115:445,state=5,signingEnforced=false,usage=1] (1705686673)

**Comment by mbechler** [comment]
Emtpy password had been used to indicate anonymous authentication in the NTLM code. I think I found a way to change that without breaking stuff, however I wasn't able to convince my samba server to allow me to login (even with smbclient), so I could not test whether this works now. Please try.

**Comment by Sentaroh** [comment]
I was able to log in without any problems as a result of testing with the modified version. 
Thank you for your support.
