### ISSUE TITLE
Enumeration failed jcifs.smb.SmbException: The handle is invalid when SmbFile.listfiles with folder has more than 197 files.

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#16]
We are running jcifs-ng from Windows 7 to Windows 2008 server R2.  We got the below exception with error 'Enumeration failed'.  We tried to narrow it down to the case when listing files of a folder has more than 197 files.

The problem happens with both case jcifs.smb.client.enableSMB2=true and jcifs.smb.client.enableSMB2=false

The stack trace from calling SmbEnumerationUtil.listFiles() is:

2017-11-25 23:33:55 DEBUG SmbTransportImpl:? - Error code: 0xC0000008 for Trans2FindNext2
2017-11-25 23:33:55 DEBUG SmbTreeConnection:? - Not retrying
jcifs.smb.SmbException: The handle is invalid.
        at jcifs.smb.SmbTransportImpl.checkStatus(Unknown Source)
        at jcifs.smb.SmbTransportImpl.sendComTransaction(Unknown Source)
        at jcifs.smb.SmbTransportImpl.send(Unknown Source)
        at jcifs.smb.SmbSessionImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send0(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIterator1.fetchMore(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.advance(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.advance(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.SmbEnumerationUtil.listFiles(Unknown Source)
        at jcifs.smb.SmbFile.listFiles(Unknown Source)
        at TestJCIFS_readdir.main(TestJCIFS_readdir.java:29)
2017-11-25 23:33:55 WARN  DirFileEntryEnumIteratorBase:? - Enumeration failed
jcifs.smb.SmbException: The handle is invalid.
        at jcifs.smb.SmbTransportImpl.checkStatus(Unknown Source)
        at jcifs.smb.SmbTransportImpl.sendComTransaction(Unknown Source)
        at jcifs.smb.SmbTransportImpl.send(Unknown Source)
        at jcifs.smb.SmbSessionImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send0(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIterator1.fetchMore(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.advance(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.advance(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.SmbEnumerationUtil.listFiles(Unknown Source)
        at jcifs.smb.SmbFile.listFiles(Unknown Source)
        at TestJCIFS_readdir.main(TestJCIFS_readdir.java:29)
folder gstorey_000.pst/ **count:198**
2017-11-25 23:33:55 DEBUG SmbTransportPoolImpl:? - Closing pool
2017-11-25 23:33:55 DEBUG SmbTransportPoolImpl:? - Closing pool

We collected two tracedumps:
jcifs-ng_197files.cab where there is NO problem
jcifs-ng_198files.cab where the problem happens.

Any ideas or suggestions would be greatly appreciated. 

Thanks,

[jcifs-ng_198files-problem.zip](https://github.com/AgNO3/jcifs-ng/files/1503667/jcifs-ng_198files-problem.zip)

**Comment by mbechler** [comment]
Reproduced and fixed the issue for SMB1. Are you sure about SMB2?

**Comment by thanh-vn** [comment]
Ran some more testing for jcifs.smb.client.enableSMB2=true and confirmed that there is **NO** 198files problem for **SMB2**.   However, there is different exception 'DirFileEntryEnumIterator2:? - End of listing
jcifs.smb.SmbException: 0x80000006'.  This exception happens with folder having less than 198 files also.

Stack trace is below:

2017-11-26 08:49:09 DEBUG Smb2CreateRequest:? - Opening richard_shapiro_001.pst\

2017-11-26 08:49:10 DEBUG Smb2CreateResponse:? - Opened richard_shapiro_001.pst\: 012C03002002000005000000FFFFFFFF
2017-11-26 08:49:10 DEBUG SmbTransportImpl:? - Compound next command 0 read size 65400 remain 65400
2017-11-26 08:49:10 DEBUG SmbTransportImpl:? - Error code: 0x80000006 for Smb2QueryDirectoryRequest
2017-11-26 08:49:10 DEBUG SmbTreeConnection:? - Not retrying
jcifs.smb.SmbException: 0x80000006
        at jcifs.smb.SmbTransportImpl.checkStatus2(Unknown Source)
        at jcifs.smb.SmbTransportImpl.checkStatus(Unknown Source)
        at jcifs.smb.SmbTransportImpl.sendrecv(Unknown Source)
        at jcifs.smb.SmbTransportImpl.send(Unknown Source)
        at jcifs.smb.SmbSessionImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send0(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIterator2.fetchMore(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.advance(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.advance(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.SmbEnumerationUtil.listFiles(Unknown Source)
        at jcifs.smb.SmbFile.listFiles(Unknown Source)
        at TestJCIFS_readdir.main(TestJCIFS_readdir.java:38)
2017-11-26 08:49:10 DEBUG DirFileEntryEnumIterator2:? - End of listing
jcifs.smb.SmbException: 0x80000006
        at jcifs.smb.SmbTransportImpl.checkStatus2(Unknown Source)
        at jcifs.smb.SmbTransportImpl.checkStatus(Unknown Source)
        at jcifs.smb.SmbTransportImpl.sendrecv(Unknown Source)
        at jcifs.smb.SmbTransportImpl.send(Unknown Source)
        at jcifs.smb.SmbSessionImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send0(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeConnection.send(Unknown Source)
        at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source)
        at jcifs.smb.SmbTreeHandleImpl.send(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIterator2.fetchMore(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.advance(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.DirFileEntryEnumIteratorBase.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.advance(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.FileEntryAdapterIterator.next(Unknown Source)
        at jcifs.smb.SmbEnumerationUtil.listFiles(Unknown Source)
        at jcifs.smb.SmbFile.listFiles(Unknown Source)
        at TestJCIFS_readdir.main(TestJCIFS_readdir.java:38)
2017-11-26 08:49:10 DEBUG Smb2CloseRequest:? - Closing 012C03002002000005000000FFFFFFFF ()
2017-11-26 08:49:11 INFO  Smb2CloseResponse:? - Closed 012C03002002000005000000FFFFFFFF ()
2017-11-26 08:49:11 DEBUG SmbTreeConnection:? - Tree connection no longer in use, release tree SmbTree[share=D10348-PALLEN,service=null,tid=1,inDfs=false,inDoma
inDfs=false,connectionState=2,usage=2]
2017-11-26 08:49:11 DEBUG SmbTreeImpl:? - Usage dropped to zero, release session
2017-11-26 08:49:11 DEBUG SmbSessionImpl:? - Usage dropped to zero, release connection Transport0[0.0.0.0<00>/9.30.60.40:445,state=3,signingEnforced=false,usage=1]
folder richard_shapiro_001.pst/ count:654


tracedump is collected:

[197listFiles_exception-SMB2.zip](https://github.com/AgNO3/jcifs-ng/files/1503986/197listFiles_exception-SMB2.zip)

**Comment by mbechler** [comment]
And is there an actual problem? The error you are seeing there is just the server's indication that there are no more files to list and seems to be handled just fine (-> End of listing).

**Comment by thanh-vn** [comment]
Thanks, 
Confirmed that there is no actual problem with the 'End of listing' exceptions after our test program skipping it.  So there is no problem when jcifs.smb.client.enableSMB2=true.

**Comment by thanh-vn** [comment]
Thank you for the quick fix!  We are able to do the listFiles() where folders contain more than 197 files on Windows with SMB1 now.
