### ISSUE TITLE
Enumerating all servers fail with SmbUnsupportedOperationException

### ISSUE THREAD

**Issue by mvysny** [AgNO3/jcifs-ng#160]
Hi, I'm using `eu.agno3.jcifs:jcifs-ng:2.1.2` - good work and thanks for taking over of the maintenance!

When I run new `SmbFile("smb://").listFiles()`, it fails with:
```
    jcifs.smb.SmbUnsupportedOperationException: Operation is not supported with the negotiated capabilities
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:207)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
```

**Comment by mvysny** [comment]
According to https://github.com/AgNO3/jcifs-ng/issues/22 this is not supported for SMB2; a fallback according to https://github.com/AgNO3/jcifs-ng/issues/20 seems to force the SMB1 protocol. Let me try that.

**Comment by mvysny** [comment]
That failed with
```
    java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
        at jcifs.util.Hexdump.toHexString(Hexdump.java:74)
        at jcifs.smb.NtlmContext.toString(NtlmContext.java:147)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at jcifs.smb.SpnegoContext.toString(SpnegoContext.java:486)
        at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:960)
        at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:486)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
        at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
        at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:205)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1192)
```

**Comment by mbechler** [comment]
The exception (in the trace output formatting) should be fixed in master. I would strongly recommend looking into alternative discovery methods if that feature is desired, as that really seems to be going away.

**Comment by mvysny** [comment]
Thank you very much for your quick reply and for the active maintenance! Just tried master and the enumeration works (when SMB1 is enforced via the `jcifs.smb.client.maxVersion` property). I know I shouldn't use that method, but I fail to find a simple example which shows the correct way! :-)

Anyway, I can now close this bug as working.
