### ISSUE TITLE
Can not read the share name with IPV6 address?

### ISSUE THREAD

**Issue by Sentaroh** [AgNO3/jcifs-ng#165]
IPV4 addresses can read share names, but IPV6 addresses have a bad endpoint exception when reading share names.

Test code:
	prop.setProperty("jcifs.smb.client.minVersion", "SMB1");
	prop.setProperty("jcifs.smb.client.maxVersion", "SMB300");
	BaseContext bc = new BaseContext(new PropertyConfiguration(prop));
	NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "","android","pswd");
	CIFSContext ct = bc.withCredentials(creds);
	SmbFile smb_file = new SmbFile("smb://[2001:c90:8221:a019:abd:43ff:fef6:482a]/", ct);
	String[] files=smb_file.list();
	for(String item:files) System.out.println( item );

StackTrace:
jcifs.dcerpc.DcerpcException: Bad endpoint: \\PIPE\
	at jcifs.dcerpc.DcerpcBinding.setOption(DcerpcBinding.java:150)
	at jcifs.dcerpc.DcerpcHandle.parseBinding(DcerpcHandle.java:99)
	at jcifs.dcerpc.DcerpcPipeHandle.<init>(DcerpcPipeHandle.java:54)
	at jcifs.dcerpc.DcerpcHandle.getHandle(DcerpcHandle.java:207)
	at jcifs.dcerpc.DcerpcHandle.getHandle(DcerpcHandle.java:190)
	at jcifs.smb.SmbEnumerationUtil.getHandle(SmbEnumerationUtil.java:69)
	at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:86)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:218)
	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:243)
	at jcifs.smb.SmbFile.list(SmbFile.java:1141)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:41)

Exception in thread "main" jcifs.smb.SmbException: smb://[2001:c90:8221:a019:abd:43ff:fef6:482a]/
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:171)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:218)
	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:243)
	at jcifs.smb.SmbFile.list(SmbFile.java:1141)
	at com.sentaroh.test.TestJcifsFile.main(TestJcifsFile.java:41)
Caused by: jcifs.dcerpc.DcerpcException: Bad endpoint: \\PIPE\
	at jcifs.dcerpc.DcerpcBinding.setOption(DcerpcBinding.java:150)
	at jcifs.dcerpc.DcerpcHandle.parseBinding(DcerpcHandle.java:99)
	at jcifs.dcerpc.DcerpcPipeHandle.<init>(DcerpcPipeHandle.java:54)
	at jcifs.dcerpc.DcerpcHandle.getHandle(DcerpcHandle.java:207)
	at jcifs.dcerpc.DcerpcHandle.getHandle(DcerpcHandle.java:190)
	at jcifs.smb.SmbEnumerationUtil.getHandle(SmbEnumerationUtil.java:69)
	at jcifs.smb.SmbEnumerationUtil.doMsrpcShareEnum(SmbEnumerationUtil.java:86)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)
	... 4 more

[log_and_trace.zip](https://github.com/AgNO3/jcifs-ng/files/3200007/log_and_trace.zip)

**Comment by Sentaroh** [comment]
jcifs-ng was downloaded today from the master.

**Comment by Sentaroh** [comment]
I was able to list it without a problem. Thank you very much.
