### ISSUE TITLE
jcifs.smb.SmbException: 0xC0000011  DEBUG jcifs.smb.SmbFileInputStream - Reached end of file

### ISSUE THREAD

**Issue by col-panic** [AgNO3/jcifs-ng#168]
This is mentioned in #112 already, and does not seem to be a problem. 

I find it rather confusing to log an exception if it is not a problem. In NtStatus there does not exist an entry for 0xC0000011, and if it really is not a problem I propose to not log this.

**Comment by col-panic** [comment]
Some more info

```
019-05-28 09:04:30,249 DEBUG jcifs.smb.SmbTransportImpl - Error code: 0xC0000011 for Smb2ReadRequest
2019-05-28 09:04:30,262 DEBUG jcifs.smb.SmbTreeConnection - Not retrying
jcifs.smb.SmbException: 0xC0000011
    at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1441) ~[na:na]
    at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552) ~[na:na]
    at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007) ~[na:na]
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523) ~[na:na]
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409) ~[na:na]
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472) ~[na:na]
    at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399) ~[na:na]
    at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314) ~[na:na]
    at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294) ~[na:na]
    at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130) ~[na:na]
    at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117) ~[na:na]
    at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331) ~[na:na]
    at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274) ~[na:na]
    at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:261) ~[na:na]
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146) ~[na:na]
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102) ~[na:na]
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123) ~[na:na]
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078) ~[na:na]
    at ch.elexis.core.services.internal.VirtualFilesystemHandle.readAllBytes(VirtualFilesystemHandle.java:61) ~[na:na]
    at ch.elexis.hl7.HL7ReaderFactory.getFileInputStream(HL7ReaderFactory.java:105) ~[na:na]
    at ch.elexis.hl7.HL7ReaderFactory.load(HL7ReaderFactory.java:75) ~[na:na]
    at ch.elexis.hl7.HL7ReaderFactory.getReader(HL7ReaderFactory.java:54) ~[na:na]
    at ch.elexis.core.importer.div.importers.HL7Parser.importFile(HL7Parser.java:417) ~[na:na]
    at ch.elexis.core.importer.div.importers.HL7Parser.importFile(HL7Parser.java:397) ~[na:na]
    at ch.elexis.core.importer.div.importers.multifile.strategy.DefaultHL7ImportStrategy.execute(DefaultHL7ImportStrategy.java:57) ~[na:na]
    at ch.elexis.core.importer.div.importers.multifile.MultiFileParser.importFromHandle(MultiFileParser.java:108) ~[na:na]
    at ch.elexis.core.importer.div.tasks.internal.HL7ImporterIIdentifiedRunnable.run(HL7ImporterIIdentifiedRunnable.java:112) ~[na:na]
    at ch.elexis.core.tasks.internal.service.Task.run(Task.java:178) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2019-05-28 09:04:30,268 DEBUG jcifs.smb.SmbFileInputStream - Reached end of file
jcifs.smb.SmbException: 0xC0000011
    at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1441) ~[na:na]
    at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1552) ~[na:na]
    at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007) ~[na:na]
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523) ~[na:na]
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409) ~[na:na]
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472) ~[na:na]
    at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399) ~[na:na]
    at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314) ~[na:na]
    at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294) ~[na:na]
    at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130) ~[na:na]
    at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117) ~[na:na]
    at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331) ~[na:na]
    at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274) ~[na:na]
    at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:261) ~[na:na]
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146) ~[na:na]
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102) ~[na:na]
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123) ~[na:na]
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078) ~[na:na]
    at ch.elexis.core.services.internal.VirtualFilesystemHandle.readAllBytes(VirtualFilesystemHandle.java:61) ~[na:na]
    at ch.elexis.hl7.HL7ReaderFactory.getFileInputStream(HL7ReaderFactory.java:105) ~[na:na]
    at ch.elexis.hl7.HL7ReaderFactory.load(HL7ReaderFactory.java:75) ~[na:na]
    at ch.elexis.hl7.HL7ReaderFactory.getReader(HL7ReaderFactory.java:54) ~[na:na]
    at ch.elexis.core.importer.div.importers.HL7Parser.importFile(HL7Parser.java:417) ~[na:na]
    at ch.elexis.core.importer.div.importers.HL7Parser.importFile(HL7Parser.java:397) ~[na:na]
    at ch.elexis.core.importer.div.importers.multifile.strategy.DefaultHL7ImportStrategy.execute(DefaultHL7ImportStrategy.java:57) ~[na:na]
    at ch.elexis.core.importer.div.importers.multifile.MultiFileParser.importFromHandle(MultiFileParser.java:108) ~[na:na]
    at ch.elexis.core.importer.div.tasks.internal.HL7ImporterIIdentifiedRunnable.run(HL7ImporterIIdentifiedRunnable.java:112) ~[na:na]
    at ch.elexis.core.tasks.internal.service.Task.run(Task.java:178) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by mbechler** [comment]
What is you suggestion? By NtStatus definiton this is an error code (0xC..) and therefore handled as such. I don't think adding such logic to the debug output is a good idea.
I guess we can add the status code to NtStatus, so that it's more obvious what it means.

**Comment by col-panic** [comment]
I guess you're right - and you only see it if debug mode is enabled. So for my scenario changing the log level from debug to info made my confusion go away :) Adding the status code is definitely good, making it more obvious - as you say!
