### ISSUE TITLE
Attempting to retrieve shared folder list with jcifs-ng over SMB 2.0 connection to Data ONTAP 8 results in an error.

### ISSUE THREAD

**Issue by yukiato** [AgNO3/jcifs-ng#170]
An error occurs when trying to get a list of shared folders with jcifs-ng on a netapp product Data ONTAP 8 via SMB 2.0 connection.
There was no problem at the time of SMB 1.0 connection.
The application created by the vendor uses jcifs-ng. Do you need any special settings?

**Comment by mbechler** [comment]
Further configuration should not be required. Which version is the application using?
How does it more specifically fail (packet trace + debug log is always the most helpful)? 

There is a problem regarding negotiation which is patched in master (which might have been related). Can you either try the master branch or set _jcifs.smb.client.useSMB2Negotiation=true_ to check whether it might be just that?

**Comment by yukiato** [comment]
Sorry for lack of explanation. I am using jcifs 2.1.2.

The user environment has been disabled by SMB 1.0 due to security.
The test program can access the shared folder without any problem with Windows Server.
The netapp product Data ONTAP 8 fails.


Test program debug log.

asspath test Joits.jar; libs/* TestJcits
Please input file server ip [ex. xxx.xxx.xxx.xxx]: HostName
Please input Domain [ex. mycluster.com]: DomainName
Please input Account (ex. administrator]: UserName
Please input Password: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) Togger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further des.
Connect to server [HostName] success !!
Exception in thread "main" java.lang. ArrayIndexOut Of BoundsException
        at java.lang. System.arraycopy (Native Method)
        at jcifs.dcerpc.DcerpcHandle.receiveMoreFragments(DcerpcHandle.java:
        at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:254)
        at jcifs.smb.SmbEnumerationUtil.domsrpcShareEnum(SmbEnumerationUtil.:92)
        at jcifs.smb.SmbEnumerationUtil.doShareEnun(SmbEnumerationUtil.java:
        at jcifs.smb.SmbEnumerationUtil.doEnum (SmbEnumerationUtil.java:222)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:28)
        at jcifs.smb.SmbFile. List Files (SmbFile.java:1266)
        at Test Jcifs.listRemote(Test Juifs.java:64)
        at Test Juifs.ci(Test Jcifs.java: 146)
        at Test Jcifs.main(Test Jcifs.java:28)


Users are asked to confirm the authority separately.
https://kb.netapp.com/app/answers/answer_view/a_id/1071815

**Comment by mbechler** [comment]
I think I found the issue, please try with latest master.

**Comment by yukiato** [comment]
Thank you very much. Let's ask the application vendor. I'll report again.

**Comment by yukiato** [comment]
Thank you problem solved.
There were about 1000 to 3000 hidden $ folders in the shared folder.
I want an early formal release.
