### ISSUE TITLE
SmbFile.setOwner() failed with 0xC000000D SmbException: The parameter is incorrect

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#183]
Hi,
We hit the error '0xC000000D, jcifs.smb.SmbException: The parameter is incorrect.' when using SmbFile.setOwner():

> 		SID newOwner = new SID("S-1-5-21-1110231572-2983002344-1517130557-1005");
> 		sf.setOwner(newOwner);

2019-07-26 23:25:15 DEBUG SmbTransportImpl:1391 - Error code: 0xC000000D for Smb2SetInfoRequest
2019-07-26 23:25:15 DEBUG SmbTreeConnection:324 - send
jcifs.smb.SmbException: The parameter is incorrect.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1393)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1504)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:980)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1802)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1771)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1765)
        at jcifs.smb.SmbFile.setOwner(SmbFile.java:2457)
        at Test_changeOwner.main(Test_changeOwner.java:100)
2019-07-26 23:25:15 DEBUG SmbTreeConnection:335 - Retrying (1/2) request [command=SMB2_CREATE,status=0,flags=0x0000,mid=21,wordCount=0,byteCount=80,name=empty.txt]
2019-07-26 23:25:15 DEBUG SmbTreeConnection:340 - Disconnecting tree on send retry
jcifs.smb.SmbException: The parameter is incorrect.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1393)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1504)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:980)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1802)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1771)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1765)
        at jcifs.smb.SmbFile.setOwner(SmbFile.java:2457)
        at Test_changeOwner.main(Test_changeOwner.java:100)
2019-07-26 23:25:15 WARN  SmbTreeImpl:735 - Disconnected tree while still in use SmbTree[share=THANHVN,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=3,usage=2]
2019-07-26 23:25:15 DEBUG SmbTreeConnection:501 - Tree is SmbTree[share=THANHVN,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=0,usage=3]
2019-07-26 23:25:15 DEBUG SmbTreeConnection:598 - Signatures for file enabled but not required jcifs.smb.SmbTreeConnection@1ff4931d
2019-07-26 23:25:15 DEBUG SmbTreeImpl:580 - treeConnect: unc=\\localhost\THANHVN,service=?????
2019-07-26 23:25:15 DEBUG SmbTreeConnection:373 - Have new tree connection for retry
2019-07-26 23:25:15 DEBUG Smb2CreateRequest:459 - Opening empty.txt
2019-07-26 23:25:15 DEBUG Smb2CloseRequest:136 - Closing FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (\empty.txt)
2019-07-26 23:25:15 DEBUG Smb2CreateResponse:323 - Opened empty.txt: 090100001000000019000000FFFFFFFF
2019-07-26 23:25:15 DEBUG SmbTransportImpl:1180 - Compound next command 80 readsize 80 remain 208
2019-07-26 23:25:15 DEBUG SmbTransportImpl:1180 - Compound next command 0 read size 128 remain 128
2019-07-26 23:25:15 DEBUG Smb2CloseResponse:226 - Closed FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (\empty.txt)
2019-07-26 23:25:15 DEBUG SmbTransportImpl:1391 - Error code: 0xC000000D for Smb2SetInfoRequest
2019-07-26 23:25:15 DEBUG SmbTreeConnection:324 - send
jcifs.smb.SmbException: The parameter is incorrect.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1393)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1504)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:980)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1802)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1771)
        at jcifs.smb.SmbFile.withOpen(SmbFile.java:1765)
        at jcifs.smb.SmbFile.setOwner(SmbFile.java:2457)
        at Test_changeOwner.main(Test_changeOwner.java:100)
2019-07-26 23:25:15 DEBUG SmbTreeConnection:335 - Retrying (2/2) request [command=SMB2_CREATE,status=0,flags=0x0000,mid=25,wordCount=0,byteCount=80,name=empty.txt]
2019-07-26 23:25:15 DEBUG SmbTreeConnection:340 - Disconnecting tree on send retry

Attached is the dump file and outputs

We checked the SID is the valid.  Can you help to see what may be wrong or what other parameter is needed?

[test_changeOwner.zip](https://github.com/AgNO3/jcifs-ng/files/3437850/test_changeOwner.zip)

**Comment by mbechler** [comment]
Can you please provide that packet dump in PCAP format.

**Comment by thanh-vn** [comment]
Hi,
Here is the cap format.  Thanks,

[owner_change.zip](https://github.com/AgNO3/jcifs-ng/files/3438312/owner_change.zip)

**Comment by mbechler** [comment]
That unfortunately does not seem to contain any SMB traffic.

**Comment by thanh-vn** [comment]
I apologized for that.
This is the new one we collected.

Thanks,

[test_changeOwner-cab.zip](https://github.com/AgNO3/jcifs-ng/files/3438462/test_changeOwner-cab.zip)

**Comment by mbechler** [comment]
I didn't realize it earlier, but jcifs-ng does not have that function, so this seems to be an issue with your patches. 

Apart from that there seems to be an issue encoding the SECINFO structure, the offsets are seems wrong.

**Comment by thanh-vn** [comment]
Thanks for looking at the issue!  Closing this.
