### ISSUE TITLE
Deadlock logging on

### ISSUE THREAD

**Issue by GerganDimirov** [AgNO3/jcifs-ng#188]
The following deadlock is observed during log on on a share:

"adapter-processor-thread-163822" Id=163822 in BLOCKED on lock=jcifs.smb.SmbTransportImpl@13dc4791     owned by adapter-processor-thread-164339 Id=164339
    at jcifs.util.transport.Transport.connect(Transport.java:529)
    at jcifs.smb.SmbTransportImpl.getNegotiateResponse(SmbTransportImpl.java:224)
    at jcifs.smb.SmbTransportImpl.isSigningEnforced(SmbTransportImpl.java:311)
    at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:134)
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:86)
      - locked java.util.LinkedList@7d4aeebe
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:64)
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
    at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:326)
    at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:320)

"adapter-processor-thread-164339" Id=164339 in BLOCKED on lock=java.util.LinkedList@7d4aeebe     owned by adapter-processor-thread-163822 Id=163822
    at jcifs.smb.SmbTransportPoolImpl.removeTransport(SmbTransportPoolImpl.java:257)
    at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:788)
      - locked jcifs.smb.SmbTransportImpl@13dc4791
    at jcifs.util.transport.Transport.disconnect(Transport.java:693)
      - locked jcifs.smb.SmbTransportImpl@13dc4791
    at jcifs.util.transport.Transport.disconnect(Transport.java:664)
      - locked jcifs.smb.SmbTransportImpl@13dc4791
    at jcifs.util.transport.Transport.sendrecv(Transport.java:237)
    at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
    at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:716)
    at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:668)
    at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
      - locked jcifs.smb.SmbTransportImpl@13dc4791
    at jcifs.smb.SmbTreeImpl.connectLogon(SmbTreeImpl.java:782)
    at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:330)

So for some reason, the first connect tries to disconnect on the Transport, and then remove the SmbTransportImpl from the pool, while the pool has the lock for the list of transports, and wants to invoke connect() on the same Transport.

**Comment by GerganDimirov** [comment]
Seems all released versions are affected.

**Comment by mbechler** [comment]
The second thread is trying to destroy the connection because there was an IOException (you may want to investigate the reason for this as well) while the first one is causing a connection attempt while trying to find a connection for reuse. 

The safe direct fix for the deadlock should be to delay the transport removal so that it happens outside of the code synchronized on transports.

There are probably at least two more issues here:
- we should not to pick up a disconnecting/failed connection, (the same issues however also may arise on parallel connection attempts)
- findConnection probably should avoid to cause a connection attempt (getting the information on whether the connection could be reused however requires just that)

**Comment by matheis** [comment]
We observed another occurrence of the above reported dead. I am attaching some sample stack, very similar to the reported one.

@mbechler Did you have a chance to look into that? 

We checked our code and see no possibility to change sth. in our code to avoid this situation. The network connection to the respective SMB server is rather unstable or this server is not able to handle the load and stops responding from time to time. Either way, we end up in this deadlock here. 

[another_deadlock_sample.txt](https://github.com/AgNO3/jcifs-ng/files/3819933/deadlock_sample.txt)

Additional question: Do you think, it is possible to explain the exception like this one:
```
[...]
Caused by: jcifs.smb.SmbException: Failed to acquire credits in time
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:960)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1266)

```
also mentioned in #132 by such a blocked SMB transport situation? We saw these kind of exceptions in our logs, too.

**Comment by mbechler** [comment]
Sorry for the delay.  I just commited some changes that should avoid the deadlock. This probably still needs some follow up, I suspect there still may be concurrency issues with parallel connections.

The exception is likely directly related, credits relate to the number of parallel inflight request on a connection - if other threads are stuck while sending requests, the credits are used up and never released, leaving none that the calling thread could aquire.

**Comment by matheis** [comment]
> Sorry for the delay. I just commited some changes that should avoid the deadlock. This probably still needs some follow up, I suspect there still may be concurrency issues with parallel connections.

Here is a follow-up thread dump excerpt (based on a 2.1.5 release). In a situation where one file server is not responding properly (due to unknown networking issues) we see the cleanup of the transport to block for "response timeout" seconds which lets threads pile up. 

```
"adapter-processor-thread-45099 (File Client)" Id=45099 in TIMED_WAITING on lock=java.lang.Thread@7b0042a5
    at java.lang.Object.wait(Native Method)
    at java.lang.Thread.join(Thread.java:1260)
    at jcifs.util.transport.Transport.cleanupThread(Transport.java:643)
      - locked jcifs.smb.SmbTransportImpl@31228a26
    at jcifs.util.transport.Transport.connect(Transport.java:602)
      - locked jcifs.smb.SmbTransportImpl@31228a26
    at jcifs.smb.SmbTransportImpl.getNegotiateResponse(SmbTransportImpl.java:224)
    at jcifs.smb.SmbTransportImpl.isSigningEnforced(SmbTransportImpl.java:315)
    at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:137)
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:89)
      - locked java.util.LinkedList@43473461
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:66)
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:48)
    at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:347)
    at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:340)
    [...]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
See the attached txt for samples of the waiting threads. I could see quite some of both threads waiting for **LinkedList@4347346**
[locking_during_transport_cleanup.txt](https://github.com/AgNO3/jcifs-ng/files/6695175/locking_during_transport_cleanup.txt)
