### ISSUE TITLE
SmbException: 'The network name cannot be found' - Accessing DFS share with jcifs-ng 2.x

### ISSUE THREAD

**Issue by throwinto2** [AgNO3/jcifs-ng#189]
I have a DFS share set up (2 Windows 2012 servers with a share that gets replicated, domain based DFS referral) and I cannot connect to these on my Java application using the jcifs-ng library v2.x.

I can access this share easily via the explorer with e.g. \\myDomain\myNamespace\myShare. I have a Java application that can also access this DFS share using the jcifs-ng library v1.5.3 without any problems. Using jcifs-ng v2.x will not work using SMB1 or SMB2. I keep getting a "SmbException: The network name cannot be found" exception.

`...Caused by: org.apache.commons.vfs.FileSystemException: Could not determine the type of file "smb://myDomain/myNamespace/myShare".
 at org.apache.commons.vfs.provider.AbstractFileObject.attach(AbstractFileObject.java:1485)
 at org.apache.commons.vfs.provider.AbstractFileObject.getType(AbstractFileObject.java:460)
 ... 38 more
Caused by: jcifs.smb.SmbException: The network name cannot be found.
 at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1457)
 at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
 at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
 at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
 at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
 at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
 at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
 at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
 at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
 at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
 at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
 at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
 at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
 at jcifs.smb.SmbFile.exists(SmbFile.java:845)
 at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1063)
 ... 40 more`

I already tried the properties "jcifs.smb.client.dfs.disabled=false", "jcifs.netbios.wins=x.x.x.x", "jcifs.resolveOrder", I exchanged the NtlmPasswordAuthentication with the newer NtlmPasswordAuthenticator, used the new CIFSContext but all to no avail.

If I set up a DFS namespace without adding a shared folder to it, I can access it. As soon as I add a shared folder to this namespace, the error will appear when trying to list all children of the DFS namespace. Somehow the DFS referral doesn't work for shares within the namespace.

Either I set up something wrong (but it works with 1.5.3) or there is a bug since v2.0.

**Comment by mbechler** [comment]
The most common issue would be something signing related. 
But there also is a good chance that you are hitting a bug, there have been a bunch of other reports of DFS issues which we haven't figured out yet. 
Can you provide more info? Debug logs and packet trace would be appreciated.

**Comment by throwinto2** [comment]
> 
> 
> The most common issue would be something signing related.
> But there also is a good chance that you are hitting a bug, there have been a bunch of other reports of DFS issues which we haven't figured out yet.
> Can you provide more info? Debug logs and packet trace would be appreciated.

Thank you for answering. I tried every combination with signing. I forced the signing on the Windows servers and in the Java application, and I disabled them as well (particularly the ipc signing property) but I get the same result wither way. Maybe I am missing something else..?
I can post more data in a few days. I am quite new to using this library, what form of packet trace and what log settings would you recommend I post?

**Comment by mbechler** [comment]
A PCAP trace of the port 445 traffic should be sufficient. If it's a small testcase TRACE level logging on the jcifs package should work fine.

**Comment by rconoverq** [comment]
Has there been any progress on this?  We have a client that has this same issue connecting to a DFS using jcifs-ng 2.1.9.

**Comment by shakethenet** [comment]
We had a similar DFS issue and were able to solve it, but frankly the solution was out of the jcifs-ng framework so I cannot go into details, at least not in this forum
