### ISSUE TITLE
SmbException: 0xC0000128 with getOwnerUser

### ISSUE THREAD

**Issue by Lavini281** [AgNO3/jcifs-ng#190]
Hi !

I am having a problem crawling an SMBv2 using [FESS](https://github.com/codelibs/fess-crawler/issues/46). They tell me that they are using your implementation of jcifs. My problem is that after some hours the crawler start to fail on all the document with this error.

```
org.codelibs.fess.crawler.exception.CrawlingAccessException: Cannot get owner of the file: smb://10.0.0.1/share/12818/document_20190608.pdf at at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:224)
at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:158)
at org.codelibs.fess.crawler.client.smb.SmbClient.doHead(SmbClient.java:390)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:144)
at org.codelibs.fess.crawler.FessCrawlerThread.isContentUpdated(FessCrawlerThread.java:85)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:155)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jcifs.smb.SmbException: 0xC0000128
at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1461)
at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1572)
at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1543)
at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1741)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1710)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1704)
at jcifs.smb.SmbFile.querySecurity(SmbFile.java:2220)
at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2269)
at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2262)
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:218)
... 6 more
```
From the microsoft [documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/8f11e0f3-d545-46cc-97e6-f00569e3e1bc), it looks like it stands for "STATUS_FILE_CLOSED" but I don't have any other clue.

Each time I manually restart the crawler, it starts working again for some hours before failing again.

Would you be able to help me ?

**Comment by mbechler** [comment]
Can you share more info, e.g. packet trace? 
This is a compound request, so we have to figure out first which command is causing the error.
From a first glance it does not make much sense that it would mean the file descriptor of the target file unless the open fails for some undetected reason.

Is the connection idle all the time? Maybe there is some server side session timeout that we have to avoid.

**Comment by Lavini281** [comment]
From what I observed with Wireshark the request were exactly the same. I think the issue was coming from the SMB server since I tried on another one and now it is working fine. I think we can close this issue since i don't think the problem is due to the client.

**Comment by Rick978** [comment]
Sy, but did you find the solution for the problem on the server? Have the same problem with FESS and dont have any ideas left... :(
