### ISSUE TITLE
RequestTimeoutException whilst Transport State is 3 - SMB2 Negotiation

### ISSUE THREAD

**Issue by JamesHopkinson** [AgNO3/jcifs-ng#192]
Hi,

Undergoing some issues when connecting to an SMB share via SMB2. I do not have access to the exact config of the fileshare.
Looking at the debug logs and previous issues raised I believe it is associated with the SMB2 Negotiation process. 

> 2019-10-31 17:17:26,069 [main] INFO  com.swhh.TestArchive - Created Root Took 273ms
2019-10-31 17:17:26,088 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - New transport connection Transport0[fileshare/1.1.1.1:445,state=0,signingEnforced=false,usage=1]
2019-10-31 17:17:26,088 [main] DEBUG jcifs.util.transport.Transport - Connecting Transport0
2019-10-31 17:17:26,088 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 1.1.1.1
2019-10-31 17:17:26,112 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@154c456
2019-10-31 17:17:26,112 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
2019-10-31 17:17:26,116 [main] DEBUG jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=domain\username,targetHost=fileshare,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
2019-10-31 17:17:26,119 [main] DEBUG jcifs.smb.SmbTreeImpl - Connection state was 0
2019-10-31 17:17:26,119 [main] DEBUG jcifs.smb.SmbTreeImpl - treeConnect: unc=\\fileshare\Share,service=?????
2019-10-31 17:17:26,120 [main] DEBUG jcifs.smb.SmbSessionImpl - sessionSetup: domain\username
2019-10-31 17:17:26,120 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is fileshare
2019-10-31 17:17:26,344 [main] DEBUG jcifs.smb.NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2, 1.3.6.1.4.1.311.2.2.10],mic=null]
2019-10-31 17:17:26,357 [main] DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=1,wordCount=0,byteCount=0
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Sign key is 0540C5040816E5A7586A1A184913A394
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Verify key is 9438FEAFEED071A9F309EA9660BE9230
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Seal key is 41143D5C9CA08CB4D34795A353D168E1
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Server seal key is 7A7534A668BD1276B617ADDF1F1E40CD
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Digest FD518080468B4948E8DCD78C4BB7AC73
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Truncated FD518080468B4948
2019-10-31 17:17:26,771 [main] DEBUG jcifs.smb.NtlmContext - Encrypted 95289ED088DDA590
2019-10-31 17:17:26,772 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list [1.3.6.1.4.1.311.2.2.10]
2019-10-31 17:17:26,772 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list encoded 300C060A2B06010401823702020A
2019-10-31 17:17:26,772 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list MIC 0100000095289ED088DDA59000000000
2019-10-31 17:17:26,775 [main] DEBUG jcifs.smb.SmbSessionImpl - Context is established
2019-10-31 17:17:26,775 [main] DEBUG jcifs.smb.SmbSessionImpl - No digest setup false B false
2019-10-31 17:17:26,777 [main] DEBUG jcifs.smb.SmbTreeImpl - Sending VALIDATE_NEGOTIATE_INFO
2019-10-31 17:17:56,781 [main] DEBUG jcifs.util.transport.Transport - State is 3
2019-10-31 17:17:56,781 [main] WARN  jcifs.util.transport.Transport - sendrecv failed
jcifs.util.transport.RequestTimeoutException: Transport0 timedout waiting for response to command=SMB2_IOCTL,status=0,flags=0x0000,mid=4,wordCount=0,byteCount=84
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1021)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:720)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:672)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:612)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.getTreeHandle(SmbFile.java:520)
	at com.swhh.smb.AwayFile.connect(AwayFile.java:88)
	at com.swhh.TestArchive.getFreshRoot(TestArchive.java:296)
	at com.swhh.TestWriting.main(TestWriting.java:64)
2019-10-31 17:17:56,784 [main] WARN  jcifs.smb.SmbTransportImpl - Disconnecting transport while still in use Transport0[fileshare/1.1.1.1:445,state=5,signingEnforced=false,usage=5]: [SmbSession[credentials=domain\username,targetHost=fileshare,targetDomain=null,uid=0,connectionState=2,usage=4]]
2019-10-31 17:17:56,784 [main] DEBUG jcifs.smb.SmbTransportImpl - Disconnecting transport Transport0[fileshare/1.1.1.1:445,state=5,signingEnforced=false,usage=5]
2019-10-31 17:17:56,784 [main] DEBUG jcifs.smb.SmbSessionImpl - Logging off session on Transport0[fileshare/1.1.1.1:445,state=5,signingEnforced=false,usage=6]
2019-10-31 17:17:56,784 [main] WARN  jcifs.smb.SmbSessionImpl - Logging off session while still in use SmbSession[credentials=domain\username,targetHost=fileshare,targetDomain=null,uid=0,connectionState=3,usage=4]:[SmbTree[share=Share,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
2019-10-31 17:17:56,784 [main] DEBUG jcifs.smb.SmbSessionImpl - Disconnect tree on logoff
2019-10-31 17:17:56,784 [main] WARN  jcifs.smb.SmbTreeImpl - Disconnected tree while still in use SmbTree[share=Share,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
2019-10-31 17:17:56,784 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - Removing transport connection Transport0[fileshare/1.1.1.1:445,state=5,signingEnforced=false,usage=5] (302870502)
2019-10-31 17:17:56,785 [main] DEBUG jcifs.smb.SmbTreeImpl - VALIDATE_NEGOTIATE_INFO response code 0xc0000001
2019-10-31 17:17:56,785 [main] DEBUG jcifs.smb.SmbTreeConnection - Switching tree
2019-10-31 17:17:56,785 [main] DEBUG jcifs.smb.SmbTreeConnection - Acquired tree on switch SmbTree[share=Share,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=0,usage=2]
2019-10-31 17:17:56,786 [main] DEBUG jcifs.smb.SmbTreeConnection - Tree is SmbTree[share=Share,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=0,usage=2]
2019-10-31 17:17:56,786 [main] DEBUG jcifs.smb.SmbTreeConnection - Session no longer valid
2019-10-31 17:17:56,786 [Transport0] DEBUG jcifs.util.transport.Transport - recv failed
java.io.IOException: end of stream
	at jcifs.util.transport.Transport.loop(Transport.java:448)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.lang.Thread.run(Thread.java:748)
2019-10-31 17:17:56,787 [Transport0] DEBUG jcifs.util.transport.Transport - Disconnected
2019-10-31 17:17:56,787 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - New transport connection Transport1[fileshare/1.1.1.1:445,state=0,signingEnforced=false,usage=1]
2019-10-31 17:17:56,787 [main] DEBUG jcifs.util.transport.Transport - Connecting Transport1
2019-10-31 17:17:56,787 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 1.1.1.1
2019-10-31 17:17:56,788 [Transport0] DEBUG jcifs.util.transport.Transport - Notified clients
2019-10-31 17:17:56,789 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Negotiation response on Transport1 :jcifs.internal.SmbNegotiation@32485a48
2019-10-31 17:17:56,789 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true) 

Reviewing this - a few log lines that seem to indicate an issue are:

> 2019-10-31 17:17:26,357 [main] DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=1,wordCount=0,byteCount=0
2019-10-31 17:17:56,789 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true) 

I have a test harness I can deploy to test various properties/combinations of properties to see if they resolve the issue. What might potential properties be that would be valid to test this area? Or alternatively could this be a bug in the SMB2 Negotiation being used?

I was thinking along the lines of:
jcifs.smb.client.signingPreferred=true
jcifs.smb.client.useSMB2Negotiation=true
jcifs.smb.client.ipcSigningEnforced=false

**Comment by JamesHopkinson** [comment]
Reviewed wireshark trace for the given archive and seems we never get the response for FSCTL_VALIDATE_NEGOTIATE_INFO at which point it eventually times out:

![image](https://user-images.githubusercontent.com/43962958/68489722-8bcec300-023f-11ea-9f62-97d0744b48a5.png)

**Comment by mbechler** [comment]
This would be the expected server behavior if something is wrong with the transmitted negotiation data. Can you provide the trace? Or please check whether the information included in the validate_negotiate_info matches the one in the negotitation request or if not what is different.

**Comment by JamesHopkinson** [comment]
Ran a test on the working system and notice a slight discrepancy in the stream of messages. Specifically that after the initial Negotiate Protocol (SMB1) is sent, we then send another Negotiate Protocol message in SMB2. However, in the erroneous state it never sends Negotiate Protocol message in SMB.
Due to this  - its hard to do a comparison as the protocol sent is different.

Another thing I noticed is that despite specifying the properties to be between SMB202 -> SMB210 it still does an initial connection with SMB1 - is there a way to force the initial request to be SMB2?

![image](https://user-images.githubusercontent.com/43962958/68579556-4c38ee80-046c-11ea-9a18-7c4d812efb3a.png)

**Comment by mbechler** [comment]
So this only happens when establishing additional sessions on an existing connection? Otherwise there definitely should be a negotiation.

You can disable multi-protocol negotation with jcifs.smb.client.useSMB2Negotiation=true.

**Comment by JamesHopkinson** [comment]
Ran a test with this property and see similar issues as without the property (although the initial message is now SMB2).
The only differences in the SMB2 layer are (Negotiate Request - Validate_Negotiate_Info):
Credits requested: 512 - 128
Message ID: Unknown (0) - Unknown (4)
Tree ID: 0x00000000 - 0x00000001 \\hostname\path
Session ID: 0x0000000000000000 - 0x5dc481a30000427c Acct: username Domain: domain Host:

**Comment by Alunisiira** [comment]
Hi, 
got the same error, but not able to post any wireshark or server insights. But could provide debug level 10 if needed.
Java small stack:
WARN : SmbTransportImpl - Failure decoding message, disconnecting transport
java.io.IOException: WHAT? ( read 73 decoded 144 ): command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0
	at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1197)
	at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1143)

Thanks,
Jan

**Comment by mbechler** [comment]
So the information inside the VALIDATE_NEGOTITATE_INFO body is all exactly the same as in the SmbNegotiateRequest?

Which settings for min/max Protocol versions are you using?
Reading the documentation again sending the VALIDATE_NEGOTITATE_INFO is only required if the clients max version is set to >= 3, so we could possibly avoid the issue. This also could possibly be the isue, but I don't see why a server would enforce this.

You could also try setting  jcifs.smb.client.requireSecureNegotiate=false, this disables the validation, so we can see whether this really is the issue.

@Alunisiira this looks like a different error, please open a new issue, some details on the failing request/response will definitely be required.

**Comment by JamesHopkinson** [comment]
The min/max versions of the protocol are: SMB202, SMB210 so this could help resolve the issue as the server could be blocking the response to this message in an attempt to be more secure.

We no longer have access to this specific File Server to test but will check this setting if we ever see this issue again, however it would be good to have a release where we avoid the VALIDATE_NEGOTIATE_INFO issue.

**Comment by JamesHopkinson** [comment]
Further information on the fileshare seems to indicate that this would be the problem. Is there any additional information I can provide that can expedite this?

**Comment by abhijith142** [comment]
Hi James, 
 I was facing the same issue when trying to connect to **EMC VNX 5400**, the connection was failing as below

`
2019-11-28/13:19:35.851/UTC [pool-76-thread-11] DEBUG jcifs.smb.NtlmContext  - Truncated 79C564A6189985A9
2019-11-28/13:19:35.851/UTC [pool-76-thread-11] DEBUG jcifs.smb.SpnegoContext  - Out Mech list [1.3.6.1.4.1.311.2.2.10]
2019-11-28/13:19:35.851/UTC [pool-76-thread-11] DEBUG jcifs.smb.SpnegoContext  - Out Mech list encoded 300C060A2B06010401823702020A
2019-11-28/13:19:35.851/UTC [pool-76-thread-11] DEBUG jcifs.smb.SpnegoContext  - Out Mech list MIC 0100000079C564A6189985A900000000
2019-11-28/13:19:35.855/UTC [pool-76-thread-11] DEBUG jcifs.smb.SmbSessionImpl  - Context is established
2019-11-28/13:19:35.855/UTC [pool-76-thread-11] DEBUG jcifs.smb.SmbSessionImpl  - No digest setup false B false
2019-11-28/13:19:35.856/UTC [pool-76-thread-11] DEBUG jcifs.smb.SmbTreeImpl  - Sending VALIDATE_NEGOTIATE_INFO
2019-11-28/13:19:49.853/UTC [pool-76-thread-10] DEBUG jcifs.util.transport.Transport  - State is 3
2019-11-28/13:19:49.853/UTC [pool-76-thread-10] WARN  jcifs.util.transport.Transport  - sendrecv failed
jcifs.util.transport.RequestTimeoutException: Transport63 timedout waiting for response to command=SMB2_IOCTL,status=0,flags=0x0000,mid=4,wordCount=0,byteCount=84
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
`

 Solved the issue by setting `jcifs.smb.client.requireSecureNegotiate=false`. However I had to change the source code to change the variable "requireSecureNegotiate" in BaseConfiguration.java from private access to protected access and provide a hook in PropertyConfiguration.java to read the value from the Properties and set it to the variable "requireSecureNegotiate".

Thanks,
Abhijith S

**Comment by JamesHopkinson** [comment]
Hi Abhijith,

Ran a small test harness with these changes against the system and it does seem to resolve the issue. So this is definitely a fix for the problem we've been experiencing - thank you for the assistance. 

It would be good to get this in the next release of JCIFS when we can.

Thanks again for the help,
James

**Comment by mbechler** [comment]
I added the missing configuration option. 
Still, I think we should figure out what the issue actually is. One possible issue I realized is that we may possibly have sent unsigned VALIDATE_NEGOTIATE_INFO requests, which is wrong. This should be fixed now as well, plase check whether this was the case and works now, even with the validation enabled?

**Comment by JamesHopkinson** [comment]
Got access to a different system that seemed to experience the same issue as this setup.
Upgraded to the latest version (2.1.4) and it seems to be working as expected.

Issue can be closed now - apologies for the delay in getting back to this.
