### ISSUE TITLE
Can not connect to SMB2 - transport closed in negotiate, then jcifs.util.transport.RequestTimeoutException: Transport4 timedout waiting for response to command=SMB2_IOCTL,status=0,flags=0x0000,mid=4,wordCount=0,byteCount=84

### ISSUE THREAD

**Issue by jerryduval** [AgNO3/jcifs-ng#194]
When connecting using 

jcifs-ng-2.1.1.jar via vfs-jcifs-ng

We first encountered this problem

jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/10.154.47.140
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:669)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:214)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1056)
	at net.idauto.oss.jcifsng.vfs2.provider.SmbFileObject.createSmbFile(SmbFileObject.java:73)
	at net.idauto.oss.jcifsng.vfs2.provider.SmbFileObject.doAttach(SmbFileObject.java:53)
	at org.apache.commons.vfs2.provider.AbstractFileObject.attach(AbstractFileObject.java:156)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:1280)
	at org.apache.commons.vfs2.provider.AbstractFileObject.exists(AbstractFileObject.java:889)
	at com.pace2020.appbox.blocks.virtualfilesystem.FileObjectWrapper.exists(FileObjectWrapper.java:52)
	at com.pace2020.epace.blocks.webservices.TestNetworkLocationWebService.test(TestNetworkLocationWebService.java:130)
	at com.pace2020.epace.blocks.webservices.TestNetworkLocationWebService.execute(TestNetworkLocationWebService.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.pace2020.epace.blocks.webservices.WebServiceInvocationHandler.invoke(WebServiceInvocationHandler.java:48)
	at com.sun.proxy.$Proxy429.execute(Unknown Source)
	at com.pace2020.epace.blocks.webservices.PicoWebServiceManagerDelegate.execute(PicoWebServiceManagerDelegate.java:199)
	at com.pace2020.epace.blocks.webservices.PicoWebServiceManager.execute(PicoWebServiceManager.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.avalon.phoenix.components.application.BlockInvocationHandler.invoke(BlockInvocationHandler.java:134)
rethrown from
jcifs.util.transport.TransportException: java.io.IOException: transport closed in negotiate
	at jcifs.util.transport.Transport.run(Transport.java:759)
	at java.lang.Thread.run(Thread.java:748)

Then we jcifs.smb.client.useSMB2Negotiation=true 

now we are encountering 

 WARN | sendrecv failed
jcifs.util.transport.RequestTimeoutException: Transport0 timedout waiting for response to command=SMB2_IOCTL,status=0,flags=0x0000,mid=4,wordCount=0,byteCount=84
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:716)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:668)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)

 WARN | Disconnecting transport while still in use Transport0[0.0.0.0<00>/10.154.47.140:445,state=5,signingEnforced=false,usage=5]: [SmbSession[credentials=hi\ld,targetHost=10.154.47.140,targetDomain=null,uid=0,connectionState=2,usage=4]]
 WARN | Logging off session while still in use SmbSession[credentials=hi\ld,targetHost=10.154.47.140,targetDomain=null,uid=0,connectionState=3,usage=4]:[SmbTree[share=CORPDATA02,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
 WARN | Disconnected tree while still in use SmbTree[share=CORPDATA02,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
 WARN | sendrecv failed
jcifs.util.transport.RequestTimeoutException: Transport1 timedout waiting for response to command=SMB2_IOCTL,status=0,flags=0x0000,mid=4,wordCount=0,byteCount=84
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1523)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:716)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:668)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:608)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbTreeConnection.resolveDfs0(SmbTreeConnection.java:684)
	at jcifs.smb.SmbTreeConnection.ensureDFSResolved(SmbTreeConnection.java:653)
	at jcifs.smb.SmbTreeConnection.ensureDFSResolved(SmbTreeConnection.java:643)
	at jcifs.smb.SmbTreeHandleImpl.ensureDFSResolved(SmbTreeHandleImpl.java:69)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:552)
	at jcifs.smb.SmbFile.exists(SmbFile.java:838)
	at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1056)

**Comment by mbechler** [comment]
The first issue might be #156, the seconds possbily #192. Can you provide a packet capture? If you can please also test whether there any diffrences in master.
