### ISSUE TITLE
Failed to resolve SIDs with jcifs.dcerpc.DcerpcException: DCERPC_FAULT_PROTO_ERROR

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#197]
We are trying to connect to a Windows server through EMC VNX storage.  At first we failed to connect to it.  With the jcifs.smb.client.useSMB2Negotiation=true, we are able to connect to the environment.

It is now failing when we are calling jcifs.smb.SmbFile.getOwnerUser API.  The error happens during SIDCacheImpl.resolveSids():
Failed to resolve SIDs with jcifs.dcerpc.DcerpcException: DCERPC_FAULT_PROTO_ERROR

[2019-11-08 15:25:00,053] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbResourceLocatorImpl Share is IPC IPC$
[2019-11-08 15:25:00,058] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbResourceLocatorImpl Share is IPC IPC$
[2019-11-08 15:25:00,059] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeImpl treeConnect: unc=\\server06\IPC$,service=?????
[2019-11-08 15:25:00,091] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeImpl Sending VALIDATE_NEGOTIATE_INFO
[2019-11-08 15:25:00,124] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeImpl Secure negotiation OK
[2019-11-08 15:25:00,124] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeConnection Switching tree
[2019-11-08 15:25:00,124] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeConnection Acquired tree on switch SmbTree[share=IPC$,service=null,tid=2,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
[2019-11-08 15:25:00,125] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbFile openUnshared: \lsarpc flags: 19f0023 access: 20003 attrs: 80 options: 0
[2019-11-08 15:25:00,125] DEBUG [1332239337@qtp-1393886351-0] jcifs.internal.smb2.create.Smb2CreateRequest Opening lsarpc
[2019-11-08 15:25:00,158] DEBUG [Transport0] jcifs.internal.smb2.create.Smb2CreateResponse Opened lsarpc: 53A52D231BCFC55D01000000FFFFFFFF
[2019-11-08 15:25:00,295] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SIDCacheImpl Failed to resolve SIDs
jcifs.dcerpc.DcerpcException: DCERPC_FAULT_PROTO_ERROR
	at jcifs.dcerpc.DcerpcMessage.getResult(DcerpcMessage.java:77) ~[jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:266) ~[jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:70) ~[jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:120) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:215) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SID.resolve(SID.java:480) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2362) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2347) [jcifs-ng-2.1.1-flx.1.jar:?]
...
[2019-11-08 15:25:00,300] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbFileHandleImpl Closing file handle FileHandle \lsarpc [fid=53A52D231BCFC55D01000000FFFFFFFF,tree=2,flags=19f0023,access=20003,attrs=0,options=0]
[2019-11-08 15:25:00,300] DEBUG [1332239337@qtp-1393886351-0] jcifs.internal.smb2.create.Smb2CloseRequest Closing 53A52D231BCFC55D01000000FFFFFFFF ()
[2019-11-08 15:25:00,333] DEBUG [Transport0] jcifs.internal.smb2.create.Smb2CloseResponse Closed 53A52D231BCFC55D01000000FFFFFFFF ()
[2019-11-08 15:25:00,333] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeConnection Tree connection no longer in use, release tree SmbTree[share=IPC$,service=null,tid=2,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
[2019-11-08 15:25:00,334] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SmbTreeImpl Usage dropped to zero, release session
[2019-11-08 15:25:00,334] DEBUG [1332239337@qtp-1393886351-0] jcifs.smb.SIDCacheImpl Failed to resolve SIDs
jcifs.CIFSException: Failed to resolve SIDs resolveSids
	at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:124) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:215) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SID.resolve(SID.java:480) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2362) [jcifs-ng-2.1.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2347) [jcifs-ng-2.1.1-flx.1.jar:?]

We added more debug info and seeing the package type (ptype) of DcerpcMessage changed from '0' to '3' after the call of decode() / **decode_header**(buf);

Appreciate your help to look at this issue,
Thanks, Thanh

**Comment by mbechler** [comment]
There were some DCERPC encoding related fixes in 2.1.2/3 please check whether these change something.

**Comment by thanh-vn** [comment]
Thanks, We picked up the latest DCERPC encoding fixes and resolved the issue.
