### ISSUE TITLE
smb2 listFiles crash while smb1 works on Swisscom Internet Gateway 2

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#200]
Using the smbcli https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0 test program, I get the following crash using listFiles on a Swisscom Internet Gateway 2 with SMB2 while it works forcing SMB1 using current jcifs-ng master 22cf4f1:
```
smbcli 2 smb://internetbox-nas/MARC/ "" lurker PASSWORD

2020-01-02 11:25:35 INFO  smbcli:106 - Enabling SMB2
2020-01-02 11:25:42 WARN  SmbTransportImpl:764 - Disconnecting transport while still in use Transport0[internetbox-nas/192.168.1.220:445,state=5,signingEnforced=false,usage=3]: [SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=2,usage=3]]
2020-01-02 11:25:42 WARN  SmbSessionImpl:1122 - Logging off session while still in use SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=3,usage=3]:[SmbTree[share=MARC,service=null,tid=10,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
2020-01-02 11:25:42 WARN  SmbTreeImpl:826 - Disconnected tree while still in use SmbTree[share=MARC,service=null,tid=10,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
2020-01-02 11:25:42 WARN  SmbSessionImpl:1132 - Failed to disconnect tree SmbTree[share=MARC,service=null,tid=10,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:830)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1129)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:780)
	at jcifs.util.transport.Transport.disconnect(Transport.java:693)
	at jcifs.util.transport.Transport.disconnect(Transport.java:664)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:676)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:612)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:558)
	at jcifs.smb.SmbFile.getType(SmbFile.java:899)
	at smbcli.main(smbcli.java:119)
2020-01-02 11:25:42 INFO  smbcli:129 - smbFile is a filesystem
2020-01-02 11:25:42 INFO  smbcli:138 - Current smbFile name = MARC/
2020-01-02 11:25:42 WARN  SmbTransportImpl:764 - Disconnecting transport while still in use Transport1[internetbox-nas/192.168.1.220:445,state=5,signingEnforced=false,usage=3]: [SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=2,usage=3]]
2020-01-02 11:25:42 WARN  SmbSessionImpl:1122 - Logging off session while still in use SmbSession[credentials=lurker,targetHost=internetbox-nas,targetDomain=null,uid=0,connectionState=3,usage=3]:[SmbTree[share=MARC,service=null,tid=10,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]]
2020-01-02 11:25:42 WARN  SmbTreeImpl:826 - Disconnected tree while still in use SmbTree[share=MARC,service=null,tid=10,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
2020-01-02 11:25:42 WARN  SmbSessionImpl:1132 - Failed to disconnect tree SmbTree[share=MARC,service=null,tid=10,inDfs=false,inDomainDfs=false,connectionState=3,usage=1]
jcifs.RuntimeCIFSException: Disconnected tree while still in use
	at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:830)
	at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1129)
	at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:780)
	at jcifs.util.transport.Transport.disconnect(Transport.java:693)
	at jcifs.util.transport.Transport.disconnect(Transport.java:664)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:676)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:612)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:558)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1206)
	at smbcli.main(smbcli.java:139)
2020-01-02 11:25:42 WARN  smbcli:143 - Caught a SmbException on listFiles
jcifs.smb.SmbException: Failed to connect to server
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:435)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:558)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1206)
	at smbcli.main(smbcli.java:139)
Caused by: jcifs.CIFSException: Mismatched attributes validating negotiate info
	at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:743)
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:672)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:612)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	... 5 more
2020-01-02 11:25:42 INFO  smbcli:165 - smbFilesArray is null

Process finished with exit code 0
```
Corresponding wireshark capture available here:
[20200102-swisscom-smb2_crash.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/4015606/20200102-swisscom-smb2_crash.pcap.zip)

Corresponding wireshark capture of working session when forcing SMB1 `smbcli 1 smb://internetbox-nas/MARC/ "" lurker PASSWORD` can be found here: 
[20200102-swisscom-smb1_ok.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/4015610/20200102-swisscom-smb1_ok.pcap.zip)

Please do not hesitate to ask for more information/tests if needed.

**Comment by mbechler** [comment]
This really looks like a server bug to me, the server picks SMB version 2.10 but in the VALIDATE_NEGOTIATE_INFO response it specifies version 2.02. 
You can may be able to avoid the issue by disabling negotiate validation (see #192).

**Comment by courville** [comment]
Thanks for getting back to me, I thus close the issue.

**Comment by courville** [comment]
Note that the latest changes made on July 7th 2020 makes it work with the Swisscom Internet Gateway 2.
I guess it really closes the issue.
Thanks!
