### ISSUE TITLE
jcifs.smb.SmbException: Transport disconnected while waiting for connection

### ISSUE THREAD

**Issue by felixRajkumar** [AgNO3/jcifs-ng#204]
Hi, I am trying to get directories from a specified host using smb. It had been working  perfectly. But all of a sudden I am getting the following exception. I am not sure why am I getting it. Thanks in advance for all the help.

> [12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: jcifs.smb.SmbException: Transport disconnected while waiting for connection|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:562)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:617)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:149)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:222)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)|
[12:40:58:071]|[01-30-2020]|[SYSERR]|[INFO]|[145]: 	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1179)|

**Comment by mbechler** [comment]
So nothing has changed, or did you update the library? Can you provide a packet capture?

**Comment by felixRajkumar** [comment]
> So nothing has changed, or did you update the library? Can you provide a packet capture?

Since it is an intermittent issue, I could not provide a packet capture. But I can tell you the version I am currently using. The version is  jcifs-ng-2.0.6.

**Comment by felixRajkumar** [comment]
The issue got fixed when I updated the jar and its dependencies. Previously I used 2.0.6 but when I upgraded it to 2.1.3 . This issue is fixed. Also the above issue is an intermittent issue.
