### ISSUE TITLE
jcifs.util.transport.TransportException: Transport1062 error reading response to command

### ISSUE THREAD

**Issue by felixRajkumar** [AgNO3/jcifs-ng#207]
Hi , I am using jcifs-ng to read files. I am getting the following error, I think this error is related to smb configurations. Can someone throw a light on this.

> [10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: jcifs.util.transport.TransportException: Transport1061 error reading response to command=SMB2_READ,status=0,flags=0x0000,mid=8,wordCount=0,byteCount=49|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.util.transport.Transport.waitForResponses(Transport.java:351)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:978)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at java.io.BufferedReader.fill(BufferedReader.java:161)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)|
[10:36:47:192]|[02-18-2020]|[SYSERR]|[INFO]|[283]: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)|

**Comment by mbechler** [comment]
Needs more info, there should be a chained exception.

**Comment by felixRajkumar** [comment]
> Needs more info, there should be a chained exception.

Yea this one too

`[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: jcifs.util.transport.RequestTimeoutException: Transport2768 timedout waiting for response to command=SMB2_READ,status=0,flags=0x0000,mid=8,wordCount=0,byteCount=49|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:978)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at java.io.BufferedReader.fill(BufferedReader.java:161)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)|
[00:02:55:038]|[02-14-2020]|[SYSERR]|[INFO]|[683]: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)|`

**Comment by felixRajkumar** [comment]
> Needs more info, there should be a chained exception.

I guess it is a lock issue but couldn't really find what the cause is, May I know what are the conclusions we can arrive from this exceptions

**Comment by felixRajkumar** [comment]
> Needs more info, there should be a chained exception.

The issue didnt get resolved and this is the chained exception 


> [14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: jcifs.util.transport.TransportException: Transport6 error reading response to command=SMB2_READ,status=0,flags=0x0000,mid=7,wordCount=0,byteCount=49|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.util.transport.Transport.waitForResponses(Transport.java:351)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1021)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.io.BufferedReader.fill(BufferedReader.java:161)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at com.manageengine.ela.server.importlog.LogBuilder.open(LogBuilder.java:188)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at com.manageengine.ela.server.common.io.file.parser.FileParser.processLog(FileParser.java:72)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at com.manageengine.ela.server.common.io.file.parser.FileParser.parseFile(FileParser.java:41)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at com.manageengine.ela.server.application.webserver.iis.processor.IISLogProcessor.process(IISLogProcessor.java:68)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at com.manageengine.ela.server.application.webserver.iis.processor.IISLogProcessor.process(IISLogProcessor.java:30)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at com.manageengine.ela.server.common.executors.processor.CommonQueueProcessor.run(CommonQueueProcessor.java:56)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.lang.Thread.run(Thread.java:745)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: Caused by: java.net.SocketException: Connection reset|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.net.SocketInputStream.read(SocketInputStream.java:209)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.util.transport.Transport.readn(Transport.java:70)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.smb.SmbTransportImpl.peekKey(SmbTransportImpl.java:824)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.util.transport.Transport.loop(Transport.java:420)|
[14:56:42:338]|[03-03-2020]|[SYSERR]|[INFO]|[518]: 	at jcifs.util.transport.Transport.run(Transport.java:769)|

**Comment by mbechler** [comment]
It should a timeout, unfortunately not why this is occuring, can you provide a more complete log file and network capture?

**Comment by felixRajkumar** [comment]
> It shows a timeout waiting for the response, unfortunately not why this is occuring, can you provide a more complete log file and network capture?

I am sorry, I could'nt get network capture, but here is the complete log trace


> [16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: jcifs.util.transport.TransportException: Transport4915 error reading response to command=SMB2_READ,status=0,flags=0x0000,mid=8,wordCount=0,byteCount=49|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.util.transport.Transport.waitForResponses(Transport.java:351)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:978)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbFileInputStream.readDirect(SmbFileInputStream.java:331)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbFileInputStream.read(SmbFileInputStream.java:274)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.io.BufferedReader.fill(BufferedReader.java:161)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.protocols.ImportBufferedReader.readImportLine(ImportBufferedReader.java:49)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.LogBuilder.open(LogBuilder.java:180)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.processors.BaseLogProcessor.processNewSource(BaseLogProcessor.java:158)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.processors.BaseLogProcessor.process(BaseLogProcessor.java:77)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.processors.BaseLogProcessor.process(BaseLogProcessor.java:46)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.common.executors.processor.CommonQueueProcessor.run(CommonQueueProcessor.java:68)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.lang.Thread.run(Thread.java:745)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: Caused by: java.net.SocketException: Connection reset|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.net.SocketInputStream.read(SocketInputStream.java:209)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.util.transport.Transport.readn(Transport.java:70)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.smb.SmbTransportImpl.peekKey(SmbTransportImpl.java:783)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.util.transport.Transport.loop(Transport.java:420)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at jcifs.util.transport.Transport.run(Transport.java:762)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	... 1 more|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: Status Code 0x1a07: IO operation failed|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.common.response.BaseStatusCode.getBaseStatusCode(BaseStatusCode.java:90)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.common.response.BaseStatusCode.getBaseStatusCode(BaseStatusCode.java:82)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.LogBuilder.open(LogBuilder.java:238)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.processors.BaseLogProcessor.processNewSource(BaseLogProcessor.java:158)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.processors.BaseLogProcessor.process(BaseLogProcessor.java:77)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.importlog.processors.BaseLogProcessor.process(BaseLogProcessor.java:46)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at com.manageengine.ela.server.common.executors.processor.CommonQueueProcessor.run(CommonQueueProcessor.java:68)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|
[16:08:23:466]|[10-29-2020]|[SYSERR]|[INFO]|[330]: 	at java.lang.Thread.run(Thread.java:745)|
