### ISSUE TITLE
Get only the shared directories by the user

### ISSUE THREAD

**Issue by felixRajkumar** [AgNO3/jcifs-ng#208]
Hi, 
    Is it possible to find if a drive is shared or not by means of jcifs-ng.

**Comment by mbechler** [comment]
What do you mean by that?

**Comment by felixRajkumar** [comment]
> What do you mean by that?

For example, there are three drives C:\\, D:\\, E:\\. The user has only shared E:\\. Then while listing files of that system, I should only show E:\\, Can I achieve this with jcifs-ng alone or should I go with any other api's.

**Comment by mbechler** [comment]
You can enumerate the server's shares, however I don't think you can get the actual filesystem location shared. 
I guess you'd need some server/windows specific code to get that.

**Comment by felixRajkumar** [comment]
> You can enumerate the server's shares, however I don't think you can get the actual filesystem location shared.
> I guess you'd need some server/windows specific code to get that.

Yeah I think so. I was searching for a long time, still couldn't make a proper blueprint for executing the above task.

**Comment by felixRajkumar** [comment]
I found this 

`String path="smb://172.16.0.11/";

SmbFile smbFile = new SmbFile(path);
String a[]=smbFile.list();
for(int i=0;i<a.length;i++)
{
    System.out.println(a[i]);
}`
here [https://stackoverflow.com/questions/2171822/connecting-to-shared-folder-in-windows-with-java](url)
It doesn't work and I am getting the following exception

> Exception in thread "main" jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1426)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:145)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:218)
	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:243)
	at jcifs.smb.SmbFile.list(SmbFile.java:1148)
	at executeTask.main(executeTask.java:11)
