### ISSUE TITLE
Exception jcifs.smb.SmbTransport.ssn139(SmbTransport.java:239)

### ISSUE THREAD

**Issue by simo385** [AgNO3/jcifs-ng#209]
Hi Everybody,

**Environment:**
Debian 9
Java 8

We’re using jcifs-2.1.13 into our maven project, but we get the following problem during a samba connection (towards a Windows system):

_jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/10.0.X.X
jcifs.util.transport.TransportException: Connection in error
jcifs.util.transport.TransportException
java.io.IOException: Failed to establish session with 0.0.0.0<00>/10.0.X.X
**at jcifs.smb.SmbTransport.ssn139(SmbTransport.java:239)**
at jcifs.smb.SmbTransport.negotiate(SmbTransport.java:249)
at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:319)
at jcifs.util.transport.Transport.run(Transport.java:241)
at java.lang.Thread.run(Thread.java:748)
at jcifs.util.transport.Transport.run(Transport.java:258)
at java.lang.Thread.run(Thread.java:748)
at jcifs.util.transport.Transport.connect(Transport.java:154)
at jcifs.smb.SmbTransport.connect(SmbTransport.java:307)
at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)
at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)
at jcifs.smb.SmbFile.connect(SmbFile.java:957)
at jcifs.smb.SmbFile.connect0(SmbFile.java:880)
at jcifs.smb.SmbFile.queryPath(SmbFile.java:1338)
at jcifs.smb.SmbFile.exists(SmbFile.java:1420)
at world.dedicated.Transfer.SmbConnection.changeWorkingDirectory(SmbConnection.java:307)
at world.dedicated.Transfer.ConnectionClient.checkDirectoryExists(ConnectionClient.java:915)
at world.dedicated.Transfer.ConnectionClient.check_remoteFolder(ConnectionClient.java:657)
at world.dedicated.Transfer.ConnectionClient.process(ConnectionClient.java:736)_

The connection routine in a Runnable class is located, which every hour is scheduled. 

The problem is the following:
After the error, we need to restart the whole JVM, because the routine doesn’t work anymore. 
We get this error (sometimes) when our client restarts his servers.

Is there a way to reset the samba connection?
Are there some fixes to do?

Thanks in advance,
Simone

**Comment by mbechler** [comment]
That stacktrace does not align with any jcifs-ng 2.* version. Please check which library you are actually using.

**Comment by simo385** [comment]
Hi Mbechler,

I'm so sorry, I'm using the Jcifs (codelibs) library. 
Do you know how get in touch with them?

Many thanks for your support,
Simone
