### ISSUE TITLE
truncated and corrupted listfiles on synology when using SMBv1 and not SMBv2

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#210]
Using the smbcli https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0 test program, I get the following corrupted/trunkated listFiles on a synology forcing SMB1 protocol while it is ok when using SMB2 (using current jcifs-ng master https://github.com/AgNO3/jcifs-ng/commit/bb4d2f47a9302c955f61deaaf7bbea5cb1222db4).
This is probably caused by the error reported in the `smbFilesArray = smbFile.listFiles();` that appears only with SMBv1.

Please find below the logs and wireshark captures of the exchanges:
- when SMBv1 is used: `smbcli 1 smb://DS414/ "" login password` 
[smb1-corrupted_listfiles.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/4289502/smb1-corrupted_listfiles.pcap.zip)
```
2020-03-04 21:06:49 INFO  smbcli:127 - smbFile is a server
2020-03-04 21:06:49 INFO  smbcli:138 - Current smbFile name = DS414/
2020-03-04 21:06:50 ERROR ShareEnumIterator:69 - Failed to create child URL
java.net.MalformedURLException: Name must not be empty
	at jcifs.smb.SmbFile.checkName(SmbFile.java:587)
	at jcifs.smb.SmbFile.<init>(SmbFile.java:466)
	at jcifs.smb.ShareEnumIterator.adapt(ShareEnumIterator.java:93)
	at jcifs.smb.ShareEnumIterator.advance(ShareEnumIterator.java:66)
	at jcifs.smb.ShareEnumIterator.next(ShareEnumIterator.java:116)
	at jcifs.smb.ShareEnumIterator.next(ShareEnumIterator.java:34)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:288)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1206)
	at smbcli.main(smbcli.java:139)
smb://DS414/app/ exists but cannot access with provided credentials
smb://DS414/audiobook/ exists but cannot access with provided credentials
smb://DS414/backup/ exists but cannot access with provided credentials
smb://DS414/bd/ exists
smb://DS414/game/ exists but cannot access with provided credentials
smb://DS414/photo/ exists
smb://DS414/download/ exists
smb://DS414/ebook/ exists
smb://DS414/music/ exists
smb://DS414/debian/ exists but cannot access with provided credentials
smb://DS414/NetBackup/ exists but cannot access with provided credentials
smb://DS414/homes/ exists but cannot access with provided credentials
smb://DS414/猀爀挀ĀĀЀЀ猀瘀渀ĀĀԀԀ吀伀刀䴀ĀĀ਀਀琀爀愀渀猀昀攀爀琀ĀĀ؀؀瘀椀搀攀漀ᴀᴀ匀礀猀琀攀洀 搀攀昀愀甀氀琀 猀栀愀爀攀搀 昀漀氀搀攀爀܀܀瘀椀搀攀漀猀ĀĀԀԀ䤀倀䌀␀ༀༀ䤀
倀䌀 匀攀爀瘀椀挀攀 ⠀⤀ԀԀ栀漀洀攀᠀᠀䠀漀洀攀 搀椀爀攀挀琀漀爀礀 漀昀 洀攀搀椀愀ᔀ/ exists but not accessible
smb://DS414/fakenas/ exists but cannot access with provided credentials
```
- when SMBv2 is used: `smbcli 2 smb://DS414/ "" login password` 
[smb2-not_corrupted_listfiles.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/4289503/smb2-not_corrupted_listfiles.pcap.zip)
```
2020-03-04 21:05:45 INFO  smbcli:106 - Enabling SMB2
2020-03-04 21:05:45 INFO  smbcli:127 - smbFile is a server
2020-03-04 21:05:45 INFO  smbcli:138 - Current smbFile name = DS414/
smb://DS414/app/ exists but cannot access with provided credentials
smb://DS414/audiobook/ exists but cannot access with provided credentials
smb://DS414/backup/ exists but cannot access with provided credentials
smb://DS414/bd/ exists
smb://DS414/game/ exists but cannot access with provided credentials
smb://DS414/src/ exists but cannot access with provided credentials
smb://DS414/photo/ exists
smb://DS414/svn/ exists but cannot access with provided credentials
smb://DS414/videos/ exists but cannot access with provided credentials
smb://DS414/IPC$/ does not exist
smb://DS414/video/ exists
smb://DS414/home/ exists
smb://DS414/TORM/ exists but cannot access with provided credentials
smb://DS414/download/ exists
smb://DS414/ebook/ exists
smb://DS414/music/ exists
smb://DS414/debian/ exists but cannot access with provided credentials
smb://DS414/NetBackup/ exists but cannot access with provided credentials
smb://DS414/transfert/ exists but cannot access with provided credentials
smb://DS414/homes/ exists but cannot access with provided credentials
smb://DS414/fakenas/ exists but cannot access with provided credentials
```
Note that in the past I had some beta users of my application using jcifs-ng complaining about partial listing resported and this could be related (if they were using a SMBv1 capable only server).

Thanks for the support all the work accomplished so far!

**Comment by mbechler** [comment]
So the received DCE payloads are exactly the same in both cases. With SMB1 however this payload is split over two reads. So I think either
- there is (still) an error combining the data from the reads (could you check whether msgBuf is the same for both cases in jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcMessage)?)
- this is an alignment issue related to the alignment issue reported in #211

**Comment by courville** [comment]
@mberchler, thanks for the answer and sorry for the delay for responding.
Please find attached an hex dump of `msgBuf.getBuffer()` in `DcerpcHandle.sendrecv`:
[msgBuf.zip](https://github.com/AgNO3/jcifs-ng/files/4404195/msgBuf.zip)

You can witness with a difftool e.g. meld that the msgBuf are indeed shifted in some areas and are indeed not the same between SMB1 and SMB2 e.g.:
```
0065007200000000000400000000000000040000007300720063000000010000
00000000000100000000000000040000000000000004000000730076006E0000
000100000000000000010000000000000005000000000000000500000054004F
0052004D0000000000010000000000000001000000000000000A000000000000
000A0000007400720061006E0073006600650072007400000001000000000000
00010000000000000006000000000000000600000076006900640065006F0000
001D000000000000001D000000530079007300740065006D0020006400650066
00610075006C0074002000730068006100720065006400200066006F006C0064
00650072000000000007000000000000000700000076006900640065006F0073
0000000000010000000000000001000000000000000500000000000000050000
004900500043002400000000000F000000000000000F00000049005000430020
0053006500720076006900630065002000280029000000000005000000000000
000500000068006F006D0065000000000018000000000000001800000048006F
006D00650020006400690072006500630074006F007200790020006F00660020
00610064006D0069006E00000015000000000000000000000000000000000000
```
instead of
```
6500720000000000040000000000000004000000730072006300000001000000
000000000100000000000000040000000000000004000000730076006E000000
0100000000000000010000000000000005000000000000000500000054004F00
52004D0000000000010000000000000001000000000000000A00000000000000
0A0000007400720061006E007300660065007200740000000100000000000000
010000000000000006000000000000000600000076006900640065006F000000
1D000000000000001D000000530079007300740065006D002000640065006600
610075006C0074002000730068006100720065006400200066006F006C006400
650072000000000007000000000000000700000076006900640065006F007300
0000000001000000000000000100000000000000050000000000000005000000
4900500043002400000000000F000000000000000F0000004900500043002000
5300650072007600690063006500200028002900000000000500000000000000
0500000068006F006D0065000000000018000000000000001800000048006F00
6D00650020006400690072006500630074006F007200790020006F0066002000
610064006D0069006E0000001500000000000000000000000000000000000000
```

**Comment by mbechler** [comment]
I believe I figured out the issue. SMB1 pipe transaction repsonse initial recieves were not using the correct data length value, resulting in a zero byte being added between the first chunk and the following ones. Please try master.

**Comment by courville** [comment]
I do confirm that it solves my issue and makes jcifs-ng work with SMB1 only capable servers!
I will deploy in beta test this new library for my app users.
Thank you very much for your work and support.
