### ISSUE TITLE
Login failure when falling back to guest user when logging in as unknow user

### ISSUE THREAD

**Issue by michiel009** [AgNO3/jcifs-ng#212]
We have SMB3.0 share that falls back to a guest session if the user that is trying to log in does not exist. This is working fine when I mount the share for example with windows but in JCIFS-NG this login is denied:

```
09:26:33.186 [main] DEBUG jcifs.smb.SmbSessionImpl - sessionSetup: kramponline.com\sa_tms_DK_test
09:26:33.186 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is sdkskjknpapp01
09:26:33.186 [main] DEBUG jcifs.smb.NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.30, 1.3.6.1.4.1.311.2.2.10],mic=null]
09:26:33.202 [main] DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Sign key is 31B38DCC9522E8FBC82F8F54242FAB78
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Verify key is 57AEE79A259B6B7B5C21A71CF1B48025
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Seal key is 64B3B29A7F2CFD766B018DD45799D711
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Server seal key is 282AFA1E33CF0FFB7DD612AE5E52678A
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Digest BD49B7DE57CC99744106180FA36A9BEA
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Truncated BD49B7DE57CC9974
09:26:33.421 [main] DEBUG jcifs.smb.NtlmContext - Encrypted 57C77B588C6B6FA9
09:26:33.421 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list [1.3.6.1.4.1.311.2.2.10]
09:26:33.421 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list encoded 300C060A2B06010401823702020A
09:26:33.421 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list MIC 0100000057C77B588C6B6FA900000000
09:26:33.452 [main] DEBUG jcifs.smb.SmbSessionImpl - Session setup failed
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:566)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:558)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1206)
	at com.kramp.eai.fulfilment.shepherd.impl.cifs.service.CifsFileService.listFiles(CifsFileService.java:42)
	at com.kramp.eai.fulfilment.shepherd.impl.cifs.CifsConnectioTest.testList(CifsConnectioTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
```

I have traced the issue to this code in the SmbSessionImpl:
```
if ( response.isLoggedInAsGuest() && !anonymous) {
              throw new SmbAuthException(NtStatus.NT_STATUS_LOGON_FAILURE);
}
```

Have now forked the repo and added a configuration property that can allow for guest login and thereby skips this check. That fix is working for me while the owners of the share are checking their setup.

I am not sure if this is a bug or a feature to deny the guest session but if the flag to allow for a guest session is a good addition then I can create a PR.

I have attached the full console log from JCIFS NG and  wireshark exports for JCIFS NG Login and Windows login:
[Logs.zip](https://github.com/AgNO3/jcifs-ng/files/4358496/Logs.zip)

**Comment by mbechler** [comment]
This is in fact a security feature, as guest logins provide a easy way to disable SMB security features (Microsoft actually started to disallow guest logins in some windows editions recently, too). 
However, you should be able to explicitly request a guest login (use  ctx->withGuestCredentials() or just use the **GUEST** username).

**Comment by michiel009** [comment]
Thanks for your response, I have tried the guest credentials but then I get an access denied error. It seems that the share is accepting any user/pass combination with a guest session, except the guest user, that one is disabled. I will take this back to the owners of the file share.
