### ISSUE TITLE
Azure Storage file: getOwnerUser() failed to resolve SDs

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#218]
Hi,
For Azure Storage files (SMB300), creating a share is OK.  We hit an issue with SmbFile.getOwnerUser() trying to resolve SD with error is   'The system cannot find the file specified' with  \lsarpc

2020-04-22 00:24:34 DEBUG SmbTreeImpl:560 - Connection state was 0
2020-04-22 00:24:34 DEBUG SmbTreeImpl:591 - treeConnect: unc=\\10.0.1.4\IPC$,service=?????
2020-04-22 00:24:34 DEBUG SmbTreeImpl:695 - Secure negotiation does not apply
2020-04-22 00:24:34 DEBUG SmbTreeConnection:158 - Switching tree
2020-04-22 00:24:34 DEBUG SmbTreeConnection:160 - Acquired tree on switch SmbTree[share=IPC$,service=null,tid=5,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
2020-04-22 00:24:34 DEBUG SmbFile:681 - openUnshared: \lsarpc flags: 0 access: 20003 attrs: 80 options: 0
2020-04-22 00:24:34 DEBUG Smb2CreateRequest:460 - Opening lsarpc
2020-04-22 00:24:34 DEBUG Smb2CreateRequest:461 - Flags are 0000
2020-04-22 00:24:34 DEBUG SmbTransportImpl:1459 - Error code: 0xC0000034 for Smb2CreateRequest
2020-04-22 00:24:34 DEBUG SmbTreeConnection:331 - Not retrying
jcifs.smb.SmbException: The system cannot find the file specified.
        at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1461)
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1572)
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)

I have included the debug trace and pcap file.
Thanks for your help!
tvn
[Azure-issue.zip](https://github.com/AgNO3/jcifs-ng/files/4513333/Azure-issue.zip)

**Comment by mbechler** [comment]
It seems that the azure server simply does not provide a LSA service for SID lookup. Are you looking for a solution to do a successful name lookup, or is it juts the error that you want to avoid?

**Comment by thanh-vn** [comment]
Thanks for the response.  We are trying to just to avoid the error.

**Comment by thanh-vn** [comment]
Thanks, we think we will ignore the warning for the lsa lookup.
