### ISSUE TITLE
POM file and bounceycastle dependency

### ISSUE THREAD

**Issue by tawitt** [AgNO3/jcifs-ng#221]
In the bundle plugin, you tell it to import bouncey castle 1.54, but then have a dependency on 1.61.  This causes a bit of confusion on my osgi container that exports 1.60.  I get a MethodNotFound error.  I downloaded the source and simple made the versions match between the dependency and the bundle plug in and the error is gone.

**Comment by mbechler** [comment]
1.54 is specified as the minimum version (which to my knowledge should be compatible in the APIs we are using, but maybe I missed something). Do you maybe have multiple bouncycaste version so that some eariler version could be resolved? Or maybe a newer version that breaks compatiblity?
What is the exact MethodNotFound error?

**Comment by tawitt** [comment]
Our Karaf exports 1.60.  With the 1.54 minimum left in place, I get (this is 2.16 of cloudlibs fork):

ava.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1ObjectIdentifier.equals(Lorg/bouncycastle/asn1/ASN1Primitive;)Z
                at jcifs.spnego.NegTokenInit.parse(NegTokenInit.java:181)
                at jcifs.spnego.NegTokenInit.<init>(NegTokenInit.java:80)
                at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:185)
                at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:689)
                at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:536)
                at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
                at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
                at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
                at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
                at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
                at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
                at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
                at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
                at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
                at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:572)
                at jcifs.smb.SmbFile.exists(SmbFile.java:866)

Going backwards from there, 2.1.13 is the first cloudlibs I can use that I do not get the above error.


Thomas Witt
Sr. Integration Engineer

Argo Group US
8325 N. Allen Road
Suite B
Peoria, IL 61615
United States of America

Mailing Address
PO Box 469008
San Antonio, TX 78246

P       +1 309-690-3925<tel:+1%20309-690-3925>
C
+1 309-922-7778<tel:+1%20309-922-7778>
F       +1 (309) 397 4287<fax:+1%20(309)%20397%204287>
E
TWitt@argogroupus.com<mailto:TWitt@argogroupus.com>

[https://www.argosuretyportal.com/signatures/img/argo.png]<http://mysite.argogroup.com/personal/twitt/>
[https://www.argosuretyportal.com/signatures/img/linkdin.png]
[https://www.argosuretyportal.com/signatures/img/facebook.png]
[https://www.argosuretyportal.com/signatures/img/twitter.png]
[https://www.argosuretyportal.com/signatures/img/logo.png]

**Comment by mbechler** [comment]
Sorry for the delay. As far as I can tell that equals method was only added in bouncycastle 1.63 which suggests that jcifs has been built against a newer version than specified in pom.xml. Any chance this is the case?

Probably should bump the BC version at some point however.
