### ISSUE TITLE
SMB1 authentication issue on Huawei b715s-23s 4G router

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#225]
With https://github.com/nova-video-player/smbcli/blob/master/src/org/courville/smbcli.java test program on a Huawei B715S-23S 4G router including a SMB server I get an authentication issue with valid credentials. Same credentials are working with ancestral jcifs-1.3.19 code used in my Android application.
I am using latest jcifs-ng (https://github.com/AgNO3/jcifs-ng/commit/59c3c0a89f541966f38dc50dd43d5e2a315e4fa3) with SMBv1 only here via `smbcli 1 smb://ATP/ "" lurker password` which produces a SmbAuthException with the following logs:
```
2020-05-13 14:21:23 INFO  smbcli:128 - smbFile is a server
2020-05-13 14:21:23 INFO  smbcli:139 - Current smbFile name = ATP/
2020-05-13 14:21:23 DEBUG SmbTransportPoolImpl:96 - New transport connection Transport0[ATP<20>/192.168.1.1:445,state=0,signingEnforced=false,usage=1]
2020-05-13 14:21:23 DEBUG Transport:568 - Connecting Transport0
2020-05-13 14:21:23 DEBUG SmbTransportImpl:701 - Connecting in state 1 addr 192.168.1.1
2020-05-13 14:21:23 DEBUG SmbComNegotiateResponse:464 - Have initial token 602806062B0601050502A01E301CA00E300C060A2B06010401823702020AA30A3008A0061B044E4F4E45
2020-05-13 14:21:23 DEBUG SmbTransportImpl:725 - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@36bd3bd1
2020-05-13 14:21:23 DEBUG SmbComNegotiateResponse:259 - Signing not-enabled not-required
2020-05-13 14:21:23 DEBUG SmbComNegotiateResponse:295 - Unicode is enabled
2020-05-13 14:21:23 DEBUG SmbTransportImpl:735 - Signature negotiation enforced false (server false) enabled false (server false)
2020-05-13 14:21:23 DEBUG SmbTransportImpl:398 - Establishing new session SmbSession[credentials=lurker,targetHost=atp,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
2020-05-13 14:21:23 DEBUG SmbTreeImpl:560 - Connection state was 0
2020-05-13 14:21:23 DEBUG SmbTreeImpl:591 - treeConnect: unc=\\atp\IPC$,service=?????
2020-05-13 14:21:23 DEBUG SmbSessionImpl:471 - sessionSetup: lurker
2020-05-13 14:21:23 DEBUG SmbSessionImpl:839 - Extended security negotiated
2020-05-13 14:21:23 DEBUG SmbSessionImpl:933 - Remote host is atp
2020-05-13 14:21:23 DEBUG NtlmPasswordAuthenticator:187 - Have initial token NegTokenInit[flags=0,mechs=[1.3.6.1.4.1.311.2.2.10],mic=null]
2020-05-13 14:21:23 DEBUG SmbTransportImpl:1029 - Breaking on error SmbComSessionSetupAndXResponse[command=SMB_COM_SESSION_SETUP_ANDX,received=true,errorCode=More data is available.,flags=0x0088,flags2=0xC801,signSeq=0,tid=65535,pid=13599,uid=100,mid=1,wordCount=4,byteCount=169,andxCommand=0xFF,andxOffset=0,isLoggedInAsGuest=false,nativeOs=Unix,nativeLanMan=Samba 3.0.37,primaryDomain=]
2020-05-13 14:21:23 DEBUG NtlmContext:329 - Sign key is 6ED46BA43F16CFB72505799C5EAB998C
2020-05-13 14:21:23 DEBUG NtlmContext:330 - Verify key is 5898E8A617312F6B639F071300026B92
2020-05-13 14:21:23 DEBUG NtlmContext:336 - Seal key is 69A32ADA984026B0B3F8563E3B91E011
2020-05-13 14:21:23 DEBUG NtlmContext:343 - Server seal key is 866A1A83FFFB07C71FCD79488494CFAE
2020-05-13 14:21:23 DEBUG NtlmContext:388 - Digest D98B4367F77D4E10F209489731E39E31
2020-05-13 14:21:23 DEBUG NtlmContext:389 - Truncated D98B4367F77D4E10
2020-05-13 14:21:23 DEBUG NtlmContext:396 - Encrypted 0AAF24B15E8F54AA
2020-05-13 14:21:23 DEBUG SpnegoContext:320 - Out Mech list [1.3.6.1.4.1.311.2.2.10]
2020-05-13 14:21:23 DEBUG SpnegoContext:321 - Out Mech list encoded 300C060A2B06010401823702020A
2020-05-13 14:21:23 DEBUG SpnegoContext:322 - Out Mech list MIC 010000000AAF24B15E8F54AA00000000
2020-05-13 14:21:23 DEBUG SmbSessionImpl:490 - Session setup failed
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1380)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1577)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1543)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1507)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:1030)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:486)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:145)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:218)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1206)
	at org.courville.smbcli.main(smbcli.java:140)
```
Here is the corresponding pcap wireshark traces:
[huawei-jcifsng.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/4622600/huawei-jcifsng.pcap.zip)
Note that I am trying to deploy (for a certain time I know) my application (nova video player) with jcifs-ng and there are many users reporting issues with SMBv1 only servers. The Huawei router is one. I have reports of failures on WD MyCloud Home box (I do not have one thus I cannot provide logs yet).
For WD MyCloud issue on newer devices problem is reported there https://www.reddit.com/r/NovaVideoPlayer/comments/ghlh93/the_parameter_is_incorrect/

**Comment by courville** [comment]
OK took 5mn to adapt my test program to jcifs-1.3.19 to collect air traces to compare and with same parameters I get: `smb://ATP/ "" lurker password`:
```
2020-05-13 19:04:49 INFO  smbcli:81 - smbFile is a server
2020-05-13 19:04:49 INFO  smbcli:92 - Current smbFile name = ATP/
smb://ATP/IPC$/ exists
smb://ATP/lurker/ exists
````
with following pcap wireshark traces:
[huawei-oldJcifs.pcap.zip](https://github.com/AgNO3/jcifs-ng/files/4623527/huawei-oldJcifs.pcap.zip)

**Comment by courville** [comment]
In the [opensource](https://consumer.huawei.com/en/opensource/detail/?siteCode=worldwide&productCode=Gateways,WIFI%20Repeaters,Fixed%20Wireless%20Terminals,MediaQ,LTE%20Router,PLC&fileType=openSourceSoftware&pageSize=10&curPage=1) release of a similar Huawei router I see that they are using samba-3.0.37

**Comment by mbechler** [comment]
I also wasn't able to reproducte the issue in different older samba versions. Unfortunately, there are a lot of differences in the requests as the old jcifs is not even performing session key exchange, this will be very difficult to figure out without further information. 
Is there any chance to login on these devices, enable debugging logging and view the log? That would certainly be the easiest option.

**Comment by courville** [comment]
Yes there are ways for reflashing a custom firmware with ssh enabled for investigation cf. https://routeur4g.fr/discussions/discussion/1359/topic-firmware-flashage-outils-b715-b525-and-more/p15 It involves some hardware hacking. I will do it and report if there is no other way to progress.

**Comment by courville** [comment]
Well, now with latest changes as of https://github.com/AgNO3/jcifs-ng/commit/b582a4d816b7365e9cf8c411291078bc7dac413a now it works \o/
