### ISSUE TITLE
NullPointerException in ServerMessageBlock.writeString() on DFS-Share

### ISSUE THREAD

**Issue by johannes-martin** [AgNO3/jcifs-ng#24]
I'm in the process of porting an existing program running find unter jcifs 1.3.14 to jcifs-ng 2.0.5.

The program uses SmbFile.mkdirs() to create a directory before writing into this directory.

When using jcifs-ng with a DFS-Path as the target, I get a NullPointerException:
`java.lang.NullPointerException
        at jcifs.internal.smb1.ServerMessageBlock.writeString(ServerMessageBlock.java:1037)
        at jcifs.internal.smb1.ServerMessageBlock.writeString(ServerMessageBlock.java:1026)
        at jcifs.internal.smb1.trans2.Trans2QueryPathInformation.writeParametersWireFormat(Trans2QueryPathInformation.java:72)
        at jcifs.internal.smb1.trans.SmbComTransaction.nextElement(SmbComTransaction.java:235)
        at jcifs.smb.SmbTransportImpl.sendComTransaction(SmbTransportImpl.java:1537)
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1464)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:396)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:313)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.SmbFile.queryPath(SmbFile.java:772)
        at jcifs.smb.SmbFile.exists(SmbFile.java:825)
        at jcifs.smb.SmbFile.mkdirs(SmbFile.java:1687)
        at jcifs.smb.SmbFile.mkdirs(SmbFile.java:1691)
`

If I specify the file server path (instead of the DFS path), the program runs fine. It also works fine if I downgrade to 1.5.3.

Any ideas what I'm doing wrong?

Regards
  Johannes

**Comment by mbechler** [comment]
Somehow the path is not properly set up, definitely not your fault. 2.0 contains quite a few changes to the DFS code so I don't think I can figure this out just by looking at diffs. Can you get me a debug log for this. The exact access pattern (code?) may also be helpful in reproducing.

**Comment by johannes-martin** [comment]
I managed to write a small testcase that shows the problem. It's attached as a maven project. The zip also includes a trace log of running 

`test.sh "smb://domain;user:password/dfs/shares/claims/Batch/ENTW"`

[testcase.zip](https://github.com/AgNO3/jcifs-ng/files/1625209/testcase.zip)

**Comment by mbechler** [comment]
Sorry for the delay.
Looks like there two levels of DFS involved, yes? \myaddomain.intra.loc\dfs\shares\ -> \\dwisa038\SHARES$ -> ...

Handling that properly won't be much fun - but let me see whether I can make it that the old (quite inefficient - more or less doing a DFS lookup for each request) behavior is restored so that it at least works.

**Comment by johannes-martin** [comment]
Sorry, I'm not very familiar with DFS, so I can't tell you many details on the setup. We have two NETAPPs that are the actual file servers, one of them is dwisa038. myaddomain.intra.loc resolves two the IPs of the two active directory servers who also work as name space servers for DFS.

If there is anything I can do to help (without actually knowing anything about DFS), let me know...

**Comment by mbechler** [comment]
I'm still tied up with work right now but I hope I can look further into that soon. If it's the nested DFS problem I think I should be able to reproduce that in my testing environment.

One thing that might be interesting to see is whether a direct connection to
```\DWISA038\SHARES$\claims\Batch\```
works (bypassing the first layer of DFS) - a log for that might also help me in debugging further.

**Comment by mbechler** [comment]
Finally, I was able to reproduce the issue with a nested DFS link and I think the issue is fixed (in master so far, backport to the 2.0 branch will probably come tomorrow).
