### ISSUE TITLE
NullPointerExeption on isSigningEnforced

### ISSUE THREAD

**Issue by felixRajkumar** [AgNO3/jcifs-ng#248]
Hi, I am using jcifs-2.0.6. I am getting the following exception. It occurs randomly. Can someone throw some light on this.

[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: java.lang.NullPointerException|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTransportImpl.isSigningEnforced(SmbTransportImpl.java:298)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:134)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:194)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)|
[12:42:41:812]|[09-01-2020]|[SYSERR]|[INFO]|[470]: 	at jcifs.smb.SmbFile.exists(SmbFile.java:821)|

**Comment by mbechler** [comment]
Looks like #178 which may be already fixed in current versions.

**Comment by felixRajkumar** [comment]
Thanks @mbechler
