### ISSUE TITLE
No NTLM authentication when application is run after packaging with jpackage

### ISSUE THREAD

**Issue by matthjes** [AgNO3/jcifs-ng#254]
Hi,

I'm writing a small client with JavaFX that should connect to a SMB share and download some files. The client needs to be packaged with jpackage, so it's a modular project.

When I run the client from within my IDE everything works fine. The connection is made and the files downloaded. However, after packaging and creating a stand-alone application (under OSX), the download no longer works.

The interesting part is that when tracing is enabled, the outputs differn quite significantly.

Here is the output when running from within the IDE:
```
21:12:20.533 [TRACE  ] [pool-3-thread-1] jcifs.smb.DfsImpl - Resolving \<server>\sw-hrl-dm-i4\SW-HRL_ZIP-Archiv_04-11-2020_17-45-58.zip
21:12:20.533 [TRACE  ] [pool-3-thread-1] jcifs.smb.DfsImpl - No match for domain based root, checking standalone <server>
21:12:20.533 [TRACE  ] [pool-3-thread-1] jcifs.smb.DfsImpl - No match for \<server>\sw-hrl-dm-i4\sw-hrl_zip-archiv_04-11-2020_17-45-58.zip
21:12:20.534 [TRACE  ] [pool-3-thread-1] jcifs.netbios.NameServiceClientImpl - Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST]
21:12:20.537 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportPoolImpl - Exclusive false enforced signing false
21:12:20.548 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTransportPoolImpl - New transport connection Transport0[<server>/160.48.219.164:445,state=0,signingEnforced=false,usage=1]
21:12:20.548 [DEBUG  ] [pool-3-thread-1] jcifs.util.transport.Transport - Connecting Transport0
21:12:20.551 [DEBUG  ] [Transport0] jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 160.48.219.164
21:12:20.582 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=42610,uid=0,mid=0,wordCount=0,byteCount=34,wordCount=0,dialects=NT LM 0.12]
21:12:20.582 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - FF534D4272000000001803C8000000000000000000000000FFFF72A600000000002200024E54204C4D20302E31320002534D4220322E3F3F3F0002534D4220322E30303200
21:12:20.582 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - Wrote negotiate request
21:12:20.607 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - New data read: Transport0[<server>/160.48.219.164:445,state=1,signingEnforced=false,usage=1]
21:12:20.607 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - FE534D4240000000000000000000010001000000000000000000000000000000
21:12:20.607 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - Read negotiate response
21:12:20.610 [DEBUG  ] [Transport0] jcifs.smb.SmbTransportImpl - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@4754f333
21:12:20.610 [DEBUG  ] [Transport0] jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
21:12:20.611 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 2 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=2]
21:12:20.611 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 1 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=1]
21:12:20.611 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Currently 0 session(s) active for Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=1]
21:12:20.613 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 2 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=2]
21:12:20.614 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
21:12:20.617 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Acquire session 2 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=0,usage=2]
21:12:20.617 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - Acquire tree 1 SmbTree[share=SW-HRL-DM-I4,service=?????,tid=-1,inDfs=false,inDomainDfs=false,connectionState=0,usage=1]
21:12:20.617 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTreeConnection - doConnect: <server>
21:12:20.617 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Acquire session 3 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=0,usage=3]
21:12:20.617 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 3 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=3]
21:12:20.617 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - Connection state was 0
21:12:20.617 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - treeConnect: unc=\\<server>\SW-HRL-DM-I4,service=?????
21:12:20.625 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 4 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=4]
21:12:20.625 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 5 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=5]
21:12:20.625 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - sessionSetup: <username>
21:12:20.625 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Remote host is <server>
21:12:20.645 [DEBUG  ] [pool-3-thread-1] jcifs.smb.NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2, 1.3.6.1.4.1.311.2.2.10],mic=null]
21:12:20.648 [TRACE  ] [pool-3-thread-1] jcifs.smb.NtlmContext - Type1Message[suppliedDomain=,suppliedWorkstation=null,flags=0x62088215]
21:12:20.649 [TRACE  ] [pool-3-thread-1] jcifs.smb.NtlmContext - 4E544C4D53535000010000001582086200000000280000000000000028000000060100000000000F
21:12:20.650 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0
21:12:20.651 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - jcifs.internal.smb2.session.Smb2SessionSetupRequest costs 1 avail 1 (Transport0)
21:12:20.651 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Request credits 512
21:12:20.651 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Sending command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0
```
Near the end you can see a log output from the NtlmPasswordAuthenticator.

Now here is the output when the client is run as a stand-alone application:
```
21:19:13.056 [TRACE  ] [pool-3-thread-1] jcifs.smb.DfsImpl - Resolving \<server>\sw-hrl-dm-i4\SW-HRL_ZIP-Archiv_04-11-2020_17-45-58.zip
21:19:13.056 [TRACE  ] [pool-3-thread-1] jcifs.smb.DfsImpl - No match for domain based root, checking standalone <server>
21:19:13.056 [TRACE  ] [pool-3-thread-1] jcifs.smb.DfsImpl - No match for \<server>\sw-hrl-dm-i4\sw-hrl_zip-archiv_04-11-2020_17-45-58.zip
21:19:13.056 [TRACE  ] [pool-3-thread-1] jcifs.netbios.NameServiceClientImpl - Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST]
21:19:13.059 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportPoolImpl - Exclusive false enforced signing false
21:19:13.066 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTransportPoolImpl - New transport connection Transport0[<server>/160.48.219.164:445,state=0,signingEnforced=false,usage=1]
21:19:13.066 [DEBUG  ] [pool-3-thread-1] jcifs.util.transport.Transport - Connecting Transport0
21:19:13.066 [DEBUG  ] [Transport0] jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 160.48.219.164
21:19:13.097 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=65535,pid=29817,uid=0,mid=0,wordCount=0,byteCount=34,wordCount=0,dialects=NT LM 0.12]
21:19:13.098 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - FF534D4272000000001803C8000000000000000000000000FFFF797400000000002200024E54204C4D20302E31320002534D4220322E3F3F3F0002534D4220322E30303200
21:19:13.098 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - Wrote negotiate request
21:19:13.124 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - New data read: Transport0[<server>/160.48.219.164:445,state=1,signingEnforced=false,usage=1]
21:19:13.125 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - FE534D4240000000000000000000010001000000000000000000000000000000
21:19:13.125 [TRACE  ] [Transport0] jcifs.smb.SmbTransportImpl - Read negotiate response
21:19:13.128 [DEBUG  ] [Transport0] jcifs.smb.SmbTransportImpl - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@152ef036
21:19:13.129 [DEBUG  ] [Transport0] jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
21:19:13.129 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 2 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=2]
21:19:13.129 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 1 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=1]
21:19:13.129 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Currently 0 session(s) active for Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=1]
21:19:13.132 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 2 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=2]
21:19:13.132 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
21:19:13.134 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Acquire session 2 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=0,usage=2]
21:19:13.134 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - Acquire tree 1 SmbTree[share=SW-HRL-DM-I4,service=?????,tid=-1,inDfs=false,inDomainDfs=false,connectionState=0,usage=1]
21:19:13.135 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTreeConnection - doConnect: <server>
21:19:13.135 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Acquire session 3 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=0,usage=3]
21:19:13.135 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 3 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=3]
21:19:13.135 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - Connection state was 0
21:19:13.135 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - treeConnect: unc=\\<server>\SW-HRL-DM-I4,service=?????
21:19:13.135 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 4 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=4]
21:19:13.135 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Acquire transport 5 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=5]
21:19:13.135 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - sessionSetup: <user>
21:19:13.136 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Remote host is <server>
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 4 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=4]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 3 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=3]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 2 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=2]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Release session 2 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=1,usage=2]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - Release tree 0 SmbTree[share=SW-HRL-DM-I4,service=?????,tid=-1,inDfs=false,inDomainDfs=false,connectionState=1,usage=0]
21:19:13.137 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbTreeImpl - Usage dropped to zero, release session
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Release session 1 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=1,usage=1]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Release session 0 SmbSession[credentials=<user>,targetHost=<server>,targetDomain=null,uid=0,connectionState=1,usage=0]
21:19:13.137 [DEBUG  ] [pool-3-thread-1] jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=2]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 1 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=1]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Release transport 0 Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=0]
21:19:13.137 [TRACE  ] [pool-3-thread-1] jcifs.util.transport.Transport - Transport usage dropped to zero Transport0[<server>/160.48.219.164:445,state=3,signingEnforced=false,usage=0]
21:19:14.132 [TRACE  ] [Transport0] jcifs.util.transport.Transport - Socket timeout during peekKey
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
```
There is no log output from the NtlmPasswordAuthenticator and the applications receives a timeout.

I have no idea why there is a difference between running the application within the IDE and as a stand-alone. I just assume that somehow the module generation is faulty.

**Comment by matthjes** [comment]
When I debug the application I can see that something weird is going on:

When running as a standalone application it never hits the following breakpoint:
```
    public NegTokenInit ( byte[] token ) throws IOException {
X        parse(token);
    }
```

In `NtlmPasswordAuthenticator.createContext()` the program flow is fine until the  `NegTokenInit` constructor is called. It then jumps to the `finally` block in `SmbSessionImpl.sessionSetup()`.

Here is the respective code in `NtlmPasswordAuthenticator.createContext()`:
```
        try {
            if ( initialToken != null && initialToken.length > 0 ) {
X                NegTokenInit tok = new NegTokenInit(initialToken);
                if ( log.isDebugEnabled() ) {
                    log.debug("Have initial token " + tok);
                }
                if ( tok.getMechanisms() != null ) {
                    Set<ASN1ObjectIdentifier> mechs = new HashSet<>(Arrays.asList(tok.getMechanisms()));
                    if ( !mechs.contains(NtlmContext.NTLMSSP_OID) ) {
                        throw new SmbUnsupportedOperationException("Server does not support NTLM authentication");
                    }
                }
            }
        }
```

Looks like this goes wrong:
```
    private static final ASN1ObjectIdentifier SPNEGO_OID = new ASN1ObjectIdentifier(SpnegoConstants.SPNEGO_MECHANISM);
```
Debugging through the application, after hitting the breakpoint where the `NegTokenInit` constructor is called the debugger jumps to the line above. The next step is then the `finally` block, the constructor is not called.

**Comment by matthjes** [comment]
This is the problem:
```
java.lang.IllegalAccessError: class jcifs.spnego.NegTokenInit (in module com.bmw.swhrl.merged.module) cannot access class org.bouncycastle.asn1.ASN1ObjectIdentifier (in module org.bouncycastle.provider) because module com.bmw.swhrl.merged.module does not read module org.bouncycastle.provider
```

No I just have to solve it...

**Comment by mbechler** [comment]
So I take it this is just an issue with your module configuration which you were able to resolve?
There really should not be much magic going on except for loading the GSS-API/Kerberos implementation.

**Comment by matthjes** [comment]
Hi,
Yes, I'm still having a hard time grasping this module system. 

Well, in this case it turned out I should have catched `Throwable` instead of `Exception` inside my thread, this is why I didn't see any exceptions in the log file...the thread just died silently. After this it was just adding `--add-reads` as a JVM option inside my build file that fixed this and now it's working.
