### ISSUE TITLE
SMB2 Multi-Protocol negotitation fails for 2.02 only servers

### ISSUE THREAD

**Issue by casolorz** [AgNO3/jcifs-ng#26]
I've started using this library and I have most of what I need working but it works with against SMB on my Windows machine but it does not work against my Synology NAS. I see other Android apps can work with the Synology NAS just fine, so I'm wondering if there is something wrong with the way I implemented my code. So my question is, is there a sample project I can test my Synology NAS with? 

The error I get is:

```
01-19 14:22:01.641 24408-25061/mypackage W/SmbTreeConnection: Referral failed, trying next
                                                                               jcifs.smb.SmbException: Failed to connect: nas/192.168.86.89
                                                                                   at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:673)
                                                                                   at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
                                                                                   at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
                                                                                   at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:557)
                                                                                   at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481)
                                                                                   at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:457)
                                                                                   at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:418)
                                                                                   at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:543)
                                                                                   at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:219)
                                                                                   at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
                                                                                   at jcifs.smb.SmbFile.listFiles(SmbFile.java:1177)
                                                                                   at mypackage.servers.smb.SMBServer$2.subscribe(SMBServer.java:78)
                                                                                   at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                                   at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                                   at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                                   at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                                   at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                                   at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                   at java.lang.Thread.run(Thread.java:764)
                                                                                Caused by: jcifs.util.transport.TransportException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean jcifs.internal.SmbNegotiationResponse.isValid(jcifs.CIFSContext, jcifs.internal.SmbNegotiationRequest)' on a null object reference
                                                                                   at jcifs.util.transport.Transport.run(Transport.java:752)
                                                                                   at java.lang.Thread.run(Thread.java:764) 
                                                                                Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean jcifs.internal.SmbNegotiationResponse.isValid(jcifs.CIFSContext, jcifs.internal.SmbNegotiationRequest)' on a null object reference
                                                                                   at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:708)
                                                                                   at jcifs.util.transport.Transport.run(Transport.java:725)
                                                                                   at java.lang.Thread.run(Thread.java:764) 
01-19 14:22:01.647 24408-25061/mypackage W/SMBServer: jcifs.smb.SmbException: Failed to connect: solonas/192.168.86.89
                                                                           at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:673)
                                                                           at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
                                                                           at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
                                                                           at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:557)
                                                                           at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481)
                                                                           at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:457)
                                                                           at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:418)
                                                                           at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:543)
                                                                           at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:219)
                                                                           at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
                                                                           at jcifs.smb.SmbFile.listFiles(SmbFile.java:1177)
                                                                           at mypackage.servers.smb.SMBServer$2.subscribe(SMBServer.java:78)
                                                                           at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                           at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                           at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                           at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                           at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                           at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                           at java.lang.Thread.run(Thread.java:764)
                                                                        Caused by: jcifs.util.transport.TransportException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean jcifs.internal.SmbNegotiationResponse.isValid(jcifs.CIFSContext, jcifs.internal.SmbNegotiationRequest)' on a null object reference
                                                                           at jcifs.util.transport.Transport.run(Transport.java:752)
                                                                           at java.lang.Thread.run(Thread.java:764) 
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean jcifs.internal.SmbNegotiationResponse.isValid(jcifs.CIFSContext, jcifs.internal.SmbNegotiationRequest)' on a null object reference
                                                                           at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:708)
                                                                           at jcifs.util.transport.Transport.run(Transport.java:725)
                                                                           at java.lang.Thread.run(Thread.java:764) 
```

Thanks.

**Comment by mbechler** [comment]
As noted in #23 there currently is no proper example code. I would suggest looking at the test cases. 

Your stacktraces hower don't look like you are doing anything wrong but more like a bug. I added a more meaningful exception but actually we should not get there. Can you get me more details (debug log, packet trace) for the connection attempt.

**Comment by casolorz** [comment]
I'll try to get the debug log on Monday. I see on stackoverflow a few examples of how to set the log level, hopefully one will work.

jcifs.Config.setProperty("jcifs.util.loglevel", "3")
or
LogStream.setLevel(10);

**Comment by mbechler** [comment]
These both are no longer valid, jcifs-ng uses slf4j. Actual configuration depends on what slf4j backend you use. If you use log4j1 you can have a look at https://github.com/AgNO3/jcifs-ng/blob/master/src/test/resources/log4j.properties for a configuration (that goes to the classpath root directory) - and set `log4j.logger.jcifs: DEBUG`.

**Comment by casolorz** [comment]
So I finally found a way to enable those logs, at least some of them. On Android it is easier to use this version of slf4j https://github.com/mvysny/slf4j-handroid

Here are the logs I got, I might need to enable more logs than just that?  There are also logs in there from a different library I use that uses slf4j, haven't figured out how to make it only log for jcifs. Maybe I'll just disable that other library. 

```
01-20 16:50:01.093 12989-13694/mypackage D/slf4j:SingletonContext: Initializing singleton context
01-20 16:50:01.166 12989-13694/mypackage V/slf4j:NameServiceClien*: Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST]
01-20 16:50:01.184 12989-13694/mypackage D/slf4j:SmbResourceLocat*: Share is IPC null
01-20 16:50:01.184 12989-13694/mypackage V/slf4j:NameServiceClien*: Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST]
01-20 16:50:01.186 12989-13694/mypackage V/slf4j:SmbTransportPool*: Exclusive false enforced signing true
01-20 16:50:01.189 12989-13694/mypackage D/slf4j:SmbTransportPool*: New transport connection Transport0[nas/192.168.86.89:445,state=0,signingEnforced=true,usage=1]
01-20 16:50:01.189 12989-13694/mypackage D/slf4j:Transport: Connecting Transport0
01-20 16:50:01.191 12989-13697/mypackage D/slf4j:SmbTransportImpl: Connecting in state 1 addr 192.168.86.89
01-20 16:50:01.203 12989-13697/mypackage V/slf4j:SmbTransportImpl: SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=0,pid=32622,uid=0,mid=0,wordCount=0,byteCount=34,wordCount=0,dialects=NT LM 0.12]
01-20 16:50:01.204 12989-13697/mypackage V/slf4j:SmbTransportImpl: FF534D4272000000001803C800000000000000000000000000006E7F00000000002200024E54204C4D20302E31320002534D4220322E3F3F3F0002534D4220322E30303200
01-20 16:50:01.205 12989-13697/mypackage V/slf4j:SmbTransportImpl: Wrote negotiate request
01-20 16:50:04.805 12989-13134/mypackage D/slf4j:AsyncHttpConnect*: while open=true more=false progress=true
01-20 16:50:04.807 12989-13134/mypackage D/slf4j:AsyncHttpConnect*: exchange HttpContentExchange@ddfeee6=GET//192.168.86.26:8088/description#CONTENT(41ms)->COMPLETED(34139ms)sent=34541ms on AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=4,h=-1,b=-1,c=-1} p=HttpParser{s=7,l=3,c=700}
01-20 16:50:04.807 12989-13137/mypackage D/slf4j:AbstractConnecti*: onIdleExpired 20000ms AsyncHttpConnection@9ccd5bb 192.168.86.47:58645 g=HttpGenerator{s=0,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=0,c=-3} SCEP@ef82ad8{l(null)<->r(::/:::38841),s=0,open=false,ishut=true,oshut=true,rb=false,wb=false,w=true,i=1-}-{AsyncHttpConnection@9ccd5bb 192.168.86.47:58645 g=HttpGenerator{s=0,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=0,c=-3}}
01-20 16:50:04.808 12989-13137/mypackage D/slf4j:ChannelEndPoint: close SCEP@ef82ad8{l(null)<->r(::/:::38841),s=0,open=false,ishut=true,oshut=true,rb=false,wb=false,w=true,i=1-}-{AsyncHttpConnection@9ccd5bb 192.168.86.47:58645 g=HttpGenerator{s=0,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=0,c=-3}}
01-20 16:50:04.809 12989-13134/mypackage D/slf4j:ChannelEndPoint: ishut SCEP@9e795d{l(/192.168.86.26:8088)<->r(/192.168.86.53:37859),s=1,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=1r}-{AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=4,h=-1,b=-1,c=-1} p=HttpParser{s=7,l=3,c=700}}
01-20 16:50:04.810 12989-13134/mypackage D/slf4j:HttpParser: filled -1/0
01-20 16:50:04.813 12989-13134/mypackage D/slf4j:AsyncHttpConnect*: finally HttpContentExchange@ddfeee6=GET//192.168.86.26:8088/description#CONTENT(41ms)->COMPLETED(34144ms)sent=34546ms on AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=4,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=3,c=700} progress=false SCEP@9e795d{l(/192.168.86.26:8088)<->r(/192.168.86.53:37859),s=1,open=true,ishut=true,oshut=false,rb=false,wb=false,w=true,i=1r}-{AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=4,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=3,c=700}}
01-20 16:50:04.818 12989-13134/mypackage D/slf4j:ChannelEndPoint: oshut SCEP@9e795d{l(/192.168.86.26:8088)<->r(/192.168.86.53:37859),s=1,open=true,ishut=true,oshut=false,rb=false,wb=false,w=true,i=1r}-{AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=4,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=0,c=-3}}
01-20 16:50:04.820 12989-13134/mypackage D/slf4j:ChannelEndPoint: close SCEP@9e795d{l(/192.168.86.26:8088)<->r(/192.168.86.53:37859),s=1,open=true,ishut=true,oshut=true,rb=false,wb=false,w=true,i=1r}-{AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=4,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=0,c=-3}}
01-20 16:50:04.827 12989-13134/mypackage D/slf4j:AsyncHttpConnect*: unhandle null on SCEP@9e795d{l(null)<->r(::/:::37859),s=1,open=false,ishut=true,oshut=true,rb=false,wb=false,w=true,i=1-}-{AsyncHttpConnection@51aa88 192.168.86.26:8088 g=HttpGenerator{s=0,h=-1,b=-1,c=-1} p=HttpParser{s=0,l=0,c=-3}}
01-20 16:50:05.879 12989-13697/mypackage V/slf4j:SmbTransportImpl: New data read: Transport0[nas/192.168.86.89:445,state=1,signingEnforced=true,usage=1]
01-20 16:50:05.880 12989-13697/mypackage V/slf4j:SmbTransportImpl: FE534D4240000000000000000000010001000000000000000000000000000000
01-20 16:50:05.880 12989-13697/mypackage V/slf4j:SmbTransportImpl: Read negotiate response
01-20 16:50:05.887 12989-13697/mypackage D/slf4j:SmbTransportImpl: Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@45644f9
01-20 16:50:05.888 12989-13694/mypackage D/slf4j:Transport: Interrupting transport thread
01-20 16:50:05.888 12989-13694/mypackage D/slf4j:Transport: Joining transport thread
01-20 16:50:05.892 12989-13694/mypackage D/slf4j:Transport: Joined transport thread
01-20 16:50:05.893 12989-13694/mypackage D/slf4j:SmbTransportPool*: Removing transport connection Transport0[nas/192.168.86.89:445,state=4,signingEnforced=true,usage=1] (55929918)
01-20 16:50:05.893 12989-13694/mypackage V/slf4j:Transport: Release transport 0 Transport0[nas/192.168.86.89:445,state=4,signingEnforced=true,usage=0]
01-20 16:50:05.894 12989-13694/mypackage V/slf4j:Transport: Transport usage dropped to zero Transport0[nas/192.168.86.89:445,state=4,signingEnforced=true,usage=0]
```

**Comment by mbechler** [comment]
I think the commit should fix that issue.

**Comment by casolorz** [comment]
I checked out that commit and rebuilt but still got an exception. I did noticed something new on the exception  that I don't think was there before:
```
   Caused by: jcifs.util.transport.TransportException: java.lang.ClassCastException: jcifs.internal.smb1.com.SmbComNegotiate cannot be cast to jcifs.internal.smb2.nego.Smb2NegotiateRequest
                                                                                         at jcifs.util.transport.Transport.run(Transport.java:752)
                                                                                         at java.lang.Thread.run(Thread.java:764) 
                                                                                      Caused by: java.lang.ClassCastException: jcifs.internal.smb1.com.SmbComNegotiate cannot be cast to jcifs.internal.smb2.nego.Smb2NegotiateRequest
                                                                                         at jcifs.internal.smb2.nego.Smb2NegotiateResponse.isValid(Smb2NegotiateResponse.java:255)
                                                                                         at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:713)
                                                                                         at jcifs.util.transport.Transport.run(Transport.java:725)
                                                                                         at java.lang.Thread.run(Thread.java:764) 

```

Here is the full log:

```
01-28 13:39:55.155 29535-31905/mypackage V/slf4j:NameServiceClien*: Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST]
01-28 13:39:55.164 29535-31905/mypackage D/slf4j:SmbResourceLocat*: Share is IPC null
01-28 13:39:55.165 29535-31905/mypackage V/slf4j:NameServiceClien*: Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST]
01-28 13:39:55.166 29535-31905/mypackage V/slf4j:SmbTransportPool*: Exclusive false enforced signing true
01-28 13:39:55.166 29535-31905/mypackage D/slf4j:SmbTransportPool*: New transport connection Transport1[mynas/192.168.86.89:445,state=0,signingEnforced=true,usage=1]
01-28 13:39:55.166 29535-31905/mypackage D/slf4j:Transport: Connecting Transport1
01-28 13:39:55.169 29535-31907/mypackage D/slf4j:SmbTransportImpl: Connecting in state 1 addr 192.168.86.89
01-28 13:39:55.178 29535-31907/mypackage V/slf4j:SmbTransportImpl: SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=0,pid=29362,uid=0,mid=0,wordCount=0,byteCount=34,wordCount=0,dialects=NT LM 0.12]
01-28 13:39:55.178 29535-31907/mypackage V/slf4j:SmbTransportImpl: FF534D4272000000001803C80000000000000000000000000000B27200000000002200024E54204C4D20302E31320002534D4220322E3F3F3F0002534D4220322E30303200
01-28 13:39:55.179 29535-31907/mypackage V/slf4j:SmbTransportImpl: Wrote negotiate request
01-28 13:40:02.579 29535-31907/mypackage V/slf4j:SmbTransportImpl: New data read: Transport1[mynas/192.168.86.89:445,state=1,signingEnforced=true,usage=1]
01-28 13:40:02.582 29535-31907/mypackage V/slf4j:SmbTransportImpl: FE534D4240000000000000000000010001000000000000000000000000000000
01-28 13:40:02.584 29535-31907/mypackage V/slf4j:SmbTransportImpl: Read negotiate response
01-28 13:40:02.597 29535-31907/mypackage D/slf4j:SmbTransportImpl: Negotiation response on Transport1 :jcifs.internal.SmbNegotiation@2c58b36
01-28 13:40:02.601 29535-31905/mypackage D/slf4j:Transport: Interrupting transport thread
01-28 13:40:02.601 29535-31905/mypackage D/slf4j:Transport: Joining transport thread
01-28 13:40:02.602 29535-31905/mypackage D/slf4j:Transport: Joined transport thread
01-28 13:40:02.603 29535-31905/mypackage D/slf4j:SmbTransportPool*: Removing transport connection Transport1[mynas/192.168.86.89:445,state=4,signingEnforced=true,usage=1] (4909623)
01-28 13:40:02.603 29535-31905/mypackage V/slf4j:Transport: Release transport 0 Transport1[mynas/192.168.86.89:445,state=4,signingEnforced=true,usage=0]
01-28 13:40:02.604 29535-31905/mypackage V/slf4j:Transport: Transport usage dropped to zero Transport1[mynas/192.168.86.89:445,state=4,signingEnforced=true,usage=0]
01-28 13:40:02.609 29535-31905/mypackage W/slf4j:SmbTreeConnection: Referral failed, trying next
                                                                                     jcifs.smb.SmbException: Failed to connect: mynas/192.168.86.89
                                                                                         at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:674)
                                                                                         at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
                                                                                         at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
                                                                                         at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:557)
                                                                                         at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481)
                                                                                         at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:143)
                                                                                         at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:216)
                                                                                         at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
                                                                                         at jcifs.smb.SmbFile.listFiles(SmbFile.java:1177)
                                                                                         at mypackage.servers.smb.SMBServer$2.subscribe(SMBServer.java:89)
                                                                                         at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                                         at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                                         at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                                         at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                         at java.lang.Thread.run(Thread.java:764)
                                                                                      Caused by: jcifs.util.transport.TransportException: java.lang.ClassCastException: jcifs.internal.smb1.com.SmbComNegotiate cannot be cast to jcifs.internal.smb2.nego.Smb2NegotiateRequest
                                                                                         at jcifs.util.transport.Transport.run(Transport.java:752)
                                                                                         at java.lang.Thread.run(Thread.java:764) 
                                                                                      Caused by: java.lang.ClassCastException: jcifs.internal.smb1.com.SmbComNegotiate cannot be cast to jcifs.internal.smb2.nego.Smb2NegotiateRequest
                                                                                         at jcifs.internal.smb2.nego.Smb2NegotiateResponse.isValid(Smb2NegotiateResponse.java:255)
                                                                                         at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:713)
                                                                                         at jcifs.util.transport.Transport.run(Transport.java:725)
                                                                                         at java.lang.Thread.run(Thread.java:764) 

```

**Comment by mbechler** [comment]
On second thought I also don't think that the change was correct protocol-wise. Will look into that again.

**Comment by mbechler** [comment]
I think that patch should do the trick. The issue should only have been present when to server does only support SMB 2.02 and no higher version.

**Comment by casolorz** [comment]
Checked out commit d2d7fc8efc93a4a3f227dca609b09377fe514725 and got this error. 

```
02-06 11:10:05.871 7006-7430/mypackage V/slf4j:SmbTransportPool*: Exclusive false enforced signing true
02-06 11:10:05.875 7006-7430/mypackage D/slf4j:SmbTransportPool*: New transport connection Transport0[mynas/192.168.86.89:445,state=0,signingEnforced=true,usage=1]
02-06 11:10:05.875 7006-7430/mypackage D/slf4j:Transport: Connecting Transport0
02-06 11:10:05.877 7006-7433/mypackage D/slf4j:SmbTransportImpl: Connecting in state 1 addr 192.168.86.89
02-06 11:10:05.888 7006-7433/mypackage V/slf4j:SmbTransportImpl: SmbComNegotiate[command=SMB_COM_NEGOTIATE,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=0,pid=13628,uid=0,mid=0,wordCount=0,byteCount=12,wordCount=0,dialects=NT LM 0.12]
02-06 11:10:05.889 7006-7433/mypackage V/slf4j:SmbTransportImpl: FF534D4272000000001803C800000000000000000000000000003C3500000000000C00024E54204C4D20302E313200
02-06 11:10:05.890 7006-7433/mypackage V/slf4j:SmbTransportImpl: Wrote negotiate request
02-06 11:10:08.370 7006-7433/mypackage V/slf4j:SmbTransportImpl: New data read: Transport0[mynas/192.168.86.89:445,state=1,signingEnforced=true,usage=1]
02-06 11:10:08.370 7006-7433/mypackage V/slf4j:SmbTransportImpl: FF534D4272000000008803C800000000000000000000000000003C3500000000
02-06 11:10:08.371 7006-7433/mypackage V/slf4j:SmbTransportImpl: Read negotiate response
02-06 11:10:08.372 7006-7433/mypackage D/slf4j:SmbComNegotiateR*: Have initial token 604806062B0601050502A03E303CA00E300C060A2B06010401823702020AA32A3028A0261B246E6F745F646566696E65645F696E5F5246433431373840706C656173655F69676E6F7265
02-06 11:10:08.373 7006-7433/mypackage V/slf4j:ServerMessageBlo*: byteCount=90 but readBytesWireFormat returned 16
02-06 11:10:08.374 7006-7433/mypackage V/slf4j:SmbTransportImpl: SmbComNegotiateResponse[command=SMB_COM_NEGOTIATE,received=true,errorCode=0,flags=0x0088,flags2=0xC803,signSeq=0,tid=0,pid=13628,uid=0,mid=0,wordCount=17,byteCount=90,wordCount=17,dialectIndex=0,securityMode=0x3,security=user,encryptedPasswords=true,maxMpxCount=50,maxNumberVcs=1,maxBufferSize=16644,maxRawSize=65536,sessionKey=0x000024FE,capabilities=0x8080F3FD,serverTime=Tue Feb 06 11:10:08 CST 2018,serverTimeZone=360,encryptionKeyLength=74,byteCount=90,oemDomainName=]
02-06 11:10:08.375 7006-7433/mypackage V/slf4j:SmbTransportImpl: FF534D4272000000008803C800000000000000000000000000003C3500000000110000033200010004410000000001
02-06 11:10:08.377 7006-7433/mypackage D/slf4j:SmbTransportImpl: Negotiation response on Transport0 :SmbComNegotiateResponse[command=SMB_COM_NEGOTIATE,received=true,errorCode=0,flags=0x0088,flags2=0xC803,signSeq=0,tid=0,pid=13628,uid=0,mid=0,wordCount=17,byteCount=90,wordCount=17,dialectIndex=0,securityMode=0x3,security=user,encryptedPasswords=true,maxMpxCount=50,maxNumberVcs=1,maxBufferSize=16644,maxRawSize=65536,sessionKey=0x000024FE,capabilities=0x8080F3FD,serverTime=Tue Feb 06 11:10:08 CST 2018,serverTimeZone=360,encryptionKeyLength=74,byteCount=90,oemDomainName=]
02-06 11:10:08.377 7006-7433/mypackage E/slf4j:SmbComNegotiateR*: Signatures are required but the server does not support them
02-06 11:10:08.378 7006-7430/mypackage D/slf4j:Transport: Interrupting transport thread
02-06 11:10:08.378 7006-7430/mypackage D/slf4j:Transport: Joining transport thread
02-06 11:10:08.378 7006-7430/mypackage D/slf4j:Transport: Joined transport thread
02-06 11:10:08.379 7006-7430/mypackage D/slf4j:SmbTransportPool*: Removing transport connection Transport0[mynas/192.168.86.89:445,state=4,signingEnforced=true,usage=1] (102779096)
02-06 11:10:08.379 7006-7430/mypackage V/slf4j:Transport: Release transport 0 Transport0[mynas/192.168.86.89:445,state=4,signingEnforced=true,usage=0]
02-06 11:10:08.379 7006-7430/mypackage V/slf4j:Transport: Transport usage dropped to zero Transport0[mynas/192.168.86.89:445,state=4,signingEnforced=true,usage=0]
02-06 11:10:08.381 7006-7430/mypackage W/slf4j:SmbTreeConnection: Referral failed, trying next
                                                                                   jcifs.smb.SmbException: Failed to connect: mynas/192.168.86.89
                                                                                       at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:651)
                                                                                       at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
                                                                                       at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
                                                                                       at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:557)
                                                                                       at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481)
                                                                                       at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:143)
                                                                                       at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:216)
                                                                                       at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
                                                                                       at jcifs.smb.SmbFile.listFiles(SmbFile.java:1177)
                                                                                       at mypackage.servers.smb.SMBServer$2.subscribe(SMBServer.java:89)
                                                                                       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                                       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                                       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                       at java.lang.Thread.run(Thread.java:764)
                                                                                    Caused by: jcifs.util.transport.TransportException: jcifs.smb.SmbException: This client is not compatible with the server.
                                                                                       at jcifs.util.transport.Transport.run(Transport.java:752)
                                                                                       at java.lang.Thread.run(Thread.java:764) 
                                                                                    Caused by: jcifs.smb.SmbException: This client is not compatible with the server.
                                                                                       at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:687)
                                                                                       at jcifs.util.transport.Transport.run(Transport.java:725)
                                                                                       at java.lang.Thread.run(Thread.java:764) 

```

**Comment by mbechler** [comment]
The "This client is not compatible with the server." should be the same fundamental issue as #40. Taking this there.
