### ISSUE TITLE
Access is denied while access window file share

### ISSUE THREAD

**Issue by suneelsharma86** [AgNO3/jcifs-ng#260]
I am trying to access files on window network share with service user which has full access but getting access denied error using jcifs-ng latest library.

Window Share:  Windows Server 2016
Trying to access from eclipse on window 10
I am able to perform all action from laptop. 
Code:
               BaseContext baseCxt = null;
		Properties jcifsProperties  = new Properties();
		jcifsProperties.setProperty("jcifs.smb.client.minVersion", "SMB202");
		jcifsProperties.setProperty("jcifs.smb.client.maxVersion","SMB202");
		jcifsProperties.setProperty("jcifs.smb.client.responseTimeout", "120000");
		jcifsProperties.setProperty("jcifs.smb.client.soTimeout", "140000");
		
		Configuration config = new PropertyConfiguration(jcifsProperties);
        NtlmPasswordAuthenticator auth = new NtlmPasswordAuthenticator(null, userName, password);
        baseCxt = new BaseContext(config);
        CIFSContext authed1 = baseCxt.withCredentials(auth);
        SmbFile f = new SmbFile("smb:////hostname/sharename/path/", authed1); 	 
        if(f.exists())
    			{
    				System.out.println("floder exists");
    			for (SmbFile fi : f.listFiles()) 
    		    	{ 
    					System.out.println(fi.getURL());
    		    	    System.out.println(fi.getName());
    		    	} 
    			}
    	
	}

Error Message:
Exception in thread "main" jcifs.smb.SmbAuthException: Access is denied.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1430)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1573)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1544)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:558)
	at jcifs.smb.SmbFile.exists(SmbFile.java:852)

**Comment by mbechler** [comment]
More information is required to figure out the cause of this error. Can you provide a debug level log?

Please check the SMB server logs if you can.
