### ISSUE TITLE
SMBFile URL with %20 is not resolvable (2.1.5)

### ISSUE THREAD

**Issue by col-panic** [AgNO3/jcifs-ng#271]
If I pass the URL `smb://xxx.yyy.ch/tests/test%20file.txt` (which is a valid smb file) to 

```
URL url = new URL(smb://xxx.yyy.ch/tests/test%20file.txt);
return new SmbFile(url, credentials);
```
then loading fails with 
```
jcifs.smb.SmbException: The system cannot find the file specified.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1462)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1573)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
```

I can fix this using

```
URL url = new URL(smb://xxx.yyy.ch/tests/test%20file.txt);
String _url = url.toExternalForm().replaceAll("%20", " ");
return new SmbFile(_url, credentials);
```

but IMHO `%20` is valid, and JCFIS should be capable of handling this internal.

**Comment by mbechler** [comment]
Yes, unfortunately jcifs has been using "wrong" URL encodings all the time. I've already been planning to move to correct URL encoding, but as this is a somewhat significant breaking change I've been waiting for a major version release.

**Comment by col-panic** [comment]
Could it be that other encoded characters like `%23` which is `#` do fail too here?

**Comment by mbechler** [comment]
Yes, i think so. #196
