### ISSUE TITLE
Transport8 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=107548,wordCount=0,byteCount=4144

### ISSUE THREAD

**Issue by artragis** [AgNO3/jcifs-ng#273]
Hello,

One of our customer recently faced an issue sending files to its SMBv2 server. The error allways appear and the error message is : 
```
Transport8 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=107548,wordCount=0,byteCount=4144
```

The SMBv2 server is hosted on : 
- Windows Server 2019 Standard
- OS BUILD : 17763.1518

The full stacktrace is the foolowing : 

```
2021-02-10 08:20:10 ERROR Three60RemoteFile:112 - Transport5 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=307414,wordCount=0,byteCount=4144
jcifs.smb.SmbException: Transport5 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=307414,wordCount=0,byteCount=4144
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1551)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
	at jcifs.smb.SmbFileOutputStream.writeDirect(SmbFileOutputStream.java:332)
	at jcifs.smb.SmbFileOutputStream.write(SmbFileOutputStream.java:294)
	at com.gbs.three60.suite.bmo.util.file.Three60RemoteFile.write(Three60RemoteFile.java:109)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFile(Three60FileUtil.java:208)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:279)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:277)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:277)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:277)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:130)
	at com.gbs.three60.suite.bobj.promotion.util.BOBJPromotionBIARUtil.copyTmpDirToDestination(BOBJPromotionBIARUtil.java:371)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.impl.BOBJPromotionWorker.postProcess(BOBJPromotionWorker.java:121)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.api.AbstractWorker.processTask(AbstractWorker.java:221)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.api.AbstractWorker.call(AbstractWorker.java:162)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.api.AbstractWorker.call(AbstractWorker.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jcifs.util.transport.TransportException: Transport5 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=307414,wordCount=0,byteCount=4144
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:351)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1025)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1544)
	... 25 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at jcifs.util.transport.Transport.readn(Transport.java:70)
	at jcifs.smb.SmbTransportImpl.peekKey(SmbTransportImpl.java:828)
	at jcifs.util.transport.Transport.loop(Transport.java:420)
	at jcifs.util.transport.Transport.run(Transport.java:769)
	... 1 more
```

Reproduced with : 

jcifs-ng 2.1.4 + bcprov 1.55
jcifs-ng 2.1.5 + bcprov 1.64

**Comment by mbechler** [comment]
Can you provide a network capture (PCAP) of when this happens? 
On first glance, this looks like the server is closing the connection in response to some request we send, which typically should only happen on severe protcol violations. Can any special circumstance/call be identified which causes this?
Maybe also the Windows SMB server logs can give some indication what goes wrong there.

**Comment by artragis** [comment]
I will try to get some logs but pcap will not be possible.

**Comment by artragis** [comment]
In event log we see errors saying "Server does not support Multichannel".

**Comment by artragis** [comment]
Hello,

In the event logs told use to run a powershell command to activate multichannel on server side.
Once this was activated, the error changed to 

```
2021-02-17 16:35:30 ERROR Three60RemoteFile:112 - Connection reset by peer: socket write error
jcifs.smb.SmbException: Connection reset by peer: socket write error
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1551)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
	at jcifs.smb.SmbFileOutputStream.writeDirect(SmbFileOutputStream.java:332)
	at jcifs.smb.SmbFileOutputStream.write(SmbFileOutputStream.java:294)
	at com.gbs.three60.suite.bmo.util.file.Three60RemoteFile.write(Three60RemoteFile.java:109)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFile(Three60FileUtil.java:208)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:279)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:277)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:277)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:277)
	at com.gbs.three60.suite.bmo.util.file.Three60FileUtil.copyFolderContent(Three60FileUtil.java:130)
	at com.gbs.three60.suite.bobj.promotion.util.BOBJPromotionBIARUtil.copyTmpDirToDestination(BOBJPromotionBIARUtil.java:371)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.impl.BOBJPromotionWorker.postProcess(BOBJPromotionWorker.java:121)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.api.AbstractWorker.processTask(AbstractWorker.java:221)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.api.AbstractWorker.call(AbstractWorker.java:162)
	at com.gbs.three60.suite.business.three60object.scheduling.worker.api.AbstractWorker.call(AbstractWorker.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at jcifs.smb.SmbTransportImpl.doSend(SmbTransportImpl.java:914)
	at jcifs.util.transport.Transport.doSend(Transport.java:276)
	at jcifs.util.transport.Transport.sendrecv(Transport.java:215)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1025)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1544)
	... 25 more
```

**Comment by mbechler** [comment]
We do not support multichannel either, so this is curious. I suppose this points to the Channel or  WriteChannelInfo* fields ending up non-zero. As part of the regular message generation this is not possible on the jcifs side, so I guess this can only be some weird alignment issue or corruption by some other part of the code. Would be really helpful to see what ends up on the wire.

**Comment by ckirscher-gbs** [comment]
Hi,

I'm a colleague of artragis. I'd like to add some information, though I'm not sure it could help understand what's happening here.

Our customer is actually sending a large amount of files, and the [sending] process fails after more than 9 minutes. On smaller samples, the sending operation is successful.

Could the quantity or the duration be responsible for this?

**Comment by mbechler** [comment]
Hard to rule out completely, but I would not think so. Is the connection used by multiple threads?

**Comment by artragis** [comment]
Hello

After verification, for this transfert this is single threaded.

Regards

**Comment by mbechler** [comment]
Hm, this is going to be really tough to figure out if we cannot at least get some information about what is actually sent there.

**Comment by artragis** [comment]
Hello,
our customer provided us this screenshot. Perhaps this can be usefull to you : 
![image](https://user-images.githubusercontent.com/1523653/112610597-29b73380-8e1d-11eb-8dc0-ecb9a4df0395.png)

**Comment by mbechler** [comment]
Is there any context for this? Is this the last nessage seen before the error occurs (however it is not the write related to the error)? Such screenshots could possibly help, but should include the last few packets and  the full decoded frame details.

**Comment by artragis** [comment]
According to our customer this is the the frame that he observed when the job failed.

The error flag was STATUS_OBJECT_NAME_NOT_FOUND.
I will get back to them to know if they are authorized to provide a packet dump from a little bit before the error.

**Comment by artragis** [comment]
Hello, they provided us those two pcap extracts

[doublerun_dvi21267-fin.cap.txt](https://github.com/AgNO3/jcifs-ng/files/6220445/doublerun_dvi21267-fin.cap.txt)
[doublerun_in21i126-fin.cap.txt](https://github.com/AgNO3/jcifs-ng/files/6220460/doublerun_in21i126-fin.cap.txt)

**Comment by mbechler** [comment]
Thanks.
In both captures there is something strange going on in the end, resulting in duplicate packets, not sure whether this is just a capture artifact or indicative of a network level issue. Ignoring these (TCP sequence numbers are repeated as well - so I don't think there is a way this could be caused by jcifs) this looks fine to me on the SMB protocol level, but the connection is closed by the server. In one of the captures the last request is even correctly answered first by the server, so I don't think this is in response to the SMB request.

What are the exceptions in these cases? not command=SMB2_WRITE but SMB2_CREATE instead, correct?
