### ISSUE TITLE
Error recovery mechanisms

### ISSUE THREAD

**Issue by tvirtualw** [AgNO3/jcifs-ng#275]
We have migrated from the old jcifs library (SMBv1) to jcifs-ng 2.1.5.

In general, our app runs fine with the new library but we have encountered sporadic non-reproducible errors that seem to require a JVM restart to fix.

Some context:

- We access different shares on different Windows 2019 servers that are part of an AD domain.
- We use the default jcifs configuration except for forcing `jcifs.smb.client.minVersion=SMB202`.
- We use the "old" approach of `new SmbFile(url, SingletonContext.getInstance().withCredentials(auth));` to create SmbFile instances.

First example is the below stack trace which seems to indicate a stale connection was closed by the SMB server. It occurred against a non-DFS share. Retries using new SmbFile instances failed with the same exception. Only a JVM restart fixed it.

````
jcifs.smb.SmbException: 0xC0000203
    at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1462)
    at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1573)
    at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1544)
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
    at jcifs.smb.SmbTreeImpl.treeDisconnect(SmbTreeImpl.java:844)
    at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1160)
    at jcifs.smb.SmbTransportImpl.doDisconnect(SmbTransportImpl.java:780)
    at jcifs.util.transport.Transport.disconnect(Transport.java:693)
    at jcifs.smb.SmbTransportPoolImpl.close(SmbTransportPoolImpl.java:302)
    at jcifs.context.BaseContext.close(BaseContext.java:207)
    at jcifs.context.AbstractCIFSContext.run(AbstractCIFSContext.java:156)
````

Second example is `jcifs.smb.SmbException: The network name cannot be found.` with NT status code `0xc00000cc` encountered while accessing different files on a DFS share. The error code seems to indicate an issue with DFS resolution. Again, retries using new SmbFile instances failed with the same exception. Only a JVM restart fixed it.

We would like to understand if jcifs-ng has built-in error recovery mechanisms that will deal with errors like stale/closed network connections, corrupted state in a Transport thread and similar things.

Such possibilities come to mind:

- There are no built-in recovery mechanisms in place. In this case, is there an easy way to recover from errors that a JVM restart may fix without restarting the JVM? Something like completely reinitializing jcifs with a clean slate, discarding any existing threads and internal state?
- Encountered issues are related to native / OS level issues and cannot be dealt with within the running JVM. Even clearing all jcifs threads/state would not fix it. A JVM restart is required. No way around it.
- There may be ways to work around such errors by using a different approach of instantiating SmbFile, e.g. not using a SingletonContext and/or obtaining SmbResource from CIFSContext. The README file does not sound like it should make a difference though.
- There are jcifs configuration options beyond the default settings that we should use and which either enable error recovery or make it less likely that errors are encountered.

We would very much appreciate feedback to the above.
To be clear, we are not looking for fixes to the two specific exceptions we have encountered, nor can we provide additional logs or packet capture at this point. We expect that unexplainable errors will happen from time to time and are just looking for ways to recover from them without having to restart the JVM.

Not of much help or relevance but: We cannot remember encountering any such issues with the old jcifs library and SMBv1 over the last couple of years but that was also a completely different software / hardware / networking environment without DFS and so on.

**Comment by mbechler** [comment]
For normal situations like dropped connections recovery should be in place, avoiding the reuse of broken connections. 
jcifs-ng removed all usage of global state (e.g. for connection pooling or dfs caching), so you would be able to cleanly reset it. However, you cannot not use SingletonContext then, as this is exactly the mechanism to implement the legacy behavior with global state (some of which could possibly be reset, but that is not really a supported scenario). If you manually create/manage the root context instances you should be able to get a completely clean restart without restarting the JVM (don't forget to close the old context).
I would not expect the JVM or OS state to cause any application level problems.

It would be great to figure out the bugs you are encountering: 
The one issue you are encountering looks like #242, unfortunately I still have not figured out what the server expects to be done to avoid the timeout or what should be done to recover from this situation. Regarding the DFS issue, debug logs would be useful to figure out what is going on (from what you described my best guess would be some caching related issue).

**Comment by tvirtualw** [comment]
Thank you for the feedback @mbechler .

The JavaDoc on the `CIFSContext` says to create a context per client configuration. It's not really clear what a "client" is. As we do not have separate JCIFS configuration properties for different servers/shares, we thought it would not make much difference then and kept using `SingletonContext`. But it would be definitely easier to manage recovery using separate contexts.

Our app has a lot of concurrent small file access through JCIFS going on. Would you be able to recommend a usage pattern for those contexts? Our concern is performance overhead when using a new context for each new SmbFile operation for example.

Such possibilities come to mind:

- Manage our own `CIFSContext` instead of using `SingletonContext`. Just to have more control over it and being able to use a new one easily if necessary.
- Create some sort of `BaseContext` factory that will create a new context for each SMB operation (like opening file, deleting file, etc.). Probably the best option in terms of error recovery but may have performance overhead.
- Something in between where we reuse contexts within the same method/operation in the code even if it would involve multiple different files/shares.

We would appreciate your feedback on that, esp. related to the performance concerns.

**Comment by mbechler** [comment]
Different client configurations in this case would mean what used to be the different system properties (which would be used globally). But this mechnaism also allows isolation/to avoid sharing certain resource, e.g. connection pool or DFS cache.  The primary reason all this (apart from a imho cleaner implementation) was to be able to run tests without starting thousands of Java VM. Maybe the test cases also can offer some more insight how it may be used.

You definitely would not want to use a fresh root context for every operation as then every operation will have to establish a fresh connection, authenticate and so forth which is pretty expensive (likely seconds). 

To allow the recovery from the error states that you are experiencing, one root context  which you could destroy and replace when such a error occurs would be sufficient I guess.

If you access it from multiple threads, this may also be a opportunity to use different root contexts. While concurrent usage is supposed to be working, you a) may be able to avoid potential bugs by not using it b) potentially can cause congestion on the shared connection.
