### ISSUE TITLE
java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1ObjectIdentifier.equals(Lorg/bouncycastle/asn1/ASN1Primitive;)Z

### ISSUE THREAD

**Issue by zml123456** [AgNO3/jcifs-ng#288]

**Comment by zml123456** [comment]
java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1ObjectIdentifier.equals(Lorg/bouncycastle/asn1/ASN1Primitive;)Z
	at jcifs.spnego.NegTokenInit.parse(NegTokenInit.java:167) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.spnego.NegTokenInit.<init>(NegTokenInit.java:66) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:243) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:698) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:536) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbFileOutputStream.<init>(SmbFileOutputStream.java:112) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbFileOutputStream.<init>(SmbFileOutputStream.java:95) ~[jcifs-ng-2.1.6.jar!/:na]
	at jcifs.smb.SmbFileOutputStream.<init>(SmbFileOutputStream.java:76) ~[jcifs-ng-2.1.6.jar!/:na]

**Comment by mbechler** [comment]
This looks like you are using a incompatible bouncycastle version.

**Comment by bomas** [comment]
I've the same issue in a project. Both:
- bcprov-jdk15to18 
- bcprov-jdk15on
Are on the classpath. 
jcifs-ng 2.1.6 requires bcprov-jdk15to18.
So I guess removing bcprov-jdk15on from the classpath should fix this. 

I'm curious. Why does jcifs-no no longer use bcprov-jdk15on?

**Comment by mbechler** [comment]
Not sure this relates to the original report, however: moved to jdk15to18 because the new (jdk15on) multi-release JARs were causing issues with some tooling for some people. But yes, now this is causing issues for others which now have a duplicated dep. Maybe we should have a vote :|

**Comment by mbechler** [comment]
Upcoming version will switch back to the "regular" jdk15on JAR, as I think that one causes issues for fewer users.

**Comment by ishAkkiah** [comment]
I face this issue now. Can I know what i
s the fix for this?

**Comment by mbechler** [comment]
Make sure that you have a compatible version on your application's classpath and that you don't have both bcprov-jdk15to18 and bcprov-jdk15on.

**Comment by Rap70r** [comment]
Hi @mbechler,

I'm facing the same issue. When I run the application locally, it works fine. However, when I run it on a Spark cluster, it fails. Any idea how I can solve the issue?

**Comment by mbechler** [comment]
Welcome to what is commonly called "classpath-hell" ;) Try to figure out which other bouncycastle version spark pulls into the classpath. If you are lucky it is a binary incompatiblity only, then you might get away by compiling jcifs-ng against that library version.  If spark's version is newer than the one pulled by jcifs-ng we can/will upgrade that in a future release.

**Comment by gerardorourke** [comment]
I am getting the exact same error as above - but I have confirmed that the versions I am using should be compatible?
Error: java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1ObjectIdentifier.equals(Lorg/bouncycastle/asn1/ASN1Primitive;)Z

The versions I am using:
jcifs-ng-2.1.9.jar
bcprov-jdk15on-1.69.jar

Any ideas? (using tomcat 9)

**Comment by mbechler** [comment]
Double check that there is nothing else pulling in another version.
