### ISSUE TITLE
Get 'The parameter is incorrect.' when set client buffer size

### ISSUE THREAD

**Issue by zqs164** [AgNO3/jcifs-ng#289]
When I use below code to access a share folder, I get the 'The parameter is incorrect.' error. Can some help check If this is a bug or Just I have made a mistake. I just want to increase the buffer size so that we can decrease the request times which may save some time casued by network delay. I can not find more document or wiki for this. I'd appreciate it if someone can help this.

```java
Properties properties = new Properties();
properties.setProperty("jcifs.smb.client.transaction_buf_size", String.valueOf(7 * 1024 * 1024));
properties.setProperty("jcifs.smb.client.rcv_buf_size", String.valueOf(7 * 1024 * 1024));
CIFSContext context = new BaseContext(new PropertyConfiguration(properties)).withCredentials(new NtlmPasswordAuthenticator("Ike", "*****"));
SmbFile file = new SmbFile("smb://localhost/share/share.txt", context);

BufferedReader br = new BufferedReader(new InputStreamReader(new BufferedInputStream(new SmbFileInputStream(file), 10 * 1024 * 1024)));

System.out.println(br.readLine());

br.close();
```
```java
1528 [main] TRACE jcifs.smb.SmbTransportImpl - Sending command=SMB2_IOCTL,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 
1528 [main] TRACE jcifs.smb.SmbTransportImpl - command=SMB2_IOCTL,status=0,flags=0x0000,mid=5,wordCount=0,byteCount=84 
1528 [main] TRACE jcifs.smb.SmbTransportImpl - FE534D4240000000000000000B00010008000000000000000500000000000000000000000100000019000004009C0000D41BFA3CB2DEAF685670D6F790B9A5AB3900000004021400FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF780000001C00000000000000000000000000000000FE6F00010000000000000001000000013BC4340AEE71A01AE21AF996B9B592010002000202100200000000 
1528 [Transport0] TRACE jcifs.smb.SmbTransportImpl - New data read: Transport0[localhost/127.0.0.1:445,state=3,signingEnforced=false,usage=5] 
1528 [Transport0] TRACE jcifs.smb.SmbTransportImpl - FE534D42400000000D0000C00B00010009000000000000000500000000000000 
1528 [main] DEBUG jcifs.smb.SmbTransportImpl - Error code: 0xC000000D for Smb2IoctlRequest 
1528 [main] TRACE jcifs.smb.SmbTransportImpl - Adding credits 1 
1528 [main] TRACE jcifs.smb.SmbSessionImpl - Send failed 
jcifs.smb.SmbException: The parameter is incorrect.
    at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1457)
    at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
    at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
    at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
    at jcifs.smb.SmbTreeImpl.validateNegotiation(SmbTreeImpl.java:720)
    at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:672)
    at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:612)
    at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
    at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
    at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
    at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
    at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:96)
    at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:86)
```
Library version:
```xml
<dependency>
    <groupId>eu.agno3.jcifs</groupId>
    <artifactId>jcifs-ng</artifactId>
    <version>2.1.3</version>
</dependency>
```

**Comment by mbechler** [comment]
Not that I am aware of a specific bug, but please try to reproduce with the current version.

What fails is the first IOCTL so that likely is caused by the server rejecting the return buffer limit (which is based on _jcifs.smb.client.transaction_buf_size_). Not exactly sure why it does that (probably credits need to be requested for larger sizes), but I guess it works without increasing the buffer size, right?

With regards to generally increasing the buffer size: Unfortunately jcifs-ng currently does not have support for the multi-credit feature required to increase the sizes beyond 64k.
