### ISSUE TITLE
ArrayIndexOutOfBoundsException in NameServicePacket:readWireFormat on Android with blockada VPN app installed

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#293]
In my nova android video player application, during my own crafted UDP network discovery https://github.com/nova-video-player/aos-FileCoreLibrary/blob/v6/src/jcifs/netbios/UdpDiscovery.java I get a systematic `ArrayIndexOutOfBoundsException` during the `readWireFormat` reported by users only when enabling the [blockada](https://blokada.org/) add blocking VPN based application (disabled it is fine):
```
2021-09-10 23:36:08.054 9600-9712/org.courville.nova W/jcifs.netbios.UdpDiscovery: [Thread-7] WARN  jcifs.netbios.UdpDiscovery - doTcpDiscovery: caught ArrayIndexOutOfBoundsException
2021-09-10 23:36:08.056 9600-9712/org.courville.nova E/jcifs.netbios.UdpDiscovery: [Thread-7] ERROR jcifs.netbios.UdpDiscovery - UdpDiscoveryThread
    java.lang.ArrayIndexOutOfBoundsException: src.length=576 srcPos=1227 dst.length=6 dstPos=0 length=6
        at java.lang.System.arraycopy(Native Method)
        at jcifs.netbios.NodeStatusResponse.readRDataWireFormat(NodeStatusResponse.java:80)
        at jcifs.netbios.NameServicePacket.readResourceRecordWireFormat(NameServicePacket.java:241)
        at jcifs.netbios.NodeStatusResponse.readBodyWireFormat(NodeStatusResponse.java:62)
        at jcifs.netbios.NameServicePacket.readWireFormat(NameServicePacket.java:128)
        at jcifs.netbios.UdpDiscovery$UdpDiscoveryThread.run(UdpDiscovery.java:202)
```
Issue has been reported by users here https://github.com/nova-video-player/aos-AVP/issues/448 and I can witness it happens on my acra debug backend.
I know that this is quite specific and relies on some quite old UDP discovery 'hack' but if you have any idea about what could go wrong, I would welcome your insights.

**Comment by mbechler** [comment]
Can you provide a capture of the Netbios traffic? I suppose blockada modifies them (privacy feature maybe) and either produces a broken packet or just produces some situation that we do not properly handle in the parser.
