### ISSUE TITLE
Smb2TreeConnectResponse should allow tree ids of 0

### ISSUE THREAD

**Issue by eg-lee** [AgNO3/jcifs-ng#303]
Currently, when determining if a tree id is valid, the `Smb2TreeConnectResponse` class's `isValid` method is explicitly not allowing tree ids equal to 0:

```
//https://github.com/AgNO3/jcifs-ng/blob/master/src/main/java/jcifs/internal/smb2/tree/Smb2TreeConnectResponse.java

@Override
public boolean isValidTid () {
    return getTreeId() != 0;
}
```

That method will result in an exception when using `SmbFile` to check a directory's existence or listing files:

```
jcifs.smb.SmbException: TreeID is invalid
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:658) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:628) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559) ~[jcifs-ng-2.1.7.jar:na]
	at jcifs.smb.SmbFile.exists(SmbFile.java:859) ~[jcifs-ng-2.1.7.jar:na]
```

The CIFS specification states that 0 is a valid tree id:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/e626b07d-d034-4b45-8676-43228a18e30a

The corrected method should return:
```
@Override
public boolean isValidTid () {
    return getTreeId() >= 0;
}
```
I would think this would be causing issues for users other than me, but I recently encountered this when trying to connect to an IBM network share running SMB2. The only way for me to read files from the share was to download this project and change that method, instead of using the latest public maven artifact [2.1.7](https://mvnrepository.com/artifact/eu.agno3.jcifs/jcifs-ng/2.1.7).

**Comment by mbechler** [comment]
You are absolutely right. Looks like I carried over the bad check from the original SMB1 code and unfortunately missed to fix that for SMB2 when I ultimately fixed it for SMB1 (#149, https://github.com/AgNO3/jcifs-ng/issues/149#issuecomment-473649950).

**Comment by eg-lee** [comment]
Ok, I was confused for a bit when I had seen that discussion before about it being an issue and fixed

**Comment by courville** [comment]
Just FYI, I came accross https://github.com/codelibs/jcifs/commit/6452365219b53ce64495e674b36d2ce016a71d8b#commitcomment-74294731 and it seems that I face similar issue when I blindly did an upstep in my app.
