### ISSUE TITLE
Tree ID is invalid

### ISSUE THREAD

**Issue by MatthiasDS96** [AgNO3/jcifs-ng#305]
When I'm trying to connect to the SmbFile using following code:

  final SmbFile path = new SmbFile(directory, fCIFSContext);
  path.connect();

I get following error.

Caused by: jcifsng.smb.SmbException: TreeID is invalid
      at jcifsng.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:658) 
      at jcifsng.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:628) 
      at jcifsng.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614) 
      at jcifsng.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568) 
      at jcifsng.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489) 
      at jcifsng.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465) 
      at jcifsng.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426) 
      at jcifsng.smb.SmbFile.ensureTreeConnected(SmbFile.java:559) 
      at jcifsng.smb.SmbFile.connect(SmbFile.java:518) 

When debugging the source code it looks like the TreeID is 0 (which is invalid according to Smb2TreeConnectResponse.class)
I'm using the latest dependency version 2.1.7
 <groupId>eu.agno3.jcifs</groupId>
<version>2.1.7</version>

When connection to the smb using smbclient this works fine and everything seems in place.

What can be the reason that the TreeID is set to 0 and not valid?

**Comment by mbechler** [comment]
Interesting how this has come up just now twice after all that time, tid=0 is perfectly valid and that was an oversight: should be fixed in master after #303

**Comment by MatthiasDS96** [comment]
Thank you for the quick reply @mbechler 
Is there a new release coming soon so we can use version 2.1.8?
