### ISSUE TITLE
java.util.ConcurrentModificationException on jcifs.smb.SmbFile.exists

### ISSUE THREAD

**Issue by zhiwenhu** [AgNO3/jcifs-ng#306]
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
	at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:118)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:194)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:837)

**Comment by zhiwenhu** [comment]
with version jcifs-ng-2.1.7.jar

**Comment by zhiwenhu** [comment]
how can i resolve this issue?

**Comment by mbechler** [comment]
Can you double check that you are really using 2.1.7, the line numbers don't align with that version. I really don't see any access that is not synchronized on the connections field.

Otherwise, any chance you could run this with an exception breakpoint and suspend the whole VM so we can get a stacktrace for the modiying access.
