### ISSUE TITLE
java.lang.NullPointerException on SmbFile.exists

### ISSUE THREAD

**Issue by zhiwenhu** [AgNO3/jcifs-ng#307]
java.lang.NullPointerException
	at jcifs.smb.SmbTransportImpl.isSigningEnforced(SmbTransportImpl.java:311)
	at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:134)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:194)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbFile.exists(SmbFile.java:837)

on version jcfs-ng-2.1.7.jar

**Comment by zhiwenhu** [comment]
why so many this error happened when many smb session running.

**Comment by zhiwenhu** [comment]
how can i resolve this issue?

**Comment by zhiwenhu** [comment]
It seems class SmbTransportImpl.java, "this.getNegotiateResponse()" returned null.
```
    public boolean isSigningEnforced() throws SmbException {
        return this.signingEnforced ? true : this.getNegotiateResponse().isSigningRequired();
    }
```
