### ISSUE TITLE
tried to access class org.bouncycastle.asn1.DEROutputStream from class jcifs.spnego.NegTokenInit

### ISSUE THREAD

**Issue by jyzheng919** [AgNO3/jcifs-ng#308]
i want to use jcifs-ng  substitutes jcifs-1.3.17

jcifs 1.3.17  download file success
```
NtlmPasswordAuthentication auth = new NtlmPasswordAuthentication("xxxx", "xxxx","xxxxx");
String Url = HdcConstants.FILE_PATH + sourcePath + fileName;
SmbFile remoteFile = new SmbFile(Url, auth);
file.getInputStream();
```
jcifs-ng 2.1.4：download file fail。
```
        NtlmPasswordAuthenticator auth = new NtlmPasswordAuthenticator("xxxx", "xxxx","xxxxx");
        String Url = HdcConstants.FILE_PATH + sourcePath + fileName;
        // set config
        Properties properties = new Properties();
        properties.setProperty("jcifs.smb.client.responseTimeout", "50000");
        PropertyConfiguration configuration = new PropertyConfiguration(properties);

        CIFSContext cifsContext = new BaseContext(configuration).withCredentials(auth);

        SmbFile file = new SmbFile(Url, cifsContext);
        file.getInputStream();
```
2022-06-08 15:22:17,857 [ForkJoinPool.commonPool-worker-0] ERROR FracasUntil:87 - smb get input stream IllegalAccessError
java.lang.IllegalAccessError: tried to access class org.bouncycastle.asn1.DEROutputStream from class jcifs.spnego.NegTokenInit
	at jcifs.spnego.NegTokenInit.toByteArray(NegTokenInit.java:158) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SpnegoContext.initSecContext(SpnegoContext.java:207) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbSessionImpl.createToken(SmbSessionImpl.java:656) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:538) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:429) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTransportImpl.getDfsReferrals(SmbTransportImpl.java:1723) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:192) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:233) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:352) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:326) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:530) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:558) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:96) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:86) ~[jcifs-ng-2.1.4.jar!/:?]
	at jcifs.smb.SmbFile.getInputStream(SmbFile.java:2111) ~[jcifs-ng-2.1.4.jar!/:?]

**Comment by matheis** [comment]
Give it a try with jcifs-ng:2.1.6. This should be fixed there I think. 
https://github.com/AgNO3/jcifs-ng/commit/7569f0ad8a4251748de76745371addb42f58938c#diff-f0534f69a5f680d8f2019487049743bf99206310b0aec3a09e0721a5580c5c3dR144
