### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException is thrown when trying to get shares

### ISSUE THREAD

**Issue by niru888** [AgNO3/jcifs-ng#31]
Hi,
I'm trying to get all shares from my SMB server but sometimes (it is not consistent)  ArrayIndexOutOfBoundsException is thrown.
I debug it little bit and I saw that the response len value is huge (about 931M)
Do somebody familiar with this issue? 

```
`       Properties prop = new Properties();
        prop.put( "jcifs.smb.client.enableSMB2", "true");
        prop.put( "jcifs.smb.client.disableSMB1", "false");
        prop.put( "jcifs.traceResources", "true" );
        Configuration config = new PropertyConfiguration(prop);
        CIFSContext context = new BaseContext(config);
        CIFSContext contextWithCred  = context.withCredentials(new NtlmPasswordAuthentication(null, "domain", "admin", "pass"));
        String url = "smb://192.1.10.102/";
        try (SmbFile share = new SmbFile(url, contextWithCred)) {
            for (SmbFile f : share.listFiles(filter)){
                System.out.println(f.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }`
```

Stacktrace:
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/192.1.10.102
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:673)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:557)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:143)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:216)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1251)
	at Main.test(Main.java:41)
	at Main.main(Main.java:17)
Caused by: jcifs.util.transport.TransportException: java.lang.ArrayIndexOutOfBoundsException
	at jcifs.util.transport.Transport.run(Transport.java:752)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at jcifs.smb.SmbTransportImpl.negotiate2(SmbTransportImpl.java:639)
	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:522)
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:690)
	at jcifs.util.transport.Transport.run(Transport.java:725)
	... 1 more

**Comment by niru888** [comment]
Thanks for your prompt response
I clone the main repository on January 24, 2018 and I update the maxVersion to be SMB311 on class BaseConfiguration because SMB311 should be supported

```
    protected void initProtocolVersions ( DialectVersion min, DialectVersion max ) {
        this.minVersion = min != null ? min : DialectVersion.SMB1;
        this.maxVersion = max != null ? max : DialectVersion.SMB311;
    }
```
Is there any plans to fix it?

**Comment by mbechler** [comment]
Ah, ok, that at least explains why you are hitting that branch. As it's not the issue fixed in the commit (as you have a more recent checkout) and you say it is not failing consistently (for the same server I assume) it might be a concurrency issue of some kind. Can you get me stacktraces for all threads (suspend VM) when the exception occurs, that you shed some light on what might be going on.

**Comment by mbechler** [comment]
Buffer synchronization looks okay so far. The stacktrace suggest that this is occuring on a connection timeout, is that the case? Can you provide a debug log as well?
