### ISSUE TITLE
ClassCastException seen in the field for jcifs.smb.SmbTransportImpl.setupResponses

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#326]
Seen in the field with nova my android video player app reported on my sentry crashnalytics backend (no clue what triggers it). Here is the stacktrace collected:
```
java.lang.ClassCastException: jcifs.internal.smb1.com.SmbComBlankResponse cannot be cast to jcifs.internal.smb1.AndXServerMessageBlock
    at jcifs.smb.SmbTransportImpl.setupResponses(SmbTransportImpl.java:1087)
    at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:927)
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1578)
    at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1542)
    at jcifs.smb.SmbSessionImpl.logoff(SmbSessionImpl.java:1195)
    at jcifs.smb.SmbTransportImpl.getSmbSession(SmbTransportImpl.java:392)
    at jcifs.smb.SmbTransportImpl.getSmbSession(SmbTransportImpl.java:106)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:566)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
    at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
    at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
    at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
    at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
    at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
    at jcifs.smb.SmbFile.listFiles(SmbFile.java:1287)
    at com.archos.filecorelibrary.jcifs.JcifListingEngine$JcifListingThread.run(JcifListingEngine.java:113)
```

jcifs-ng master is used (26844892eccc2335bbeeee87c5a002515f28bbd9).

**Comment by courville** [comment]
Thank you! Connecting the dots with https://github.com/nova-video-player/aos-AVP/issues/819 
FYI it fixed regression on Apple time capsule SMB1 for some of my users.
