### ISSUE TITLE
library throws jcifs.smb.SmbException: Failed to connect:

### ISSUE THREAD

**Issue by rongway777** [AgNO3/jcifs-ng#328]
Strange problem. The library is normal on one device, but this exception is thrown on another device. (They tried to access the same server)，Can you give me some suggestions? The following is the log and configuration information, Looking forward to your reply，Thanks in advance!

//prop:
prop.put("jcifs.smb.client.disableSMB1", "false");
prop.put("jcifs.smb.client.enableSMB2", "true");
prop.put("jcifs.smb.client.dfs.disabled", "true");
prop.put("jcifs.netbios.retryTimeout", "5000");
prop.put("jcifs.netbios.retryCount", "5");
prop.put("jcifs.resolveOrder", "BCAST,LMHOSTS,WINS,DNS");
prop.put("jcifs.smb.client.ipcSigningEnforced", "false");

//log:
12-23 17:16:56.478670 10888 11029 W System.err: jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/172.16.0.88
12-23 17:16:56.478827 10888 11029 W System.err: 	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:689)
12-23 17:16:56.478843 10888 11029 W System.err: 	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:220)
12-23 17:16:56.478855 10888 11029 W System.err: 	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:48)
12-23 17:16:56.478867 10888 11029 W System.err: 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:565)
12-23 17:16:56.478876 10888 11029 W System.err: 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
12-23 17:16:56.478890 10888 11029 W System.err: 	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:145)
12-23 17:16:56.478899 10888 11029 W System.err: 	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:218)
12-23 17:16:56.478910 10888 11029 W System.err: 	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:243)
12-23 17:16:56.478920 10888 11029 W System.err: 	at jcifs.smb.SmbFile.list(SmbFile.java:1162)
12-23 17:16:56.478934 10888 11029 W System.err: 	at 
....
12-23 17:16:56.479038 10888 11029 W System.err: Caused by: jcifs.util.transport.TransportException: java.net.ConnectException: failed to connect to /172.16.0.88 (port 445) from /172.16.110.66 (port 58594) after 35000ms: isConnected failed: EHOSTUNREACH (No route to host)
12-23 17:16:56.479057 10888 11029 W System.err: 	at jcifs.util.transport.Transport.run(Transport.java:769)
12-23 17:16:56.479068 10888 11029 W System.err: 	at java.lang.Thread.run(Thread.java:764)
12-23 17:16:56.479154 10888 11029 W System.err: Caused by: java.net.ConnectException: failed to connect to /172.16.0.88 (port 445) from /172.16.110.66 (port 58594) after 35000ms: isConnected failed: EHOSTUNREACH (No route to host)
12-23 17:16:56.479168 10888 11029 W System.err: 	at libcore.io.IoBridge.isConnected(IoBridge.java:278)
12-23 17:16:56.479179 10888 11029 W System.err: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
12-23 17:16:56.479189 10888 11029 W System.err: 	at libcore.io.IoBridge.connect(IoBridge.java:129)
12-23 17:16:56.479205 10888 11029 W System.err: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
12-23 17:16:56.479222 10888 11029 W System.err: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-23 17:16:56.479233 10888 11029 W System.err: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-23 17:16:56.479243 10888 11029 W System.err: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-23 17:16:56.479252 10888 11029 W System.err: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-23 17:16:56.479261 10888 11029 W System.err: 	at java.net.Socket.connect(Socket.java:621)
12-23 17:16:56.479273 10888 11029 W System.err: 	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:494)
12-23 17:16:56.479282 10888 11029 W System.err: 	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:706)
12-23 17:16:56.479292 10888 11029 W System.err: 	at jcifs.util.transport.Transport.run(Transport.java:742)
12-23 17:16:56.479303 10888 11029 W System.err: 	... 1 more
12-23 17:16:56.479368 10888 11029 W System.err: Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
12-23 17:16:56.479386 10888 11029 W System.err: 	at libcore.io.IoBridge.isConnected(IoBridge.java:267)
12-23 17:16:56.479398 10888 11029 W System.err: 	... 12 more

**Comment by mbechler** [comment]
This very much looks like a general network error: EHOSTUNREACH (No route to host). Unless a wrong address is resolved (172.16.0.88) I don't think there is anything wrong with jcifs.
