### ISSUE TITLE
Looping when sid.getType() with  jcifs.smb.client.enableSMB2=true

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#34]
Hi,
I think there is looping with sid.getType() with jcifs.smb.client.enableSMB2=true.
In my test we connect to Windows 2008 R2 server and try to retrieve the type of sid as below

```
jcifs.internal.dtyp.ACE[] aces = smbFile.getSecurity(false);
String uid = "N/A";
for (ACE ace : aces)
    {
        SID sid = ace.getSID();
	if (sid.getType() == SID.SID_TYPE_USER)
        {
            uid = sid.toString();
            break;
        }
    }

```
I'm getting forever loop as below:
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getAccountName(SID.java:362)
        at TestJCIFS_readfiles.main(TestJCIFS_readfiles.java:124)

The loop:
        at jcifs.smb.SID.getType(SID.java:334)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:80)
        at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108)
        at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189)
        at jcifs.smb.SID.resolve(SID.java:480)
        at jcifs.smb.SID.resolveWeak(SID.java:487)
        at jcifs.smb.SID.getType(SID.java:334)

Could you check in jcifs.smb.SIDCacheImpl.resolveSids,
           switch ( s.getType() ) {  <---- should this be 'switch ( s.type ) {'

```
            switch ( s.getType() ) {                        
            case jcifs.SID.SID_TYPE_USER:
            case jcifs.SID.SID_TYPE_DOM_GRP:
            case jcifs.SID.SID_TYPE_DOMAIN:
            case jcifs.SID.SID_TYPE_ALIAS:
            case jcifs.SID.SID_TYPE_WKN_GRP:
                int sid_index = rpc.names.names[ si ].sid_index;
                rpc.unicode_string ustr = rpc.domains.domains[ sid_index ].name;
                s.domainName = ( new UnicodeString(ustr, false) ).toString();
                break;
            }

```
Thanks in advance.
Thanh

**Comment by thanh-vn** [comment]
Thank you,  the problem is fixed.
