### ISSUE TITLE
Server does not support NTLM authentication

### ISSUE THREAD

**Issue by fengyingkong** [AgNO3/jcifs-ng#340]
i use kerberos auth,example:

`  Properties prop3 = new Properties();
        prop3.setProperty("jcifs.smb.client.enableSMB2", "true");
        prop3.setProperty("jcifs.smb.client.disableSMB1", "true");
        SingletonContext.init(prop3);

        Subject s = getInitiatorSubject(ShareProperties.USERNAME, ShareProperties.PASSWORD, ShareProperties.DOMAIN, null);
        CIFSContext ctx = SingletonContext.getInstance().withCredentials(new Kerb5Authenticator(s, ShareProperties.DOMAIN, ShareProperties.USERNAME, ShareProperties.PASSWORD));
        try ( SmbResource f = new SmbFile(getShareRootURL(), ctx) ) {
            f.exists();
        }
        catch ( SmbUnsupportedOperationException e ) {
            Assume.assumeTrue("Using short names", false);
        }`

but error: 

`/Users/cs/jdk/jdk-17.0.7.jdk/Contents/Home/bin/java --add-exports java.base/sun.security.util=ALL–UNNAMED --add-exports java.security.jgss/sun.security.jgss.krb5=ALL-UNNAMED --add-exports java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-exports java.security.jgss/sun.security.krb5.internal=ALL-UNNAMED --add-exports java.security.jgss/sun.security.krb5.internal.crypto=ALL-UNNAMED -javaagent:/Applications/IntelliJ IDEA 2.app/Contents/lib/idea_rt.jar=49495:/Applications/IntelliJ IDEA 2.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/cs/Documents/smbv2.0-client/target/test-classes:/Users/cs/Documents/smbv2.0-client/target/classes:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.5.2/spring-boot-starter-web-2.5.2.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-starter/2.5.2/spring-boot-starter-2.5.2.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot/2.5.2/spring-boot-2.5.2.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.5.2/spring-boot-autoconfigure-2.5.2.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.5.2/spring-boot-starter-logging-2.5.2.jar:/Users/cs/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/cs/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/cs/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.14.1/log4j-to-slf4j-2.14.1.jar:/Users/cs/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/Users/cs/.m2/repository/org/slf4j/jul-to-slf4j/1.7.31/jul-to-slf4j-1.7.31.jar:/Users/cs/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/cs/.m2/repository/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.5.2/spring-boot-starter-json-2.5.2.jar:/Users/cs/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:/Users/cs/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:/Users/cs/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:/Users/cs/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.12.3/jackson-datatype-jdk8-2.12.3.jar:/Users/cs/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.3/jackson-datatype-jsr310-2.12.3.jar:/Users/cs/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.12.3/jackson-module-parameter-names-2.12.3.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.5.2/spring-boot-starter-tomcat-2.5.2.jar:/Users/cs/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.48/tomcat-embed-core-9.0.48.jar:/Users/cs/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.48/tomcat-embed-el-9.0.48.jar:/Users/cs/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.48/tomcat-embed-websocket-9.0.48.jar:/Users/cs/.m2/repository/org/springframework/spring-web/5.3.8/spring-web-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-beans/5.3.8/spring-beans-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-webmvc/5.3.8/spring-webmvc-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-aop/5.3.8/spring-aop-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-context/5.3.8/spring-context-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-expression/5.3.8/spring-expression-5.3.8.jar:/Users/cs/.m2/repository/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.5.2/spring-boot-starter-test-2.5.2.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-test/2.5.2/spring-boot-test-2.5.2.jar:/Users/cs/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.5.2/spring-boot-test-autoconfigure-2.5.2.jar:/Users/cs/.m2/repository/com/jayway/jsonpath/json-path/2.5.0/json-path-2.5.0.jar:/Users/cs/.m2/repository/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar:/Users/cs/.m2/repository/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar:/Users/cs/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/Users/cs/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar:/Users/cs/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar:/Users/cs/.m2/repository/org/assertj/assertj-core/3.19.0/assertj-core-3.19.0.jar:/Users/cs/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar:/Users/cs/.m2/repository/org/junit/jupiter/junit-jupiter/5.7.2/junit-jupiter-5.7.2.jar:/Users/cs/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.2/junit-jupiter-api-5.7.2.jar:/Users/cs/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/Users/cs/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/Users/cs/.m2/repository/org/junit/platform/junit-platform-commons/1.7.2/junit-platform-commons-1.7.2.jar:/Users/cs/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.7.2/junit-jupiter-params-5.7.2.jar:/Users/cs/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.7.2/junit-jupiter-engine-5.7.2.jar:/Users/cs/.m2/repository/org/junit/platform/junit-platform-engine/1.7.2/junit-platform-engine-1.7.2.jar:/Users/cs/.m2/repository/org/mockito/mockito-junit-jupiter/3.9.0/mockito-junit-jupiter-3.9.0.jar:/Users/cs/.m2/repository/org/skyscreamer/jsonassert/1.5.0/jsonassert-1.5.0.jar:/Users/cs/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar:/Users/cs/.m2/repository/org/springframework/spring-core/5.3.8/spring-core-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-jcl/5.3.8/spring-jcl-5.3.8.jar:/Users/cs/.m2/repository/org/springframework/spring-test/5.3.8/spring-test-5.3.8.jar:/Users/cs/.m2/repository/org/xmlunit/xmlunit-core/2.8.2/xmlunit-core-2.8.2.jar:/Users/cs/.m2/repository/eu/agno3/jcifs/jcifs-ng/2.1.9/jcifs-ng-2.1.9.jar:/Users/cs/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/cs/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/Users/cs/.m2/repository/org/slf4j/slf4j-log4j12/1.7.32/slf4j-log4j12-1.7.32.jar:/Users/cs/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/cs/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.69/bcprov-jdk15on-1.69.jar:/Users/cs/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/Users/cs/.m2/repository/org/hamcrest/hamcrest-core/2.2/hamcrest-core-2.2.jar:/Users/cs/.m2/repository/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.jar:/Users/cs/.m2/repository/org/objenesis/objenesis/1.0/objenesis-1.0.jar:/Users/cs/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar com.tencent.smb.SMBv2Tests
WARNING: Unknown module: ALL–UNNAMED specified to --add-exports
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/cs/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/cs/.m2/repository/org/slf4j/slf4j-log4j12/1.7.32/slf4j-log4j12-1.7.32.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Ends 1688992666000
20:37:46.205 [main] DEBUG jcifs.netbios.NameServiceClientImpl - Resolved 'UD.COM' to [UD.COM/127.0.0.1] using DNS
20:37:46.210 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - Trying address UD.COM/127.0.0.1
20:37:46.219 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - New transport connection Transport0[UD.COM/127.0.0.1:445,state=0,signingEnforced=false,usage=1]
20:37:46.219 [main] DEBUG jcifs.util.transport.Transport - Connecting Transport0
20:37:46.219 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 127.0.0.1
20:37:46.278 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@206c58ee
20:37:46.278 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
20:37:46.279 [main] DEBUG jcifs.smb.SmbTransportImpl - Resolving DFS path \ud.com
20:37:46.282 [main] DEBUG jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=,targetHost=ud.com,targetDomain=UD.COM,uid=0,connectionState=0,usage=1] on Transport0
20:37:46.285 [main] DEBUG jcifs.smb.SmbTreeImpl - Connection state was 0
20:37:46.285 [main] DEBUG jcifs.smb.SmbTreeImpl - treeConnect: unc=\\ud.com\IPC$,service=?????
20:37:46.286 [main] DEBUG jcifs.smb.SmbSessionImpl - sessionSetup: 
20:37:46.286 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is ud.com
20:37:46.309 [main] DEBUG jcifs.smb.NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2],mic=null]
20:37:46.311 [main] DEBUG jcifs.smb.SmbSessionImpl - Session setup failed
jcifs.smb.SmbUnsupportedOperationException: Server does not support NTLM authentication
	at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:250)
	at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:706)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:544)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:429)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTransportImpl.getDfsReferrals(SmbTransportImpl.java:1758)
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:192)
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:233)
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:352)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:326)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:530)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbFile.exists(SmbFile.java:859)
	at com.tencent.smb.SMBv2Tests.main(SMBv2Tests.java:136)
20:37:46.311 [main] DEBUG jcifs.smb.SmbTreeImpl - Disconnect tree on treeConnectFailure
jcifs.smb.SmbUnsupportedOperationException: Server does not support NTLM authentication
	at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:250)
	at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:706)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:544)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:429)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTransportImpl.getDfsReferrals(SmbTransportImpl.java:1758)
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:192)
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:233)
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:352)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:326)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:530)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbFile.exists(SmbFile.java:859)
	at com.tencent.smb.SMBv2Tests.main(SMBv2Tests.java:136)
20:37:46.311 [main] DEBUG jcifs.smb.SmbTreeImpl - Usage dropped to zero, release session
20:37:46.311 [main] DEBUG jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport0[UD.COM/127.0.0.1:445,state=3,signingEnforced=false,usage=2]
20:37:46.311 [main] DEBUG jcifs.smb.DfsImpl - Getting domain controller for UD.COM failed
jcifs.smb.SmbUnsupportedOperationException: Server does not support NTLM authentication
	at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:250)
	at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:706)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:544)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:429)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:405)
	at jcifs.smb.SmbTransportImpl.getDfsReferrals(SmbTransportImpl.java:1758)
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:192)
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:233)
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:352)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:326)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:530)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbFile.exists(SmbFile.java:859)
	at com.tencent.smb.SMBv2Tests.main(SMBv2Tests.java:136)
20:37:46.312 [main] DEBUG jcifs.smb.DfsImpl - Failed to connect to domain controller for UD.COM
20:37:46.312 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - Trying address 0.0.0.0<00>/127.0.0.1
20:37:46.312 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - New transport connection Transport1[0.0.0.0<00>/127.0.0.1:445,state=0,signingEnforced=false,usage=1]
20:37:46.312 [main] DEBUG jcifs.util.transport.Transport - Connecting Transport1
20:37:46.312 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 127.0.0.1
20:37:46.317 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Negotiation response on Transport1 :jcifs.internal.SmbNegotiation@6334cc7c
20:37:46.317 [Transport1] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
20:37:46.317 [main] DEBUG jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=Kerb5Authenticatior[subject=javax.security.auth.Subject$SecureSet@cf0cff52,user=null,realm=null],targetHost=127.0.0.1,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport1
20:37:46.317 [main] DEBUG jcifs.smb.SmbTreeImpl - Connection state was 0
20:37:46.317 [main] DEBUG jcifs.smb.SmbTreeImpl - treeConnect: unc=\\127.0.0.1\FILESHARE,service=?????
20:37:46.317 [main] DEBUG jcifs.smb.SmbSessionImpl - sessionSetup: Kerb5Authenticatior[subject=javax.security.auth.Subject$SecureSet@cf0cff52,user=null,realm=null]
20:37:46.317 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is 127.0.0.1
20:37:46.318 [main] DEBUG jcifs.smb.Kerb5Authenticator - Have initial token NegTokenInit[flags=0,mechs=[1.2.840.48018.1.2.2, 1.2.840.113554.1.2.2],mic=null]
20:37:46.320 [main] DEBUG jcifs.smb.Kerb5Context - Found ExtendedGSSContext implementation: com.sun.security.jgss.ExtendedGSSContext
20:37:46.331 [main] DEBUG jcifs.smb.Kerb5Context - Service name is cifs@127.0.0.1
20:37:46.573 [main] DEBUG jcifs.smb.SmbSessionImpl - Context is established
20:37:46.574 [main] DEBUG jcifs.smb.SmbSessionImpl - No digest setup false B false
20:37:46.589 [main] DEBUG jcifs.smb.SmbTransportImpl - Error code: 0xC00000CC for Smb2TreeConnectRequest
20:37:46.589 [main] DEBUG jcifs.smb.SmbTreeImpl - Disconnect tree on treeConnectFailure
jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1496)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1607)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1014)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1578)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbFile.exists(SmbFile.java:859)
	at com.tencent.smb.SMBv2Tests.main(SMBv2Tests.java:136)
20:37:46.589 [main] DEBUG jcifs.smb.SmbTreeImpl - Usage dropped to zero, release session
20:37:46.590 [main] DEBUG jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport1[0.0.0.0<00>/127.0.0.1:445,state=3,signingEnforced=false,usage=2]
20:37:46.590 [main] DEBUG jcifs.smb.SmbTreeConnection - Referral failed, trying next
jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1496)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1607)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1014)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1578)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbFile.exists(SmbFile.java:859)
	at com.tencent.smb.SMBv2Tests.main(SMBv2Tests.java:136)
20:37:46.591 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Closing pool
20:37:46.591 [Thread-0] DEBUG jcifs.smb.SmbTransportImpl - Disconnecting transport Transport1[0.0.0.0<00>/127.0.0.1:445,state=5,signingEnforced=false,usage=0]
20:37:46.591 [Thread-0] DEBUG jcifs.smb.SmbSessionImpl - Logging off session on Transport1[0.0.0.0<00>/127.0.0.1:445,state=5,signingEnforced=false,usage=1]
20:37:46.591 [Thread-0] DEBUG jcifs.smb.SmbSessionImpl - Disconnect tree on logoff
20:37:46.591 [Thread-0] DEBUG jcifs.smb.SmbSessionImpl - Reacquire transport
20:37:46.591 [Thread-0] DEBUG jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport1[0.0.0.0<00>/127.0.0.1:445,state=5,signingEnforced=false,usage=2]
20:37:46.592 [Thread-0] DEBUG jcifs.util.transport.Transport - Trying to connect a disconnected transport
Exception in thread "main" jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1496)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1607)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1014)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1578)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbFile.exists(SmbFile.java:859)
	at com.tencent.smb.SMBv2Tests.main(SMBv2Tests.java:136)
20:37:46.603 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Scheduling transport connection for removal Transport1[0.0.0.0<00>/127.0.0.1:445,state=5,signingEnforced=false,usage=0] (1505745489)
20:37:46.603 [Thread-0] DEBUG jcifs.smb.SmbTransportImpl - Disconnecting transport Transport0[UD.COM/127.0.0.1:445,state=5,signingEnforced=false,usage=0]
20:37:46.603 [Transport1] DEBUG jcifs.util.transport.Transport - recv failed
java.io.IOException: end of stream
	at jcifs.util.transport.Transport.loop(Transport.java:448)
	at jcifs.util.transport.Transport.run(Transport.java:779)
	at java.base/java.lang.Thread.run(Thread.java:833)
20:37:46.603 [Transport1] DEBUG jcifs.util.transport.Transport - Disconnected
20:37:46.603 [Transport1] DEBUG jcifs.util.transport.Transport - Exception without a request pending
java.io.IOException: end of stream
	at jcifs.util.transport.Transport.loop(Transport.java:448)
	at jcifs.util.transport.Transport.run(Transport.java:779)
	at java.base/java.lang.Thread.run(Thread.java:833)
20:37:46.605 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Scheduling transport connection for removal Transport0[UD.COM/127.0.0.1:445,state=5,signingEnforced=false,usage=0] (14206573)
20:37:46.605 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Removing transport connection Transport1[0.0.0.0<00>/127.0.0.1:445,state=6,signingEnforced=false,usage=0] (1505745489)
20:37:46.606 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Removing transport connection Transport0[UD.COM/127.0.0.1:445,state=6,signingEnforced=false,usage=0] (14206573)
20:37:46.606 [Transport0] DEBUG jcifs.util.transport.Transport - Disconnected
20:37:46.606 [Transport0] DEBUG jcifs.util.transport.Transport - Exception without a request pending
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:985)
	at jcifs.util.transport.Transport.readn(Transport.java:70)
	at jcifs.smb.SmbTransportImpl.peekKey(SmbTransportImpl.java:828)
	at jcifs.util.transport.Transport.loop(Transport.java:420)
	at jcifs.util.transport.Transport.run(Transport.java:779)
	at java.base/java.lang.Thread.run(Thread.java:833)

Process finished with exit code 1
`

and i found here  the auth changed the ntlm.  why?
![image](https://github.com/AgNO3/jcifs-ng/assets/32350484/f22cc486-051c-4f7a-a157-fbc5de9df8a6)

**Comment by mbechler** [comment]
The lookup for DFS roots is always made anonymously, which I believe cannot be done with kerberos authentication. Obviously, in priciple that could also be done properly authenticated if so desired, however that is currently not supported.

**Comment by fengyingkong** [comment]
ok, thank you.
