### ISSUE TITLE
NTLMPasswordAuthenticator no longer working with latest bouncy castle versions

### ISSUE THREAD

**Issue by bryan-coleman** [AgNO3/jcifs-ng#342]
Fails with Bouncy Castle versions 175 and 176.  
Works with version 173. (didn't try 174; however, would likely work given the release notes: https://www.bouncycastle.org/releasenotes.html)

**Sample Test Code:**
try (SmbFile file = new SmbFile(<url>, <context>) {
  SmbFile[] list = file.listFiles();
}

**Failure Thread Dump:**
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERApplicationSpecific
	at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:243)
	at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:706)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:544)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1213)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.DERApplicationSpecific
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)

**Comment by AlBundy33** [comment]
@mbechler Do you have any idea if you want to change this or do you absolutely need the older version?

**Comment by bryan-coleman** [comment]
I appreciate you reaching out.  That said, I don't understand the
question.  Are you suggesting that I was/am using an old version of
jcifs-ng or bouncy castle?

I believe I was testing against the latest version of both; and, do not see
any newer versions available since this bug was raised.  If you would
please clarify what you are referring to that would be helpful.

**Comment by AlBundy33** [comment]
jcifs-ng does not work with latest bouncycastle because of
java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERApplicationSpecific

Tested in my local project with
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-ext-jdk18on

1.74 is the latest version that contains DERApplicationSpecific

**Comment by mbechler** [comment]
@bryan-coleman  I believe that was targeted at me. Sorry for taking so long.  Yes, unfortunately that is a direct reference to a removed class. Per documentation we should be able to replace DERApplicationSpecific with ASN1TaggedObject (+ additional checks) . Will be addressed for the next version, but I'm hestitant to do an release just for that change alone.

**Comment by mbechler** [comment]
Updated and adjusted to work with the latest BouncyCastle version in master.

**Comment by mbechler** [comment]
I get the pain that this is causing, and given the speed I currently make progress on other stuff, I think I'll go for a separate release soon.

**Comment by mbechler** [comment]
Just pushed 2.1.10 to maven central.

**Comment by HannesWell** [comment]
> Just pushed 2.1.10 to maven central.

Works like a charm. Thank you!
