### ISSUE TITLE
Bouncyastle removed "deprecated ASN1ApplicationSpecific(Parser) stuff"

### ISSUE THREAD

**Issue by Albex** [AgNO3/jcifs-ng#345]
Bouncycastle officially removed support for "ASN1ApplicationSpecific(Parser) stuff" since 1.75+ (https://github.com/bcgit/bc-java/commit/d0b10323cfaa0fce7ea8fb773d2d66f2087b8a05).
Our tests seem to show that Jcifs uses it:
```
java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERApplicationSpecific
    at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:243)
    at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:706)
    at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:544)
    at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
    at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
    at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
    at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
    at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
    at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
    at jcifs.smb.SmbFile.exists(SmbFile.java:859)
```
Any plan to remove this dependency ?

**Comment by mttcr** [comment]
to help with the fix:

```java
/**
 * A DER encoding version of an application specific object.
 * 
 * @deprecated Will be removed. See comments for
 *             {@link ASN1ApplicationSpecific}.
 */
public class DERApplicationSpecific 
```


```java
/**
 * Base class for an ASN.1 ApplicationSpecific object
 *
 * @deprecated Will be removed. Change application code to handle as {@link ASN1TaggedObject} only, testing
 *             for the expected {@link ASN1TaggedObject#getTagClass() tag class} of
 *             {@link BERTags#APPLICATION} in relevant objects before using. If using a
 *             {@link ASN1StreamParser stream parser}, handle application-tagged objects using
 *             {@link ASN1TaggedObjectParser} in the usual way, again testing for a
 *             {@link ASN1TaggedObjectParser#getTagClass() tag class} of {@link BERTags#APPLICATION}.
 */
public abstract class ASN1ApplicationSpecific
```

**Comment by mbechler** [comment]
Thanks, see #342
