### ISSUE TITLE
Error code: 0xC000003A STATUS_OBJECT_PATH_NOT_FOUND when Smb2CreateRequest for lsarpc

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#35]
Hi,
Out test is trying to retrieve the owner uid of an object as
String uid = smbFile.getOwnerUser().toString();

We run the test against 2 servers:
1st: Windows 2008 R2 server. The test passed.
2nd: netApp version 9. The test failed with the stack trace below and the error is 0xC000003A which is PATH NOT FOUND

DEBUG [-195684588@qtp--1409420992-0] jcifs.smb.SmbTreeConnection Not retrying
jcifs.smb.SmbException: The system cannot find the path specified.
at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1387) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1498) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:974) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1469) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:396) ~[jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:313) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbFile.openUnshared(SmbFile.java:741) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:169) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.dcerpc.msrpc.LsaPolicyHandle.(LsaPolicyHandle.java:43) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:107) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:189) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SID.resolve(SID.java:480) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2415) [jcifs-ng-2.0.1-flx.1.jar:?]
at jcifs.smb.SmbFile.getOwnerUser(SmbFile.java:2401) [jcifs-ng-2.0.1-flx.1.jar:?]
at storediq.siqcifs.facade.BaseSmbFacade.getExtendedAttributes(BaseSmbFacade.java:592) [siqsmb-1.0.2.jar:?]
at storediq.siqcifs.httpserver.httpcommands.GetExtendedAttributesCommand.call(GetExtendedAttributesCommand.java:40) [siqsmb-1.0.2.jar:?]
at storediq.siqcifs.httpserver.ServerServlet.invokeCommandHandler(ServerServlet.java:198) [siqsmb-1.0.2.jar:?]
at storediq.siqcifs.httpserver.ServerServlet.doRequest(ServerServlet.java:77) [siqsmb-1.0.2.jar:?]
at storediq.siqcifs.httpserver.ServerServlet.doPost(ServerServlet.java:218) [siqsmb-1.0.2.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-2.5-20081211.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [servlet-api-2.5-20081211.jar:?]
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.26.jar:6.1.26]:

We did not see much differences when comparing two debug stacks. We only saw one thing different:
1st: good case: Smb2CreateResponse Opened just the name 'lsarpc'. But for the failed case, it open with the name '192.168.0.10\IPC$\lsarpc'
Do you see if the error has to do anything with that? Any other advise for us to look into?
--------------------- 1st good case --------------------------------
[-1554196232@qtp--885766133-1] jcifs.smb.SmbTreeImpl treeConnect: unc=\192.168.225.248\IPC$,service=?????
[-1554196232@qtp--885766133-1] jcifs.smb.SmbTreeConnection Switching tree
[-1554196232@qtp--885766133-1] jcifs.smb.SmbTreeConnection Acquired tree on switch SmbTree[share=IPC$,service=null,tid=5,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
[-1554196232@qtp--885766133-1] jcifs.smb.SmbFile openUnshared: \lsarpc flags: 19f0023 access: 2019f attrs: 80 options: 0
[-1554196232@qtp--885766133-1] jcifs.internal.smb2.create.Smb2CreateRequest **Opening lsarpc**
[Transport0] jcifs.internal.smb2.create.Smb2CreateResponse Opened lsarpc: 811B0000300000001500000030000000
---------------------- 2nd failed case -----------------------
[-195684588@qtp--1409420992-0] jcifs.smb.SmbResourceLocatorImpl Share is IPC IPC$
[-195684588@qtp--1409420992-0] jcifs.smb.SmbResourceLocatorImpl Share is IPC IPC$
[-195684588@qtp--1409420992-0] jcifs.smb.SmbTreeImpl treeConnect: unc=\192.168.0.10\IPC$,service=?????
[-195684588@qtp--1409420992-0] jcifs.smb.SmbTreeConnection Switching tree
[-195684588@qtp--1409420992-0] jcifs.smb.SmbTreeConnection Acquired tree on switch SmbTree[share=IPC$,service=null,tid=2,inDfs=true,inDomainDfs=false,connectionState=2,usage=2]
[-195684588@qtp--1409420992-0] jcifs.smb.SmbFile openUnshared: \lsarpc flags: 19f0023 access: 2019f attrs: 80 options: 0
[-195684588@qtp--1409420992-0] jcifs.internal.smb2.create.Smb2CreateRequest **Opening 192.168.0.10\IPC$\lsarpc**
[-195684588@qtp--1409420992-0] jcifs.smb.SmbTransportImpl Error code: 0xC000003A for Smb2CreateRequest

Thanks in advance,

**Comment by mbechler** [comment]
With regards to the path, somehow the client is led to believe that this is inside DFS. This looks like the netapp is not setting the flags correctly. Can you get me a packet trace so I can see why this might be happening?

I can see that for SMB1 there used to be an excemption for the IPC share disabling DFS handling for that. 1c452edf3e272e206157a2e42641165c0901c343 adds something like that back in that should work for SMB2, too.

Unfortunately I don't have access to any netapps so I can't really test that stuff.

**Comment by thanh-vn** [comment]
Thanks for the comment.  I included the tcpdump.  We have not picked up your commit for this yet.

[SMB2-netApp-Status_object_path_not_found.zip](https://github.com/AgNO3/jcifs-ng/files/1692835/SMB2-netApp-Status_object_path_not_found.zip)

**Comment by thanh-vn** [comment]
Hi,
The exemption above does work for the netApp when connecting directly to a Windows server.  I have another question:  if the netApp is happened setting as a DFS in the future, do you think the IPC disabling DFS above would have any issue?
Thanks in advance,

**Comment by mbechler** [comment]
I don't think you can actually make IPC$ a DFS root, so this shouldn't be an issue.

**Comment by thanh-vn** [comment]
Thanks for the quick fix and responses.
