### ISSUE TITLE
class org.bouncycastle.asn1.DLApplicationSpecific cannot be cast to class org.bouncycastle.asn1.ASN1TaggedObject

### ISSUE THREAD

**Issue by lixiaolei-hub** [AgNO3/jcifs-ng#359]
**maven** 
```xml
<dependency>
 <groupId>eu.agno3.jcifs</groupId>
 <artifactId>jcifs-ng</artifactId>
 <version>2.1.10</version>
</dependency>
```
**test code**
```java
 CIFSContext cifsContext = SingletonContext.getInstance().withGuestCrendentials();
        try (SmbFile smbFile = new SmbFile("smb://192.168.1.159/share/lixiaolei", cifsContext)) {
            Arrays.stream(smbFile.listFiles()).forEach(file -> {
                log.info(file.toString());
            });
        }
```
**exception**
```
14:03:13.524 [main] DEBUG jcifs.context.SingletonContext - Initializing singleton context
14:03:13.793 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - Trying address 0.0.0.0<00>/192.168.1.159
14:03:13.802 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - New transport connection Transport0[0.0.0.0<00>/192.168.1.159:445,state=0,signingEnforced=false,usage=1]
14:03:13.803 [main] DEBUG jcifs.util.transport.Transport - Connecting Transport0
14:03:13.803 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Connecting in state 1 addr 192.168.1.159
14:03:13.826 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@43d18f66
14:03:13.826 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
14:03:13.829 [main] DEBUG jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=,targetHost=192.168.1.159,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
14:03:13.833 [main] DEBUG jcifs.smb.SmbTreeImpl - Connection state was 0
14:03:13.833 [main] DEBUG jcifs.smb.SmbTreeImpl - treeConnect: unc=\\192.168.1.159\SHARE,service=?????
14:03:13.834 [main] DEBUG jcifs.smb.SmbSessionImpl - sessionSetup: 
14:03:13.834 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is 192.168.1.159
14:03:13.866 [main] DEBUG jcifs.smb.SmbSessionImpl - Session setup failed
java.lang.ClassCastException: class org.bouncycastle.asn1.DLApplicationSpecific cannot be cast to class org.bouncycastle.asn1.ASN1TaggedObject (org.bouncycastle.asn1.DLApplicationSpecific and org.bouncycastle.asn1.ASN1TaggedObject are in unnamed module of loader 'app')
	at jcifs.spnego.NegTokenInit.parse(NegTokenInit.java:159)
	at jcifs.spnego.NegTokenInit.<init>(NegTokenInit.java:66)
	at jcifs.smb.NtlmPasswordAuthenticator.createContext(NtlmPasswordAuthenticator.java:243)
	at jcifs.smb.SmbSessionImpl.createContext(SmbSessionImpl.java:706)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:544)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:491)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1213)
	at com.ako.dmp.util.SmbUtils.main(SmbUtils.java:102)
14:03:13.866 [main] DEBUG jcifs.smb.SmbTreeImpl - Usage dropped to zero, release session
14:03:13.867 [main] DEBUG jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport0[0.0.0.0<00>/192.168.1.159:445,state=3,signingEnforced=false,usage=2]
14:03:13.868 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Closing pool
14:03:13.868 [Thread-0] DEBUG jcifs.smb.SmbTransportImpl - Disconnecting transport Transport0[0.0.0.0<00>/192.168.1.159:445,state=5,signingEnforced=false,usage=0]
14:03:13.870 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Scheduling transport connection for removal Transport0[0.0.0.0<00>/192.168.1.159:445,state=5,signingEnforced=false,usage=0] (52594931)
14:03:13.870 [Transport0] DEBUG jcifs.util.transport.Transport - Disconnected
14:03:13.870 [Thread-0] DEBUG jcifs.smb.SmbTransportPoolImpl - Removing transport connection Transport0[0.0.0.0<00>/192.168.1.159:445,state=6,signingEnforced=false,usage=0] (52594931)
```
**additional** 
To reduce complexity, I turned on public access to the samba server, and of course, I tried using usernames and passwords, and the same error occurred.
Did I use it the wrong way?

**Comment by mbechler** [comment]
This error indicates an incompatible version of the bouncycastle library, maybe you are pulling in two versions.

**Comment by lixiaolei-hub** [comment]
According to your tips, I excluded the components with bouncycastle version conflict, and now the test passes, thank you very much
Conflicting versions:
1.69 vs 1.76, remove the 1.69,keep 1.76
