### ISSUE TITLE
Handling closed TCP connection when doing SMB1+2 nego

### ISSUE THREAD

**Issue by phhusson** [AgNO3/jcifs-ng#364]
Hi,

I have a SMB server (Freebox Server, which uses Linux ksmbd) whose behavior when receiving SmbComNegotiate packet is to simply FIN the TCP connection.
This lead to raising an exception when connecting:
```
Caused by: java.io.IOException: transport closed in negotiate
   at jcifs.smb.SmbTransportImpl.negotiatePeek(SmbTransportImpl.java:604)
   at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:512)
   at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:706)
   at jcifs.util.transport.Transport.run(Transport.java:742)
```

Setting auth to SMBv2-only works around the issue.

I made this patch that works to handle that:
```
diff --git a/src/main/java/jcifs/smb/SmbTransportImpl.java b/src/main/java/jcifs/smb/SmbTransportImpl.java
index b170312..ba95b8d 100644
--- a/src/main/java/jcifs/smb/SmbTransportImpl.java
+++ b/src/main/java/jcifs/smb/SmbTransportImpl.java
@@ -509,7 +509,22 @@ class SmbTransportImpl extends Transport implements SmbTransportInternal, SmbCon
 
             SmbComNegotiate comNeg = new SmbComNegotiate(getContext().getConfig(), this.signingEnforced);
             int n = negotiateWrite(comNeg, true);
-            negotiatePeek();
+            try {
+                negotiatePeek();
+            } catch(IOException e) {
+                log.debug("Got an IO error while trying SMB1+2 neg. Trying SMB2-only");
+                this.smb2 = true;
+                try {
+                    this.out.close();
+                } catch(IOException e2) {}
+                try {
+                    this.in.close();
+                } catch(IOException e2) {}
+                try {
+                    this.socket.close();
+                } catch(IOException e2) {}
+                return negotiate(prt);
+            }
 
             SmbNegotiationResponse resp = null;
```

I'm pretty sure it's way too ugly hence I didn't bother to do a PR yet.
Would you have directions on how would you make it cleanly?

You can temporarily find a pcap of that issue https://treble.phh.me/str2.pcap

**Comment by phhusson** [comment]
Server-side agreed that it is their own fault, and fixed it, so I'm closing this issue.
