### ISSUE TITLE
SmbFile.isDirectory() throwing jcifs.smb.SmbException: The network name cannot be found

### ISSUE THREAD

**Issue by SteveGreatApe** [AgNO3/jcifs-ng#38]
Hi, just started using jcifs-ng, great to see this being actively developed as the original did have quite a few issues.

I've hit a problem with isDirectory() throwing "jcifs.smb.SmbException: The network name cannot be found" when I call it on a SmbFile  for a server retrieved like this:

```
        SmbFile smbFolder = new SmbFile("smb://WORKGROUP", cifsContext);
        SmbFile[] smbFiles = smbFolder.listFiles();
        smbFiles[0].isDirectory();
```

However if I create a copy of the SmbFile like this it works okay.
```
        SmbFile smbFolder = new SmbFile("smb://WORKGROUP", cifsContext);
        SmbFile[] smbFiles = smbFolder.listFiles();
        SmbFile clone = new SmbFile(smbFiles[0].getPath(), cifsContext);
        clone.isDirectory();
```
This is running on Android with a snapshot of code grabbed on 4th Feb, the CIFSContext has "jcifs.smb.client.enableSMB2" set to "false" as the listFiles() call failed otherwise.

**Comment by SteveGreatApe** [comment]
Another issue with isDirectory. If I call isDirectory() on a password protected folder it throws SmbAuthException, whereas the original jcifs would have just returned true. This is with SMB2 enabled as I needed to do that to browse the Server contents.

**Comment by mbechler** [comment]
So, the first issue is with smb://_WORKGROUP_, as in you are trying to enumerate servers? I'll look into the isDirectory() issue but as you seem to have already found, there is no support for enumerating servers with SMB2 enabled (cf. #22). 

Stacktraces for the exceptions would be helpful.

For the SmbAuthException I'm not so sure I like the behavior of just returning isDirectory()==true on failure, I couldn't quickly find a change like that but I might even have changed that intentionally at some point.

**Comment by SteveGreatApe** [comment]
Yes, I'm enumerating servers, which seems to work okay once I've disabled SMB2. As it happens due to the need to switch to an SMB2 enabled context I have to recreate the SmbFile for the Server with the new context anyway, so it naturally works around the problem.

Here's the call stack for that first problem. 
```
	  at jcifs.smb.SmbException.<init>(SmbException.java:156)
	  at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1372)
	  at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1540)
	  at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	  at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1506)
	  at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1470)
	  at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:873)
	  at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:480)
	  - locked <0x15bc> (a jcifs.smb.SmbTransportImpl)
	  at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
	  at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
	  at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	  at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	  - locked <0x15c0> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	  - locked <0x15c0> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	  at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:548)
	  - locked <0x15a9> (a jcifs.smb.SmbFile)
	  at jcifs.smb.SmbFile.exists(SmbFile.java:824)
	  at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1046)
	  at com.greatape.media.NetworkGallery.readFileList(NetworkGallery.java:112)
```

**Comment by SteveGreatApe** [comment]
This is the call stack for the SmbAuthException:
```
	  at jcifs.smb.SmbException.<init>(SmbException.java:156)
	  at jcifs.smb.SmbAuthException.<init>(SmbAuthException.java:39)
	  at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1406)
	  at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1535)
	  at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	  at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1506)
	  at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:548)
	  at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
	  - locked <0x1670> (a jcifs.smb.SmbTransportImpl)
	  at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
	  at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
	  at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	  - locked <0x1670> (a jcifs.smb.SmbTransportImpl)
	  at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	  - locked <0x165b> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	  - locked <0x165b> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	  at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:548)
	  - locked <0x165d> (a jcifs.smb.SmbFile)
	  at jcifs.smb.SmbFile.exists(SmbFile.java:824)
	  at jcifs.smb.SmbFile.isDirectory(SmbFile.java:1046)
	  at com.greatape.media.NetworkGallery.readFileList(NetworkGallery.java:111)
```

Probably the same thing, I also get SmbAuthException calling getType() on the file.
```
	  at jcifs.smb.SmbException.<init>(SmbException.java:156)
	  at jcifs.smb.SmbAuthException.<init>(SmbAuthException.java:39)
	  at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1406)
	  at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1535)
	  at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	  at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1506)
	  at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:548)
	  at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
	  - locked <0x1657> (a jcifs.smb.SmbTransportImpl)
	  at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
	  at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
	  at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	  - locked <0x1657> (a jcifs.smb.SmbTransportImpl)
	  at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	  - locked <0x165b> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	  - locked <0x165b> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	  at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:548)
	  - locked <0x165d> (a jcifs.smb.SmbFile)
	  at jcifs.smb.SmbFile.getType(SmbFile.java:875)
	  at com.greatape.media.NetworkGallery.readFileList(NetworkGallery.java:90)

```
