### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by casolorz** [AgNO3/jcifs-ng#43]
I put out another beta with the latest master branch as of last weekend and got this report over crashlytics. No idea how to reproduce it. 

```
Caused by java.lang.ClassCastException: jcifs.smb.NtlmPasswordAuthenticator cannot be cast to jcifs.smb.NtlmPasswordAuthentication
       at jcifs.smb.NtlmPasswordAuthentication.equals(NtlmPasswordAuthentication.java:169)
       at java.util.Objects.equals(Objects.java:59)
       at jcifs.smb.SmbSessionImpl.matches(SmbSessionImpl.java:335)
       at jcifs.smb.SmbTransportImpl.getSmbSession(SmbTransportImpl.java:363)
       at jcifs.smb.SmbTransportImpl.getSmbSession(SmbTransportImpl.java:333)
       at jcifs.smb.SmbTransportImpl.getSmbSession(SmbTransportImpl.java:104)
       at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:615)
       at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
       at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
       at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:143)
       at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:216)
       at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
       at jcifs.smb.SmbFile.listFiles(SmbFile.java:1182)

```

**Comment by mbechler** [comment]
Thanks. Introduced with password auth changes for #36
