### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by casolorz** [AgNO3/jcifs-ng#45]
There seems to be a chance that the properties change while going through the iterator, probably an Android thing. I've only had a few crash reports on Crashlytics. 

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:776)
       at java.util.Hashtable.putAll(Hashtable.java:424)
       at jcifs.context.SingletonContext.init(SingletonContext.java:72)
       at jcifs.context.SingletonContext.getInstance(SingletonContext.java:92)
       at jcifs.context.SingletonContext.registerSmbURLHandler(SingletonContext.java:129)
       at jcifs.Config.registerSmbURLHandler(Config.java:70)
```

**Comment by mbechler** [comment]
That should be ```p.putAll(System.getProperties());``` which really can only fail if another thread is modifiying the system properties. I don't think there is anything meaningful I can do about that - you'll have to find out what is modifying the system properties and add synchroization between that and the init() call.

**Comment by casolorz** [comment]
Unfortunately I'm not modifying them, which means it is either some library or android itself doing it at that time. But yeah I understand that you can't do anything about it. It is probably happening at startup so maybe I can just delay `jcifs` a little bit.
