### ISSUE TITLE
Failed connect to NetApp: throwing SmbException: 0xC0000001

### ISSUE THREAD

**Issue by guybmayor** [AgNO3/jcifs-ng#50]
Failed to connect to NetApp server (with SMB1/SMB2) although I successes with pure JCIFS and from smbclient throwing:

jcifs.smb.SmbException: 0xC0000001
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1424)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1535)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1506)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:548)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
	at jcifs.smb.SmbFile.connect(SmbFile.java:509)

**Comment by mbechler** [comment]
That error unfortunately is very generic (STATUS_UNSUCCESSFUL), I'm definitely going to need more info. Debug logs + packet traces of the failing and a working session setup would be great.

Which version are you using? There are some NTLM changes in master, so it might be interesting to check whether that happens with both.

We have another open session setup issue  (#46)  with a proprietary server implementation, maybe these are related.

**Comment by mbechler** [comment]
Observations:
- sending that supportedMech probably is not quite right at that point
- we are sending the SPNEGO mechListMIC while the other impl is not.

Setting jcifs.smb.useRawNTLM=true should remove both potential issues. So that would be a good thing to check first.

If that works the next thing to check would be whether it works when setting 
jcifs.smb.client.disableSpnegoIntegrity=true instread. That way we should be able
to find out whether it is MIC related or not.

**Comment by guybmayor** [comment]
unfortunately it's still not working. 
when I'm trying to set jcifs.smb.useRawNTLM=true I getting:
![image](https://user-images.githubusercontent.com/24632568/36670140-f636d2ec-1aff-11e8-8b99-da9899241ddd.png)

and the answer is:
![image](https://user-images.githubusercontent.com/24632568/36670184-1953813a-1b00-11e8-99ac-00737e289524.png)

Don't know if it makes any difference but on the working impl the NTLMv2 Response look like this:
![image](https://user-images.githubusercontent.com/24632568/36670507-4df51bdc-1b01-11e8-98b6-e0eb5bf3d9d2.png)

and on jcisf-ng its:
![image](https://user-images.githubusercontent.com/24632568/36670343-b5a84700-1b00-11e8-960b-9858673f768b.png)

BTW
set jcifs.smb.client.disableSpnegoIntegrity=true give my the same error as before

**Comment by mbechler** [comment]
The response to _useRawNTLM=true_ shows **STATUS_SUCCESS**, so that might be the wrong screenshot?
If so, I think we have pinned down the issue to be the NTLM messages.

Yes, the NTLM response details would have been the next thing to ask for ;)

Working has MsvAvTargetName but not MsvAvTimestamp. I believe MsvAvTargetName should be optional, the Timestamp however may be interesting as it is involved in the magic to determine whether a MIC is required/checked or not.

Definitely not a valid patch, but just for testing you could try removing the Timestamp from the response:
```
diff --git a/src/main/java/jcifs/ntlmssp/Type3Message.java b/src/main/java/jcifs/ntlmssp/Type3Message.java
index 5a5baab..28bc5e9 100644
--- a/src/main/java/jcifs/ntlmssp/Type3Message.java
+++ b/src/main/java/jcifs/ntlmssp/Type3Message.java
@@ -247,7 +247,7 @@ public class Type3Message extends NtlmMessage {
             AvPairs.replace(serverAvPairs, new AvFlags(curFlags));
         }
 
-        AvPairs.replace(serverAvPairs, new AvTimestamp(ts));
+        //AvPairs.replace(serverAvPairs, new AvTimestamp(ts));
 
         if ( targetName != null ) {
             AvPairs.replace(serverAvPairs, new AvTargetName(targetName));
```


Is the server sending a Timestamp in the NTLM Challenge's Target Info? What kind of client is the working one? If not samba, can you check whether that behaves the same (there I can look up what kind of logic they are using). If you can supply the raw PCAP files that might speed up things a bit.

**Comment by guybmayor** [comment]
I have tried to remove the Timestamp but it is didn't worked.
attachecd the PCAP files
the working client is windows 10 explorer

[netapp pcap.zip](https://github.com/AgNO3/jcifs-ng/files/1778336/netapp.pcap.zip)

**Comment by mbechler** [comment]
That "non working" PCAP actually looks like the session setup completed. This is causing the mentioned exception?

Setting that aside from that the linked patch should further align the negotiated flags to make sure that is not the problem.

**Comment by guybmayor** [comment]
OK, let me make on order with everything...
1. Setting the jcifs.smb.useRawNTLM=true did change the error to jcifs.smb.SmbException: Signature validation failed. Debug logs:

> 2018-03-04 12:48:09.913 DEBUG [jcifs.smb.SmbResourceLocatorImpl] (default task-7) Share is IPC null
> 2018-03-04 12:48:09.928 DEBUG [jcifs.smb.SmbTransportPoolImpl] (default task-7) New transport connection Transport0[0.0.0.0<00>/52.35.32.245:445,state=0,signingEnforced=true,usage=1]
> 2018-03-04 12:48:09.928 DEBUG [jcifs.util.transport.Transport] (default task-7) Connecting Transport0
> 2018-03-04 12:48:09.929 DEBUG [jcifs.smb.SmbTransportImpl] (Transport0) Connecting in state 1 addr 52.35.32.245
> 2018-03-04 12:48:10.636 DEBUG [jcifs.smb.SmbTransportImpl] (Transport0) Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@5303cedc
> 2018-03-04 12:48:10.637 DEBUG [jcifs.smb.SmbTransportImpl] (Transport0) Signature negotiation enforced true (server true) enabled false (server true)
> 2018-03-04 12:48:10.646 DEBUG [jcifs.smb.SmbTransportImpl] (default task-7) Establishing new session SmbSession[credentials=itsmine\guy,targetHost=52.35.32.245,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
> 2018-03-04 12:48:10.654 DEBUG [jcifs.smb.SmbTreeImpl] (default task-7) treeConnect: unc=\\52.35.32.245\IPC$,service=?????
> 2018-03-04 12:48:10.657 DEBUG [jcifs.smb.SmbSessionImpl] (default task-7) sessionSetup: itsmine\guy
> 2018-03-04 12:48:10.658 DEBUG [jcifs.smb.SmbSessionImpl] (default task-7) Remote host is 52.35.32.245
> 2018-03-04 12:48:10.916 DEBUG [jcifs.smb.SmbTransportImpl] (default task-7) Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byteCount=0
> 2018-03-04 12:48:10.973 DEBUG [jcifs.smb.NtlmContext] (default task-7) Sign key is 17547AADFBACA95D318B851A06C248BE
> 2018-03-04 12:48:10.973 DEBUG [jcifs.smb.NtlmContext] (default task-7) Verify key is B8244878535E718DB3DDA5AE8A316504
> 2018-03-04 12:48:10.975 DEBUG [jcifs.smb.NtlmContext] (default task-7) Seal key is B19051D4F97B7BD3486A7340BAA60F72
> 2018-03-04 12:48:10.975 DEBUG [jcifs.smb.NtlmContext] (default task-7) Server seal key is 28E492AE99BF7F7CFC681EF7987118FD
> 2018-03-04 12:48:11.215 DEBUG [jcifs.smb.SmbSessionImpl] (default task-7) Context is established
> 2018-03-04 12:48:11.227 ERROR [jcifs.internal.smb2.Smb2SigningDigest] (default task-7) The server did not sign a message we expected to be signed
> 2018-03-04 12:48:11.233 DEBUG [jcifs.smb.SmbSessionImpl] (default task-7) Session setup failed
> jcifs.smb.SmbException: Signature validation failed
> 	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:607)
> 	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
> 	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
> 	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
> 	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
> 	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
> 	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
> 	at jcifs.smb.SmbFile.connect(SmbFile.java:509)
> 2018-03-04 12:48:11.234 DEBUG [jcifs.smb.SmbTreeImpl] (default task-7) Disconnect tree on treeConnectFailure
> jcifs.smb.SmbException: Signature validation failed
> 	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:607)
> 	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
> 	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
> 	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
> 	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
> 	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
> 	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
> 	at jcifs.smb.SmbFile.connect(SmbFile.java:509)
> 2018-03-04 12:48:11.235 DEBUG [jcifs.smb.SmbTreeImpl] (default task-7) Usage dropped to zero, release session
> 2018-03-04 12:48:11.235 DEBUG [jcifs.smb.SmbSessionImpl] (default task-7) Usage dropped to zero, release connection Transport0[0.0.0.0<00>/52.35.32.245:445,state=3,signingEnforced=true,usage=2]
> 2018-03-04 12:48:11.235 WARN  [jcifs.smb.SmbTreeConnection] (default task-7) Referral failed, trying next
> jcifs.smb.SmbException: Signature validation failed
> 	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:607)
> 	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
> 	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
> 	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
> 	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
> 	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
> 	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
> 	at jcifs.smb.SmbFile.connect(SmbFile.java:509)
> 2018-03-04 12:48:11.242 ERROR [fileServers.SMBServer] (default task-7) Failed to connect using connect. Furher details: itsmine/guy@52.35.32.245
> jcifs.smb.SmbException: Signature validation failed
> 	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:607)
> 	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:477)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341)
> 	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
> 	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
> 	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
> 	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
> 	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
> 	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
> 	at jcifs.smb.SmbFile.connect(SmbFile.java:509)
> 	at fileServers.SMBServer.connect(SMBServer.java:188)
> 	at fileServers.SMBServer.connect(SMBServer.java:158)

and the response is as I post before with Security Blob: <MISSING>: NO DATA
2. The negotiated flags are not making any change.
3. Don't know if it makes any change but, I tried to make some code change, and I find that if I change this src:
![image](https://user-images.githubusercontent.com/24632568/36945184-16cb60ec-1fb3-11e8-83e5-c237da1e88b1.png)

And set the jcifs.smb.client.disableSpnegoIntegrity=true (jcifs.smb.useRawNTLM=false).
I am getting the same error as before but now the return from the server is looking OK:
![image](https://user-images.githubusercontent.com/24632568/36945273-056f472c-1fb4-11e8-918a-9c1af8751c29.png)

**Comment by mbechler** [comment]
The SPEGNO selectedMech change is good, I even had that somewhere but it seems have not committed it.

So in summary we now have:
-  jcifs.smb.useRawNTLM=false/jcifs.smb.client.disableSpnegoIntegrity=true -> Signature validation failed
-  jcifs.smb.useRawNTLM=false/jcifs.smb.client.disableSpnegoIntegrity=false -> unknown server error 
- jcifs.smb.useRawNTLM=true -> Signature validation failed

which sounds a lot like there is some disagreement on the session key. If the server is not checking the NTLM MIC but is checking the SPNEGO mechListMIC that would explain the seen behavior.
Let's hope that isn't a subtle issue in the actual key calculations, that would be pretty nasty to debug without debug access to the other side.

Another thing to notice is that we are sending a LM response (conditional on the absence of AvTimestamp).
You could try to force sending an all-zero LMResponse in Type3Message.java:179
```
            boolean haveTimestamp = AvPairs.contains(avPairs, AvPair.MsvAvTimestamp);
            if ( !haveTimestamp ) {
                byte[] lmClientChallenge = new byte[8];
                tc.getConfig().getRandom().nextBytes(lmClientChallenge);
                setLMResponse(getLMv2Response(tc, type2, domain, user, password, lmClientChallenge));
            }
            else {
                setLMResponse(new byte[24]);
            }
```

**Comment by guybmayor** [comment]
So I did some debugging and found out 2 things:
1. 
on src\main\java\jcifs\internal\smb2\Smb2Constants.java:
public static final int SMB2_NEGOTIATE_SIGNING_ENABLED = 0x0001;
and also
public static final int SMB2_NEGOTIATE_SIGNING_REQUIRED = 0x0001;
(Should be 0x0002)

2.
In the SMB2 SESSION_SETUP Request documentation (https://msdn.microsoft.com/en-us/library/cc246563.aspx) says that the security mode is:
   A. not efected from the response.
   B. should alwas by set to SMB2_NEGOTIATE_SIGNING_ENABLED or SMB2_NEGOTIATE_SIGNING_REQUIRED but one of them must be set.

After I see those issues I make some code changes I solved the problem.
You can see the changes in my pull request:
[](https://github.com/AgNO3/jcifs-ng/pull/55)

**Comment by guybmayor** [comment]
I also add  jcifs.smb.client.ipcSigningEnforced = false conf

**Comment by mbechler** [comment]
Regarding SIGNING_ENABLED/SIGNING_REQUIRED I know that the specification says that but samba sets both, too.

I think you only managed to disable any signing so that the issue is not showing :|

**Comment by mbechler** [comment]
Maybe it would be a good idea to verify whether samba and windows clients are able to connect to the netapp with signing enforced/enabled. Just to make sure that we are not chasing a netapp bug.

**Comment by guybmayor** [comment]
yes you are right it is work with booth with samba. but the SIGNING_ENABLED is always on.
so I set for all request to have SIGNING_ENABLED on in default.

I start to check way the jcifs.smb.client.ipcSigningEnforced get me a problems and I found that src\main\java\jcifs\smb\SmbTreeImpl.java:703 the request securityMode is always set to 1 (SIGNING_ENABLED) and because the default ipcSigningEnforced  is true its wrong.

please check put my new pull request

**Comment by mbechler** [comment]
You are probably right about the SmbTreeImpl security_mode. 
I think the SmbSessionImpl change still does not look right to me, I think that only enabled signing when enforced.

What's the situation now? Are there any combination which actually enable signing and work for you? What are the minimal changes you have to make to get it to work?

Sorry for the delays, but I don't think I can get deeper into that before the weekend.

**Comment by guybmayor** [comment]
The SmbSessionImpl change is required in case that the client and the server doesn't require signing because the isSigningNegotiated method will always return true.

the pull request work with windows server 2016/2012 and NetApp 9.3 with and without signing required.

**Comment by mbechler** [comment]
Okay, I think I'm getting it now :)

- You are right, setting SIGNING_ENABLED is mandatory, no matter what, so this cannot part of a negotiation of any kind.
- For negotiating a signing preference I can see the samba client sending SMB_NEGOTIATE_SIGNING_REQUIRED for negotiation, but then ignoring it when the server does not actually enable signing. 
- That leaves the question on how to determine whether signing should be enabled, and I have the feeling that the current way of things might not be quite right. I'm not sure the current way of determining that on session basis is even possible and it looks to me that the spec would even allow for asymmetric configurations.
- We have to be careful as the SmbSessionImpl.isSignatureSetupRequired code also affects SMB1.

**Comment by mbechler** [comment]
I think the better workaround for now would be to let Smb2NegotiateResponse.isSigningNegotiated() return false.

**Comment by guybmayor** [comment]
- I accept your commit Smb2NegotiateResponse.isSigningNegotiated() instead the SmbSessionImpl.isSignatureSetupRequired that code also affects SMB1.

- And still, it is working for my only is I set SMB2_NEGOTIATE_SIGNING_REQUIRED = 0x0002 and return the relevant security mode on Smb2NegotiateRequest in src\main\java\jcifs\smb\SmbTreeImpl.java:703 - 
those changes are support the documentations ans the samba client implementation.

- Also notice that on one of my client servers. the security mode was only enable but on the Smb2SessionSetupResponse the signed flag was on. so I add 2 more changes.

you can see all changes in my updated pull request

**Comment by mbechler** [comment]
Yes, the SMB2_NEGOTIATE_SIGNING_REQUIRED = 0x1 and SmbTreeImpl are definite bugs.
I'v merged most of your changes, some in a slightly different way.

However I'm still not entirely convinced that the signing negotiation is completely correct.
Enabling signing based on the fact that the server signed the final SessionSetup response seems reasonable, however in #57 and #60 we have seen that there are servers which do not sign that even though signing should be enabled. 

I've been going through the specification again and again but can't make sense of what the relation of securityMode during negotiation, during session setup and actual signing enablement/requirement should be.

**Comment by guybmayor** [comment]
Thanks for all the support and fixes.
It seems that everything is working now 👍 😄
