### ISSUE TITLE
got UnknowHostException and timedout trying to connect to domain controller (Windows 2008 R2)

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#53]
We are trying to connect to Windows 2008 R2 server using credentials as 'ed\username' 'passxxxx'
Can you review and provide inputs for these 2 questions:

1) We use credentials as 'ed\username'; however, we see jcifs-ng tied to connect to 'ed' at first?
	[2018-02-22 22:14:30,955] DEBUG [1640446703@qtp--1559202494-2] jcifs.smb.DfsImpl Getting domain controller for ed failed
java.net.UnknownHostException: ed
	at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:1022) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:53) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:170) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:189) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:234) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:348) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:322) [jcifs-ng-2.0.1-flx.1.jar:?]

2) We got sendrecv timedout.  
We tried to increase the timeout property from 35s to 70s, but still got the timedout at jcifs.util.transport.Transport.waitForResponses after the failure of 'java.net.UnknownHostException: ed'
Why it waited for the timedout if it already failed with the 'UnknownHostException'.  We observed with other case where after the failure of connection to the domain controller 'ed', it tried to connect using the correct credentials 'ed\username' successfully.
 .
	[2018-02-22 22:14:30,955] DEBUG [1640446703@qtp--1559202494-2] jcifs.smb.DfsImpl Getting domain controller for ed failed
java.net.UnknownHostException: ed
	at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:1022) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:53) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:170) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:189) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:234) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:348) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:322) [jcifs-ng-2.0.1-flx.1.jar:?]
   ...
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.26.jar:6.1.26]
[2018-02-22 22:14:30,956] DEBUG [1640446703@qtp--1559202494-2] jcifs.smb.SmbTreeImpl treeConnect: unc=\\192.168.nnn.nn\AUTOSHARED1,service=?????

[2018-02-22 22:15:40,956] DEBUG [1640446703@qtp--1559202494-2] jcifs.util.transport.Transport State is 3
[2018-02-22 22:15:40,957] WARN  [1640446703@qtp--1559202494-2] jcifs.util.transport.Transport sendrecv failed
jcifs.util.transport.RequestTimeoutException: Transport1 timedout waiting for response to command=SMB2_TREE_CONNECT,status=0,flags=0x0000,mid=14646,wordCount=0,byteCount=64
	at jcifs.util.transport.Transport.waitForResponses(Transport.java:365) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.util.transport.Transport.sendrecv(Transport.java:232) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:973) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1470) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:605) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:558) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:457) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:418) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:642) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.getServerTime(SmbFile.java:2488) [jcifs-ng-2.0.1-flx.1.jar:?]
[2018-02-22 22:15:40,958] WARN  [1640446703@qtp--1559202494-2] jcifs.smb.SmbTransportImpl Disconnecting transport while still in use Transport1[0.0.0.0<00>/192.168.nnn.nn:445,state=5,signingEnforced=false,usage=6]: [SmbSession[credentials=ed\username,targetHost=192.168.nnn.nn,targetDomain=null,uid=0,connectionState=2,usage=5]]
[2018-02-22 22:15:40,958] DEBUG [1640446703@qtp--1559202494-2] jcifs.smb.SmbTransportImpl Disconnecting transport Transport1[0.0.0.0<00>/192.168.nnn.nn:445,state=5,signingEnforced=false,usage=6]
[2018-02-22 22:15:40,958] DEBUG [1640446703@qtp--1559202494-2] jcifs.smb.SmbSessionImpl Logging off session on Transport1[0.0.0.0<00>/192.168.nnn.nn:445,state=5,signingEnforced=false,usage=7]
[2018-02-22 22:15:40,958] WARN  [1640446703@qtp--1559202494-2] jcifs.smb.SmbSessionImpl Logging off session while still in use SmbSession[credentials=ed\username,targetHost=192.168.nnn.nn,targetDomain=null,uid=0,connectionState=3,usage=5]:[SmbTree[share=AUTOSHARE1,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=0], SmbTree[share=AUTOSHARED1,service=?????,tid=0,inDfs=false,inDomainDfs=false,connectionState=1,usage=1]]

Thanks in advance,

**Comment by mbechler** [comment]
Connecting to _ED_ is part of the DFS code trying to figure out the domain controllers for the user domain. You seem to be using a short domain name and probably don't have a working NetBIOS environment (broadcast not possible, no wins configured).
I would strongly suggest using only long domain names if possible.

 I don't think the second issue is related to the first one. Is that reliably reproducable? Could be an actual networking problem. Otherwise that could be either that the server does not like the request, or that maybe we are somehow missing the response. Packet trace would be good for figuring that out.

**Comment by thanh-vn** [comment]
Thanks for the response.

For the second issue, it is not easy to reproduce it; because this be a concurrency issue where at the time it happens there are multiple requests to getConnection very first time to a same host.   This error only happens once during the long test.
Can you help if there is any suggestion on how to debug this futher? In the mean time we will try to minimize the test to be smaller and will try to collect packets trace.

Thanks,

**Comment by mbechler** [comment]
Getting the debugger to trigger on the condition and suspending the whole VM to get stack traces of all threads at the same time would likely help a lot but that admittedly may not be easy to get (or even possible).

I'll see if I can find a way to reproduce that. If you can find a more isolated test case that would be great.

**Comment by thanh-vn** [comment]
We will try to create testcase more isolated to the problem area and update this case.
Thanks,

**Comment by thanh-vn** [comment]
Closing this for now.  Will get to this concurrency issue again if I can get the stack traces of all the threads at the time when the problem happens.
Thanks,
