### ISSUE TITLE
jcifs.smb.SmbException: Signature validation failed

### ISSUE THREAD

**Issue by hmkmajeed** [AgNO3/jcifs-ng#57]
I am getting the above error while transferring the file through SMB2.

Below is my current setup:
Jar version: 
latest version jcifs-ng-2.0.5

environment properties: 
wrapper.java.additional.7=-Djcifs.smb.client.signingPreferred=true
wrapper.java.additional.8=-Djcifs.smb.client.signingEnforced=true
wrapper.java.additional.9=-Djcifs.smb.client.ipcSigningEnforced=true
wrapper.java.additional.10=-Djcifs.smb.client.enableSMB2=true
wrapper.java.additional.11=-Djcifs.smb.client.disableSMB1=true

Log/error details:
ERROR jcifs.internal.smb2.Smb2SigningDigest - The server did not sign a message we expected to be signed
INFO   | jvm 1    | 2018/03/07 23:14:38 | 2018-03-07 23:14:38,725 [.Export.0] ERROR com.seccas.task.CreateCollectionFile - Errored CreateCollectionFile task: ClientID=38, SupervisorID=1580021, CollectionID=281229, FileName='testcollex'
INFO   | jvm 1    | 2018/03/07 23:14:38 | jcifs.smb.SmbException: Signature validation failed
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:646)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:463)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:358)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at jcifs.smb.SmbFile.exists(SmbFile.java:821)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at com.seccas.task.CreateCollectionFile.copyCollectionMessages(CreateCollectionFile.java:770)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at com.seccas.task.CreateCollectionFile.futureTaskRun(CreateCollectionFile.java:127)
INFO   | jvm 1    | 2018/03/07 23:14:38 |   at com.seccas.util.SeccasTaskThread.run(SeccasTaskThread.java:46)
INFO   | jvm 1    | 2018/03/07 23:14:39 | 2018-03-07 23:14:39,179 [..Export.0] ERROR com.seccas.util.SeccasTaskThread - Error running task
INFO   | jvm 1    | 2018/03/07 23:14:39 | jcifs.smb.SmbException: Signature validation failed
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:646)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:463)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:358)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at jcifs.smb.SmbFile.exists(SmbFile.java:821)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at com.seccas.task.CreateCollectionFile.copyCollectionMessages(CreateCollectionFile.java:770)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at com.seccas.task.CreateCollectionFile.futureTaskRun(CreateCollectionFile.java:127)
INFO   | jvm 1    | 2018/03/07 23:14:39 |   at com.seccas.util.SeccasTaskThread.run(SeccasTaskThread.java:46)
DEBUG  | wrapperp | 2018/03/07 23:14:40 | Send a packet PING : ping fffffe35
INFO   | jvm 1    | 2018/03/07 23:14:40 | WrapperManager Debug: Received a packet PING : ping fffffe35
INFO   | jvm 1    | 2018/03/07 23:14:40 | WrapperManager Debug: Send a packet PING : ping fffffe35
DEBUG  | wrapperp | 2018/03/07 23:14:40 | read a packet PING : ping fffffe35

Any idea on this? may I missed any settings?

**Comment by mbechler** [comment]
As you use _jcifs.smb.client.signingEnforced=true_ there is a chance that your server might just have signing disabled.
Another possiblity would be that we do not properly detect a guest connection (for which signing is not possible, so this should cause another error if you did not request guest auth).

And last but not least the server implemenation (what kind of server is this?) might not sign the final SessionSetup response (or we consider the session setup done and it is actually not for the server).  The specification might not be absolutely clear on that so there is a chance that someone might have interpreted it differently (only for 3.x I can see a MUST).

A packet trace would be helpful.

**Comment by hmkmajeed** [comment]
Many Thanks @mbechler for the response.

I've set the jcifs.smb.client.signingEnforced=false and run the test again and below is the SessionSetup response and Tree Connect response packet trace:

Tree_Connect response:
<img width="770" alt="tree_connect_response" src="https://user-images.githubusercontent.com/34904404/37328256-7bfa1080-26d4-11e8-9826-799aa72e96bf.png">

Session_Setup response:
<img width="755" alt="session_setup_response" src="https://user-images.githubusercontent.com/34904404/37328291-9b63bee4-26d4-11e8-9f19-3c22c0f03a61.png">

The other properties I used as below:
-Djcifs.smb.client.enableSMB2=true 
-Djcifs.smb.client.signingPreferred=false 
-Djcifs.smb.client.signingEnforced=false 
-Djcifs.smb.client.ipcSigningEnforced=false 
-Djcifs.smb.useRawNTLM=true

**Comment by mbechler** [comment]
In #50 we are found that the current handling of the session security_mode is wrong.  This looks it might also be an artifact of it (although I'm not completely sure yet how the proper fix would look like)

**Comment by hmkmajeed** [comment]
@mbechler, do we have any update on this? Any additional info you need for this to move on. I have tried with SNAPSHOPT version (2.1.0-SNAPSHOT) just to test the same issue, however i didn't get any differences still failing.

**Comment by mbechler** [comment]
If it's none of the issues we already fixed recently I'm going to need more details (preferrably debug logs and full packet trace). What kind of NAS is that?

If you set all of 
-Djcifs.smb.client.signingPreferred=false
-Djcifs.smb.client.signingEnforced=false
-Djcifs.smb.client.ipcSigningEnforced=false
you are still getting "The server did not sign a message we expected to be signed"?

**Comment by chidu106** [comment]
@mbechler @hmkmajeed - Where do i set these properties. I set them in intellij VM options, but didnt get picked.

**Comment by mbechler** [comment]
Unless the PropertyConfiguration is not initialized from the system properties, this should work. Looks like there is some spring code involved, you would have to check/debug how they initialize it.
