### ISSUE TITLE
UnknownHostException ?????

### ISSUE THREAD

**Issue by himeroza** [AgNO3/jcifs-ng#58]
I try to list my folder on path
String path = smb://wawa.local/DFS/Shared/MT4 i Vibank/pdf_files_test/daily/

Properties smbPrt = new Properties();
smbPrt.setProperty( "jcifs.smb.client.domain", WAWA);
smbPrt.setProperty( "jcifs.smb.client.username", him );
smbPrt.setProperty( "jcifs.smb.client.password", 123456 );

after this config i have a code like this:
```
try ( SmbFile smbFile = new SmbFile( path, new BaseContext( new PropertyConfiguration( smbPrt ) ) ) )
		{
			List<SmbFile> filesList = new ArrayList<SmbFile>( Arrays.asList( smbFile.listFiles( getSmbFileFilter( lDate, isCorrectionFile ) ) ) );
		}
		catch ( Exception e )
		{
			logger.error( e.getMessage(), e );
		}
```
and then i have an exception:

2018-03-08 12:55:44.938|DEBUG|pool-22-thread-1|DfsImpl.getDcReferrals|Getting domain controller for WAWA failed
java.net.UnknownHostException: WAWA
        at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:1025)
        at jcifs.netbios.NameServiceClientImpl.getAllByName(NameServiceClientImpl.java:54)
        at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:170)
        at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
        at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:189)
        at jcifs.smb.DfsImpl.getDc(DfsImpl.java:234)
        at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112)
        at jcifs.smb.DfsImpl.resolve(DfsImpl.java:348)
        at jcifs.smb.DfsImpl.resolve(DfsImpl.java:322)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:525)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:219)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1253)
        at bos.synchro.executors.TransFiles.getTransFilesMtList(TransFiles.java:860)
        at bos.synchro.executors.TransFiles.genTransFilesMtCorrections(TransFiles.java:762)
        at bos.synchro.executors.TransFiles.run(TransFiles.java:173)
        at bos.synchro.ServerExecutors$RunnableWrapper.run(ServerExecutors.java:201)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:319)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:191)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:795)

**Comment by mbechler** [comment]
As described in https://github.com/AgNO3/jcifs-ng/issues/53#issuecomment-370134619 this is expected if you have DFS enabled and use short domain names without a working NetBIOS configuration. 
I'd generally advice to use long/full domain names but if you don't use DFS you should be able to ignore this.
