### ISSUE TITLE
java.lang.NoClassDefFoundError: jcifs/Credentials

### ISSUE THREAD

**Issue by Jomme5** [AgNO3/jcifs-ng#59]
Got this error: 
java.lang.NoClassDefFoundError: jcifs/CIFSContext
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: jcifs.CIFSContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 

Any ideas what is the cause?

**Comment by mbechler** [comment]
Load errors have the tendency to hide the actual issue, a debugger might help to get to the cause. Best guesses:
1) Missing a dependency/incompatible dependency version (only bouncycastle and slf4j-api are used)
2) Loading the library multiple times

**Comment by Jomme5** [comment]
Funfact: I want to use VSCode tot test some thing out before programming it in Android Studio, with the slow Gradle-build-system. The external jar is compiled with maven btw. It would be nice to use this jar with intellisense and use maven once for building external jars.

**Comment by Jomme5** [comment]
Yes OK - it has something to do with my build system. Something for another github-thread.  ;)
