### ISSUE TITLE
failed to connect to OneFS - SmbTransportImpl.doConnect gets NullPointerException 

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#60]
We are getting NullPointerException when trying to connect to OneFS v 7.2 using SMB2 enable and the properties below:
    jcifs.smb.client.enableSMB2=true
    jcifs.smb.client.signingPreferred=false
    jcifs.smb.client.signingEnforced=false
    jcifs.smb.client.ipcSigningEnforced=false

On the OneFS SMB settings, we have 
    Enable Security Signatures: No
    Require Security Signatures: No
    Support Multichannel: Yes
    Support NetBIOS: No
    Support Smb2: Yes

---------------------------------------
Caused by: jcifs.util.transport.TransportException: java.lang.NullPointerException
    at jcifs.util.transport.Transport.run(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at java.lang.Thread.run(Thread.java:785) ~[?:1.8.0-internal]
Caused by: java.lang.NullPointerException
    at jcifs.smb.SmbTransportImpl.doConnect(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.util.transport.Transport.run(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at java.lang.Thread.run(Thread.java:785) ~[?:1.8.0-internal]
        ............................
    at jcifs.smb.SmbTransportImpl.ensureConnected(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.connectHost(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.connectHost(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.connect(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbTreeConnection.connectWrapException(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbFile.ensureTreeConnected(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
    at jcifs.smb.SmbFile.exists(Unknown Source) ~[jcifs-ng-2.0.1-flx.1.jar:?]
-------------------------------------------

Can you see what may be wrong?  Including is the packet trace, hope we can see better what may be the cause of it.

Thanks in advance!

**Comment by mbechler** [comment]
I think this is #26, patch is at d2d7fc8efc93a4a3f227dca609b09377fe514725

**Comment by thanh-vn** [comment]
----------------------------------
Hi,
We applied #26, got further, but still not successfully pass the signature validation.  Below is the debug tracing.

2018-03-19 19:28:51 DEBUG SmbTransportPoolImpl:93 - New transport connection Transport0[0.0.0.0<00>/172.17.2.155:445,state=0,signingEnforced=true,usage=1]
2018-03-19 19:28:51 DEBUG Transport:568 - Connecting Transport0
2018-03-19 19:28:51 DEBUG SmbTransportImpl:663 - Connecting in state 1 addr 172.17.2.155
2018-03-19 19:28:51 DEBUG SmbTransportImpl:687 - Negotiation response on Transport0 :Smb2NegotiateResponse[command=SMB2_NEGOTIATE,status=0,flags=0x0001,mid=1,wordCount=0,byteCount=0,dialectRevision=514,securityMode=0x1,capabilities=0x00000000,serverTime=Mon Mar 19 19:28:51 UTC 2018
2018-03-19 19:28:51 DEBUG SmbTransportImpl:697 - Signature negotiation enforced true (server true) enabled true (server true)
2018-03-19 19:28:51 DEBUG SmbTransportImpl:381 - Establishing new session SmbSession[credentials=DOMAIN01\userID,targetHost=nnn.nn.n.nnn,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
2018-03-19 19:28:51 DEBUG SmbTreeImpl:580 - treeConnect: unc=\\nnn.nn.n.nnn\SHARE01,service=?????
2018-03-19 19:28:51 DEBUG SmbSessionImpl:451 - sessionSetup: DOMAIN01\userID
2018-03-19 19:28:51 DEBUG SmbSessionImpl:519 - Remote host is nnn.nn.n.nnn
2018-03-19 19:28:51 DEBUG SmbTransportImpl:982 - Breaking on error command=SMB2_ SESSION_SETUP,status=More data is available.,flags=0x0001,mid=2,wordCount=0,byte Count=0
2018-03-19 19:28:53 DEBUG SmbTransportImpl:945 - Insufficient credits, send only first command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 next is command=SMB2_TREE_CONNECT,status=0,flags=0x0000,mid=0,wordCount=0, byteCount=0
2018-03-19 19:28:53 DEBUG SmbTransportImpl:1018 - Server Transport0[0.0.0.0<00>/nnn.nn.n.nnn:445,state=3,signingEnforced=true,usage=5] returned zero credits for command=SMB2_TREE_CONNECT,status=0,flags=0x0000,mid=4,wordCount=0,byteCount=54
2018-03-19 19:28:53 DEBUG SmbSessionImpl:628 - Context is established
2018-03-19 19:28:53 ERROR Smb2SigningDigest:116 - The server did not sign a mess age we expected to be signed
2018-03-19 19:28:53 DEBUG SmbSessionImpl:470 - Session setup failed
jcifs.smb.SmbException: Signature validation failed
        at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:646)
        at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:463)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:358)
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336)
        at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
        at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:575)
        at jcifs.smb.SmbFile.exists(SmbFile.java:852)
        at Test_getOwnerID.main(Test_getOwnerID.java:41)
2018-03-19 19:28:53 DEBUG SmbTreeImpl:210 - Usage dropped to zero, release session
2018-03-19 19:28:53 DEBUG SmbSessionImpl:220 - Usage dropped to zero, release connection Transport0[0.0.0.0<00>/nnn.nn.n.nnn:445,state=3,signingEnforced=true,usage=2]
2018-03-19 19:28:53 WARN  SmbTreeConnection:576 - Referral failed, trying next
jcifs.smb.SmbException: Signature validation failed
---------------------------------Thanks much for looking into this!

**Comment by thanh-vn** [comment]
Hi, 
Somehow I don't see an option to re-open this issue.

**Comment by thanh-vn** [comment]
Hi,
I collected more information about the SMB settings of the oneFS env:
Access Based Enumeration: No
Access Based Enumeration Root Only: No
            Allow Delete Readonly: No
             Allow Execute Always: No
                    Change Notify: norecurse
               Create Permissions: default acl
            Directory Create Mask: 0700
            Directory Create Mode: 0000
                 File Create Mask: 0700
                 File Create Mode: 0100
                   Hide Dot Files: No
                         Host ACL: -
                Impersonate Guest: never
                 Impersonate User:
                Mangle Byte Start: 0XED00
                       Mangle Map: 0x01-0x1F:-1, 0x22:-1, 0x2A:-1, 0x3A:-1, 0x3C:-1, 0x3E:-1, 0x3F:-1, 0x5C:-1
                 Ntfs ACL Support: Yes
                          Oplocks: Yes
                     Strict Flush: Yes
                   Strict Locking: No

I included the packet traces, hope you can help to see the reason for the failure of the signature validation.

Thanks,

[volume_create_fail_20180319_2.zip](https://github.com/AgNO3/jcifs-ng/files/1844455/volume_create_fail_20180319_2.zip)

**Comment by mbechler** [comment]
Could be fixed by 70f0b6e5595b755404940a1a2b0b60bf6d7d4693

**Comment by thanh-vn** [comment]
thanks much, the issue is resolved.
