### ISSUE TITLE
SmbFile.getShareSecurity() throws SmbException for NetApp shares

### ISSUE THREAD

**Issue by djdkedev** [AgNO3/jcifs-ng#71]
Jcifs-ng version: 2.0.6
properties set:
prop.put( "jcifs.smb.client.enableSMB2", "true");
prop.put( "jcifs.smb.client.disableSMB1", "false");
NetApp version: The ONTAP version is 9, The SMB1, SMB2, SMB3 are enabled by default.

SmbException:
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/<ip>
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:651)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbPipeHandleImpl.ensureTreeConnected(SmbPipeHandleImpl.java:111)
	at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:166)
	at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
	at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
	at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
	at jcifs.smb.SmbFile.getShareSecurity(SmbFile.java:2331)
	at JcifsNgTest.main(JcifsNgTest.java:56)
Caused by: jcifs.util.transport.TransportException: jcifs.smb.SmbException: This client is not compatible with the server.
	at jcifs.util.transport.Transport.run(Transport.java:752)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jcifs.smb.SmbException: This client is not compatible with the server.
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:691)
	at jcifs.util.transport.Transport.run(Transport.java:725)
	... 1 more

**Comment by djdkedev** [comment]
Hello,

Do you have any updates about this issue?

Thanks!

**Comment by mbechler** [comment]
Busy weekend... Logs, Packet trace? Likely duplicate of #64

**Comment by djdkedev** [comment]
Does jcifs-ng support SMB1 along with SMB2?

**Comment by mbechler** [comment]
Yes
