### ISSUE TITLE
Deadlock in SmbTreeImpl

### ISSUE THREAD

**Issue by mdzhigarov** [AgNO3/jcifs-ng#72]
"VM Thread" os_prio=0 tid=0x00007fb330628000 nid=0x547 runnable 

"Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007fb330033800 nid=0x53c runnable 

"Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007fb330035800 nid=0x53d runnable 

"Gang worker#2 (Parallel GC Threads)" os_prio=0 tid=0x00007fb330037000 nid=0x53e runnable 

"Gang worker#3 (Parallel GC Threads)" os_prio=0 tid=0x00007fb330039000 nid=0x53f runnable 

"G1 Main Concurrent Mark GC Thread" os_prio=0 tid=0x00007fb33005a000 nid=0x545 runnable 

"Gang worker#0 (G1 Parallel Marking Threads)" os_prio=0 tid=0x00007fb33005b800 nid=0x546 runnable 

"G1 Concurrent Refinement Thread#0" os_prio=0 tid=0x00007fb330042800 nid=0x544 runnable 

"G1 Concurrent Refinement Thread#1" os_prio=0 tid=0x00007fb330041000 nid=0x543 runnable 

"G1 Concurrent Refinement Thread#2" os_prio=0 tid=0x00007fb33003f000 nid=0x542 runnable 

"G1 Concurrent Refinement Thread#3" os_prio=0 tid=0x00007fb33003d800 nid=0x541 runnable 

"G1 Concurrent Refinement Thread#4" os_prio=0 tid=0x00007fb33003b800 nid=0x540 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fb330688000 nid=0x552 waiting on condition 

JNI global references: 34405

Found one Java-level deadlock:
=============================
"pool-134-thread-5":
  waiting to lock monitor 0x00007fb2c415ae48 (object 0x00000000c82614e0, a jcifs.smb.SmbSessionImpl),
  which is held by "AdapterFramework-9 (File Controller) (file_controller_parallel_search_depth_0:file_controller_parallel_search_depth_0)"
"AdapterFramework-9 (File Controller) (file_controller_parallel_search_depth_0:file_controller_parallel_search_depth_0)":
  waiting to lock monitor 0x00007fb28570ecb8 (object 0x00000000c8261598, a jcifs.smb.SmbTreeImpl),
  which is held by "AdapterFramework-13 (File Controller) (file_controller_parallel_fair:file_controller_parallel_fair)"
"AdapterFramework-13 (File Controller) (file_controller_parallel_fair:file_controller_parallel_fair)":
  waiting to lock monitor 0x00007fb2c415ae48 (object 0x00000000c82614e0, a jcifs.smb.SmbSessionImpl),
  which is held by "AdapterFramework-9 (File Controller) (file_controller_parallel_search_depth_0:file_controller_parallel_search_depth_0)"

Java stack information for the threads listed above:
===================================================
"pool-134-thread-5":
	at jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:255)
	- waiting to lock <0x00000000c82614e0> (a jcifs.smb.SmbSessionImpl)
	at jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:75)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:562)
	- locked <0x00000000caec0460> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	- locked <0x00000000caec0460> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	- locked <0x00000000caec0460> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
	- locked <0x00000000caec04e8> (a jcifs.smb.SmbFile)
	at jcifs.smb.SmbFile.exists(SmbFile.java:826)
	...
    
"AdapterFramework-9 (File Controller) (file_controller_parallel_search_depth_0:file_controller_parallel_search_depth_0)":
	at jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:173)
	- waiting to lock <0x00000000c8261598> (a jcifs.smb.SmbTreeImpl)
	at jcifs.smb.SmbTreeImpl.acquire(SmbTreeImpl.java:137)
	at jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:260)
	- locked <0x00000000c82614e0> (a jcifs.smb.SmbSessionImpl)
	at jcifs.smb.SmbSessionImpl.getSmbTree(SmbSessionImpl.java:75)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:562)
	- locked <0x00000000cbf24b18> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	- eliminated <0x00000000cbf24b18> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	- locked <0x00000000cbf24b18> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
	- locked <0x00000000cbf24ba0> (a jcifs.smb.SmbFile)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1258)
	...
    
"AdapterFramework-13 (File Controller) (file_controller_parallel_fair:file_controller_parallel_fair)":
	at jcifs.smb.SmbSessionImpl.release(SmbSessionImpl.java:228)
	- waiting to lock <0x00000000c82614e0> (a jcifs.smb.SmbSessionImpl)
	at jcifs.smb.SmbTreeImpl.release(SmbTreeImpl.java:219)
	- locked <0x00000000c8261598> (a jcifs.smb.SmbTreeImpl)
	at jcifs.smb.SmbTreeImpl.close(SmbTreeImpl.java:191)
	at jcifs.smb.SmbTreeConnection.release(SmbTreeConnection.java:222)
	- locked <0x00000000cbf23308> (a jcifs.smb.SmbTreeConnection)
	at jcifs.smb.SmbTreeHandleImpl.release(SmbTreeHandleImpl.java:174)
	at jcifs.smb.SmbTreeHandleImpl.close(SmbTreeHandleImpl.java:155)
	- locked <0x00000000cbf233b8> (a jcifs.smb.SmbTreeHandleImpl)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:230)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1258)
    ...

Found 1 deadlock.

Using the latest snapshot + SingletonContext.

**Comment by mbechler** [comment]
Looks to me that SmbSessionImpl.getSmbTree being synchronized is the offender breaking the intended locking order here. Using a separate lock for the tree list should work I guess.

**Comment by mdzhigarov** [comment]
Using a different lock for the SmbSessionImpl.getSmbTree would definitely fix the lock order for this specific use case and hence this deadlock. 
However, I have no idea how would that impact other parts of the lib...

**Comment by GerganDimirov** [comment]
I did several tests with the latest 2.1.0-Snapshot and the problem is no longer seen.
Can you tell when a release for the 2.1.0 is planned?
