### ISSUE TITLE
Sporadic failures during copy on high speed system

### ISSUE THREAD

**Issue by apa** [AgNO3/jcifs-ng#74]
I'm trying to use 2.0.6 version on system with high speed network (internet explorer gives up to 400MB\s when copying from local to smb. Jcifsng with default settings gives up to 50MB\s). 

On small files (from 1 byte up to 5GB) everything goes like a charm, but after some copied files library fails with next exceptions in log:

> Caused by: jcifs.smb.SmbException: Transport82 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=18,wordCount=0,byteCount=10048
>         at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1482)
>         at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
>         at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
>         at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
>         at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
>         at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
>         at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
>         at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
>         at jcifs.smb.SmbFileOutputStream.writeDirect(SmbFileOutputStream.java:322)
>         at jcifs.smb.SmbFileOutputStream.write(SmbFileOutputStream.java:284)
>         at com.mucommander.commons.file.impl.sltfs.BlockedSmbFileOutputStream.write(BlockedSmbFileOutputStream.java:84)
>         at com.mucommander.commons.io.CounterOutputStream.write(CounterOutputStream.java:92)
>         at com.mucommander.commons.file.impl.sltfs.SLTFSFile.copyStream(SLTFSFile.java:347)
>         ... 5 more
> Caused by: jcifs.util.transport.TransportException: Transport82 error reading response to command=SMB2_WRITE,status=0,flags=0x0000,mid=18,wordCount=0,byteCount=10048        at jcifs.util.transport.Transport.waitForResponses(Transport.java:351)
>         at jcifs.util.transport.Transport.sendrecv(Transport.java:232)
>         at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:978)
>         at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)
>         ... 17 more
> Caused by: java.io.IOException: WHAT? ( read 124 decoded 128 ): command=SMB2_CLOSE,status=0,flags=0x0005,mid=17,wordCount=0,byteCount=0
>         at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1187)
>         at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1100)
>         at jcifs.util.transport.Transport.loop(Transport.java:459)
>         at jcifs.util.transport.Transport.run(Transport.java:762)
>         ... 1 more
> 

If I'll change log level to finest then copy speed dramatically decreased (up to 5MB\s) and error is not appears with any copied file size.

So, I have two questions actually (possibly I should split them into different issues here on github?):
 - is this copy error known?
 - what could I tune in 2.0.6 version to increase copying speed? Any buffers size, or may be asyncronious transactions are possible with that version?

Thanks in advance!

**Comment by apa** [comment]
> currently capped by the client at ~64k
Is this limitation of implementation in jcifsng? Because from my experience with smbj looks like smb2 protocol allows big transactions buffers (like 1MB, for example). 
I found in BaseConfiguration::maximumBufferSize with value 65536, but it's not configurable..

Regarding increasing of copy speed: is asyncronious read\write (especially write into smb server) in scope for future implementation?

**Comment by mbechler** [comment]
master branch might have a fix for the padding error
