### ISSUE TITLE
"Program type already present" android build issue

### ISSUE THREAD

**Issue by ma99us** [AgNO3/jcifs-ng#75]
Trying to build an android app with jcif-ng 2.0.6.
Getting errors like this during DEX phase "**Program type already present: jcifs.ACE**":
Stacktrace:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\0.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\21.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\133.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\193.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\194.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\195.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\196.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\197.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\198.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\199.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\200.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\201.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\202.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\203.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\204.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\205.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\206.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\207.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\208.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\209.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\210.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\211.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\212.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\213.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\214.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\215.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\216.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\217.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\218.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\219.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\220.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\221.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\222.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\223.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\224.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\225.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\231.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\232.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\233.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\235.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\236.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\237.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\238.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\239.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\240.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\241.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\242.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\243.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\244.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\245.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\246.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\247.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\248.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\249.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\250.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\251.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\252.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\253.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\254.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\255.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\256.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\257.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\258.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\259.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\260.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\261.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\262.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\263.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\264.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\265.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\266.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\267.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\268.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\269.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\270.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\271.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\272.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\273.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\274.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\275.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\276.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\277.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\278.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\279.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\280.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\281.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\282.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\283.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\285.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\286.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\287.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\288.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\289.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\291.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\292.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\293.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\294.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\295.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\296.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\297.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\298.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\299.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\301.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\302.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\303.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\304.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\306.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\307.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\308.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\309.jar
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\0.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\21.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\133.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\193.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\194.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\195.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\196.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\197.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\198.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\199.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\200.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\201.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\202.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\203.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\204.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\205.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\206.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\207.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\208.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\209.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\210.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\211.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\212.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\213.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\214.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\215.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\216.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\217.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\218.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\219.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\220.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\221.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\222.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\223.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\224.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\225.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\231.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\232.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\233.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\235.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\236.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\237.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\238.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\239.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\240.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\241.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\242.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\243.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\244.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\245.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\246.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\247.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\248.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\249.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\250.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\251.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\252.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\253.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\254.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\255.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\256.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\257.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\258.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\259.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\260.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\261.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\262.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\263.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\264.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\265.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\266.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\267.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\268.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\269.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\270.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\271.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\272.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\273.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\274.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\275.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\276.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\277.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\278.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\279.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\280.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\281.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\282.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\283.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\285.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\286.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\287.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\288.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\289.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\291.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\292.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\293.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\294.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\295.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\296.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\297.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\298.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\299.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\301.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\302.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\303.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\304.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\306.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\307.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\308.jar, C:\Projects\SmbLister\app\build\intermediates\transforms\dexBuilder\debug\309.jar
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 48 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	... 53 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
	... 56 more

**Comment by ma99us** [comment]
Gradle dependencies:
    implementation 'eu.agno3.jcifs:jcifs-ng:2.0.6'
    compile 'org.bouncycastle:bcprov-jdk15on:1.56'
    compile 'org.slf4j:slf4j-android:1.7.7'
    compile 'com.android.support:recyclerview-v7:27.1.1'
    compile 'com.android.support:leanback-v17:27.1.1'
    compile 'com.android.support:appcompat-v7:27.1.1'
    compile 'com.android.support:design:27.1.1'
    compile 'com.android.support:support-v4:27.1.1'
    compile 'com.android.support:support-vector-drawable:27.1.1'
    compile 'com.google.firebase:firebase-ads:15.0.0'
    compile 'com.google.firebase:firebase-core:15.0.0'

**Comment by mbechler** [comment]
Don't have too much experience with android builds, but that sounds like a classpath issue to me. However, 2.0.6 also does not have android support as that required some breaking API changes.

**Comment by ma99us** [comment]
any hope to get android support back in future versions?

**Comment by mbechler** [comment]
The master branch has it, which will ultimately be 2.1, but I haven't gotten around to get that ready for release for quite a while.
