### ISSUE TITLE
listFiles() hits OutOfMemoryError when a folder has million files

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#77]
Hi,
Using SMB2, I am trying to call listFiles() a folder has about 3.2 million files and received Java heap space exception.  I increased the max size of java heap to 6g ( -Xmx6g), but still having the OutOfMemoryError.

Here is the code 

> SmbFile file;
> file = new SmbFile("smb://" + host + "/" + shareName + "/" + initDir + "/", SingletonContext.getInstance().withCredentials(auth));
> SmbFile[] fileList;
> fileList = file.listFiles(); 

java.lang.OutOfMemoryError: Java heap space
	at java.lang.Throwable.fillInStackTrace(Native Method) ~[?:2.9 (02-08-2018)]
	at java.lang.Throwable.<init>(Throwable.java:86) ~[?:2.9 (02-08-2018)]
	at java.lang.Throwable.<init>(Throwable.java:97) ~[?:2.9 (02-08-2018)]
	at java.lang.Error.<init>(Error.java:81) ~[?:2.9 (02-08-2018)]
	at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:64) ~[?:2.9 (02-08-2018)]
	at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:69) ~[?:2.9 (02-08-2018)]
	at jcifs.smb.DirFileEntryAdapterIterator.adapt(DirFileEntryAdapterIterator.java:48) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.FileEntryAdapterIterator.advance(FileEntryAdapterIterator.java:73) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.FileEntryAdapterIterator.next(FileEntryAdapterIterator.java:121) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.FileEntryAdapterIterator.next(FileEntryAdapterIterator.java:32) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:286) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1219) ~[jcifs-ng-2.0.1-flx.1.jar:?]

Is there any suggestion for the issue?

Thanks in advance.
Thanks,

**Comment by mbechler** [comment]
The listFiles() style operations all load the complete directory contents so you will be limited by the amount of memory available. jcifs-ng also has the newer children() style methods returning iterators, these don't load all the directory entries at the same time.
