### ISSUE TITLE
client not compatible - netApp DFS

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#79]
Hi,
We are getting  'This client is not compatible with the server' error when trying to connect to a smb2 environment through netApp/DFS during command=SMB2_NEGOTIATE

[2018-06-22 09:35:53,057] DEBUG [Transport6] jcifs.smb.SmbTransportImpl Negotiation response on Transport6 :Smb2NegotiateResponse[command=SMB2_NEGOTIATE,status=The parameter is incorrect.,flags=0x0001,mid=1,wordCount=0,byteCount=0,dialectRevision=0,securityMode=0x0,capabilities=0x00000000,serverTime=Thu Jan 01 00:00:00 UTC 1970
[2018-06-22 09:35:53,057] DEBUG [1101952700@qtp--1110955942-0] jcifs.util.transport.Transport Interrupting transport thread
[2018-06-22 09:35:53,057] DEBUG [1101952700@qtp--1110955942-0] jcifs.util.transport.Transport Joining transport thread
[2018-06-22 09:35:53,057] DEBUG [1101952700@qtp--1110955942-0] jcifs.util.transport.Transport Joined transport thread
[2018-06-22 09:35:53,057] DEBUG [1101952700@qtp--1110955942-0] jcifs.smb.SmbTransportPoolImpl Removing transport connection Transport6[0.0.0.0<00>/192.168.0.203:445,state=4,signingEnforced=true,usage=1] (2057422451)
[2018-06-22 09:35:53,057] WARN  [1101952700@qtp--1110955942-0] jcifs.smb.SmbTreeConnection Referral failed, trying next
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/192.168.0.203
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:651) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:575) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbFile.getServerTime(SmbFile.java:2420) [jcifs-ng-2.0.1-flx.1.jar:?]
Caused by: jcifs.util.transport.TransportException: jcifs.smb.SmbException: This client is not compatible with the server.
	at jcifs.util.transport.Transport.run(Transport.java:752) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at java.lang.Thread.run(Thread.java:785) ~[?:1.8.0-internal]
Caused by: jcifs.smb.SmbException: This client is not compatible with the server.

Can you help to see what may be wrong? We checked and confirmed the smb server is enable smb2 protocol.

**Comment by thanh-vn** [comment]
[jcifs-ng-issue79.zip](https://github.com/AgNO3/jcifs-ng/files/2128607/jcifs-ng-issue79.zip)

**Comment by mbechler** [comment]
Have you checked whether you can connect to the DFS target server (192.168.0.203)? 
It immediately rejects our SMB2 negotiation attempt and I'm not sure why.
