### ISSUE TITLE
SMB2 jcifs.smb.SmbTransportImpl Failure decoding message

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#80]
We are getting weird error when trying to connect to a SMB2 server for command=SMB2_CLOSE.  An exception 'java.io.IOException: WHAT? ( read 124 decoded 128 ):' returned.  We did not hit this when using SMB1.

[2018-05-21 18:53:54,120] WARN  [Transport0] jcifs.smb.SmbTransportImpl Failure decoding message, disconnecting transport
java.io.IOException: WHAT? ( read 124 decoded 128 ): command=SMB2_CLOSE,status=0,flags=0x000D,mid=11,wordCount=0,byteCount=0
	at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1187) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1100) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.util.transport.Transport.loop(Transport.java:459) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.util.transport.Transport.run(Transport.java:762) [jcifs-ng-2.0.1-flx.1.jar:?]
	at java.lang.Thread.run(Thread.java:811) [?:2.9 (02-08-2018)]
[2018-05-21 18:53:54,121] DEBUG [-1724470660@qtp--2001254524-0] jcifs.internal.smb2.create.Smb2CloseRequest Closing FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (\)
[2018-05-21 18:53:54,121] DEBUG [Transport0] jcifs.util.transport.Transport recv failed
java.io.IOException: WHAT? ( read 124 decoded 128 ): command=SMB2_CLOSE,status=0,flags=0x000D,mid=11,wordCount=0,byteCount=0
	at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1187) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1100) ~[jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.util.transport.Transport.loop(Transport.java:459) [jcifs-ng-2.0.1-flx.1.jar:?]
	at jcifs.util.transport.Transport.run(Transport.java:762) [jcifs-ng-2.0.1-flx.1.jar:?]
	at java.lang.Thread.run(Thread.java:811) [?:2.9 (02-08-2018)]
[2018-05-21 18:53:54,121] WARN  [Transport0] jcifs.smb.SmbTransportImpl Disconnecting transport while still in use Transport0[0.0.0.0<00>/192.168.0.240:445,state=5,signingEnforced=false,usage=5]: [SmbSession[credentials=oprsys\svc_testuser,targetHost=192.168.0.240,targetDomain=null,uid=0,connectionState=2,usage=4]]

Appreciate if you can suggest anyway to debug this issue!

**Comment by thanh-vn** [comment]
[jcifs-ng-issue80.zip](https://github.com/AgNO3/jcifs-ng/files/2129258/jcifs-ng-issue80.zip)

**Comment by mbechler** [comment]
I think that might be the issue described in https://github.com/AgNO3/jcifs-ng/issues/74#issuecomment-385658812 with the server not padding as expected.  
It's not that easy to fix as this introduces a difference between the data that the signature is calculated on and the actual data and I haven't gotten around to it.

**Comment by mbechler** [comment]
master branch possibly has a fix for that now

**Comment by thanh-vn** [comment]
Thank you much for the possible fix, we will give it a try.
