### ISSUE TITLE
NullPointerException when calling SmbFile.listFiles

### ISSUE THREAD

**Issue by chengyiuchun** [AgNO3/jcifs-ng#85]
Hi,

I encountered the following NullPointerException when listing files with version 2.0.6

My flow is like:
```
SmbFile file = new SmbFile(...);
SmbFile[] results = file.listFiles("*abc*");
```

Thanks.

Stack trace:
```
java.lang.NullPointerException
    at jcifs.smb.SmbTransportImpl.isDisconnected(SmbTransportImpl.java:188)
    at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:122)
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:194)
    at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
    at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
    at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
    at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
    at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
    at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:283)
    at jcifs.smb.SmbFile.listFiles(SmbFile.java:1179)
```

**Comment by apa** [comment]
I could confirm issue: also see that sporadically after calling different methods.
Issue in jcifs.smb.SmbTransportImpl.isDisconnected method:
`        return super.isDisconnected() || this.socket.isClosed();`

Makes sense to add check whether socket is `null` before calling isClosed() method.

**Comment by jgribonvald** [comment]
Could you make a new release ?
