### ISSUE TITLE
netApp: jcifs.smb.SmbException: This client is not compatible with the server

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#97]
Hi,
We are having issue 'client is not compatible with the server' while trying to access shares through netApp environment.  The status of the SMB2_NEGOTIATE command is 'The parameter is incorrect'.

2018-08-10 12:52:36 DEBUG SmbTransportImpl:687 - Negotiation response on Transport2 :Smb2NegotiateResponse[command=SMB2_NEGOTIATE,status=The parameter is incorrect.,flags=0x0001,mid=1,wordCount=0,byteCount=0,dialectRevision=0,securityMode=0x0,capabilities=0x00000000,serverTime=Thu Jan 01 00:00:00 UTC 1970
2018-08-10 12:52:36 DEBUG Transport:633 - Interrupting transport thread
2018-08-10 12:52:36 DEBUG Transport:635 - Joining transport thread
2018-08-10 12:52:36 DEBUG Transport:637 - Joined transport thread
2018-08-10 12:52:36 DEBUG SmbTransportPoolImpl:256 - Removing transport connection Transport2[0.0.0.0<00>/10.11.22.101:445,state=4,signingEnforced=true,usage=1] (562257446)
2018-08-10 12:52:36 WARN  SmbTreeConnection:576 - Referral failed, trying next
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/10.11.22.101
        at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:651)
        at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
        at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:575)
        at jcifs.smb.SmbFile.exists(SmbFile.java:852)
        at Test_getOwnerID.main(Test_getOwnerID.java:61)
Caused by: jcifs.util.transport.TransportException: jcifs.smb.SmbException: This client is not compatible with the server.
        at jcifs.util.transport.Transport.run(Transport.java:752)
        at java.lang.Thread.run(Thread.java:785)
Caused by: jcifs.smb.SmbException: This client is not compatible with the server.
        at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:691)
        at jcifs.util.transport.Transport.run(Transport.java:725)

 We are using SMB2 with the following settings:
 -Djcifs.smb.client.signingEnforced=true -Djcifs.smb.client.signingPreferred=true -Djcifs.smb.client.ipcSigningEnforced=false.

Could you see what we can debug the issue?
Thanks in advance!
[thanh-vn-Compatible-issue.zip](https://github.com/AgNO3/jcifs-ng/files/2279952/thanh-vn-Compatible-issue.zip)

**Comment by mbechler** [comment]
Which version?

**Comment by thanh-vn** [comment]
The version of netApp that has issue is: 8.2.4P6 7-Mode 

We tried the same test and found out that these older versions of netApp do not have the issue: 8.1.2 7-Mode and 8.2P6 7-Mode

**Comment by mbechler** [comment]
I meant the jcifs-ng version

**Comment by thanh-vn** [comment]
jcifs-ng is 2.0.6

**Comment by thanh-vn** [comment]
We see the error we received from the SMB2_NEGOTIATE command = -1073741811 <-- 0xc000000d
The network trace shows SMB2_NEGOTIATE status = 0xc000000d = STATUS_INVALID_PARAMETER.
Can you see anything else to debug the issue on jcifs-ng side?  The issue does not happen on earlier version of netApp (see comment #3) 
Thanks,

**Comment by mbechler** [comment]
Might require some capability and/or a higher protocol version. Maybe the netapp logs can provide some information. You can try with 2.1. Also, there could be still something wrong/different with the signing negotiation.

**Comment by thanh-vn** [comment]
Hi,
netApp thinks returning STATUS_INVALID_PARAMETER because the client already negotiated the protocol on the same session: "After the client negotiates SMB2, it ACKs the response and starts negotiating AGAIN, starting with SMB2 instead of SMB.  
The client should either start with SMB2 (if that's what it needs to do), or proceed with Session Setup after Negotiate Protocol succeeds."

Dont know if the netApp's comments help any.  We are asking more detail from netApp's logs.
Thanks,

**Comment by mbechler** [comment]
Not sure whether they are describing multi protocol negotation or an actual issue. Can you provide a packet trace showing that behavior.

If they just don't understand multi-protocol negotiation, you can use SMB2 only negotiation by setting _jcifs.smb.client.useSMB2Negotiation=true_
