### ISSUE TITLE
Logon failure: unknown user name or bad password when SMB2 is enabled.

### ISSUE THREAD

**Issue by myoldprojects** [AgNO3/jcifs-ng#98]
Tried with version 2.0.7 and 2.1.0
The server is Hitachi HNAS

I was able to connect with the same user name and password under SMB1, but as soon as I enabled SMB2 I am getting "_Logon failure: unknown user name or bad password._"
I have confirmed the server has enabled SMB2. I am able to connect to that server with SMBJ. We also have windows desktop and Linux access to this HNAS server.

Here is the code snippet and log from the client 

**<< version 2.0.7 >>**

	String domain = "";
	Properties prop = new Properties();
	prop.put( "jcifs.smb.client.enableSMB2", "true" );
	prop.put( "jcifs.smb.client.useSMB2Negotiation", "true" );
	prop.put( "jcifs.smb.client.useExtendedSecurity","false");
	Configuration config = new PropertyConfiguration(prop);
	CIFSContext baseContext = new BaseContext(config);
	CIFSContext contextWithCred = baseContext.withCredentials(new NtlmPasswordAuthentication(baseContext, domain, user, password));
	SmbFile share = new SmbFile(smbFullPathWithOutCred, contextWithCred);
	if (share.exists())

DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0009,mid=1,wordCount=0,byteCount=0
DEBUG jcifs.smb.SmbTransportImpl - Insufficient credits, send only first command=SMB2_SESSION_SETUP,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0 next is command=SMB2_TREE_CONNECT,status=0,flags=0x0000,mid=0,wordCount=0,byteCount=0
DEBUG jcifs.smb.SmbSessionImpl - Session setup failed
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1381)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1522)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:984)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1493)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:601)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:466)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:361)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:339)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.exists(SmbFile.java:821)
	at org.test.smb2.JcifsNG.main(JcifsNG.java:35)

**<< version 2.1.0 >>**

	String domain = "";
	Properties prop = new Properties();
	prop.put( "jcifs.smb.client.useExtendedSecurity","false" );
	prop.put( "jcifs.smb.client.useSMB2Negotiation", "true" );
	Configuration config = new PropertyConfiguration(prop);
	CIFSContext baseContext = new BaseContext(config);
	CIFSContext contextWithCred = baseContext.withCredentials(new NtlmPasswordAuthenticator(domain, user, password));
	SmbFile share = new SmbFile(smbFullPathWithOutCred, contextWithCred);
	if (share.exists())
	
	
DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0009,mid=1,wordCount=0,byteCount=0
DEBUG jcifs.smb.NtlmContext - Sign key is 3A62CBB4587550B8A66554B48464FD97
DEBUG jcifs.smb.NtlmContext - Verify key is E26E797BC0BC44E7E173548AE28305F5
DEBUG jcifs.smb.NtlmContext - Seal key is 032A2BC44417071B8FAA7D1839FA9172
DEBUG jcifs.smb.NtlmContext - Server seal key is 51076B0359D6DC81012BC0B6CBD5479B
DEBUG jcifs.smb.NtlmContext - Digest 7FFECBC71274BFDFB36A09ECC6278504
DEBUG jcifs.smb.NtlmContext - Truncated 7FFECBC71274BFDF
DEBUG jcifs.smb.NtlmContext - Encrypted 52B0C6FEF5A1C794
DEBUG jcifs.smb.SpnegoContext - Out Mech list [1.3.6.1.4.1.311.2.2.10]
DEBUG jcifs.smb.SpnegoContext - Out Mech list encoded 300C060A2B06010401823702020A
DEBUG jcifs.smb.SpnegoContext - Out Mech list MIC 0100000052B0C6FEF5A1C79400000000
DEBUG jcifs.smb.SmbSessionImpl - Session setup failed
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1404)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1547)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1005)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1518)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:547)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:481)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:367)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
	at jcifs.smb.SmbFile.exists(SmbFile.java:826)

Am I missing any property setting?	
Any suggestion?
Thanks.

**Comment by mbechler** [comment]
So auth works with jcifs-ng with SMB2 disabled?
jcifs.smb.client.useExtendedSecurity really should not be necessary - if it is required for SMB1 to function something is seriously wrong there.

Auth issues unfortunately can be quite difficult to debug. Maybe most helpful would be a side by side comparsion of packet traces of SMBJ and jcifs-ng.
Please double check that the domain/username/password are actually correct. 

There are two more settings, however the affected features were only introduced in 2.1 so if it fails on 2.0 as well these should not make a difference
- Setting jcifs.smb.client.disableSpnegoIntegrity=true
- Setting jcifs.smb.useRawNTLM=true

**Comment by myoldprojects** [comment]
Yes, I use the same domain/username/password on both SMBJ and Jcifs-ng.
I hope the following help. Let me know if there is another frame let me know.  Thanks.

JCIFS-NG

SMB2 (Server Message Block Protocol version 2)
    SMB2 Header
    Session Setup Request (0x01)
        StructureSize: 0x0019
        Flags: 0
        Security mode: 0x01, Signing enabled
        Capabilities: 0x00000001, DFS
        Channel: None (0x00000000)
        Previous Session Id: 0x0000000000000000
        Blob Offset: 0x00000058
        Blob Length: 434
        Security Blob: 4e544c4d5353500003000000180018005800000000010001...
            NTLM Secure Service Provider
                NTLMSSP identifier: NTLMSSP
                NTLM Message Type: NTLMSSP_AUTH (0x00000003)
                Lan Manager Response: 48bfabf6c66ad2eb36010f94df97238e72ea007b00629ba2
                NTLM Response: 2b702004fc747f0191712cc72134f12e0101000000000000...
                Domain name: ?
                User name: [USER_ID]
                Host name: JCIFS140_103_75
                Session Key: 336defed9c8ecbe9ffe37527fd391e29
                Negotiate Flags: 0x62888215, Negotiate Key Exchange, Negotiate 128, Negotiate Version, Negotiate Target Info, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Negotiate Sign, Request Target, Negotiate UNICODE
                Version 6.1 (Build 0); NTLM Current Revision 15
                MIC: bf4f1cd53ed1c1c80e76beae648d3d58
				
=================================================================
SMBJ
				
SMB2 (Server Message Block Protocol version 2)
    SMB2 Header
    Session Setup Request (0x01)
        StructureSize: 0x0019
        Flags: 0
        Security mode: 0x01, Signing enabled
        Capabilities: 0x00000001, DFS
        Channel: None (0x00000000)
        Previous Session Id: 0x0000000000000000
        Blob Offset: 0x00000058
        Blob Length: 286
        Security Blob: a182011a30820116a28201120482010e4e544c4d53535000...
            GSS-API Generic Security Service Application Program Interface
                Simple Protected Negotiation
                    negTokenTarg
                        responseToken: 4e544c4d53535000030000000000000040000000ac00ac00...
                        NTLM Secure Service Provider
                            NTLMSSP identifier: NTLMSSP
                            NTLM Message Type: NTLMSSP_AUTH (0x00000003)
                            Lan Manager Response: Empty
                            NTLM Response: f0bd25c43f62213bc461406580ac5a0c0101000000000000...
                            Domain name: NULL
                            User name: [USER_ID]
                            Host name: NULL
                            Session Key: 3b00e42e092d1ba65e26c253bd38a391
                            Negotiate Flags: 0xe0888215, Negotiate 56, Negotiate Key Exchange, Negotiate 128, Negotiate Target Info, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Negotiate Sign, Request Target, Negotiate UNICODE

**Comment by mbechler** [comment]
Thanks. So, except for jcifs-ng adding some newer NTLM extensions, which I don't think would cause that error, there is a difference in how we treat an unspecified domain, and that there is a hostname sent.
I'll provide a version where that behavior can be adjusted, so we can further check whether and which one of these is causing the issue.

Could also be related to #93.

**Comment by mbechler** [comment]
These commits should lead to the same behavior as smbj and hopefully to a successful connection. If it succeeds, plase also try specifing some hostname via _jcifs.netbios.hostname_ so we can further pin that down (I guess the domain is the issue).

**Comment by myoldprojects** [comment]
Thanks for the new update, with the new changes now I am able to connect and do some listing from the directory.  The only new issue I see is the following stack trace.

`14:50:16.153 [main] DEBUG jcifs.smb.SmbTransportPoolImpl - New transport connection Transport0[0.0.0.0<00>/xx.xx.xx.xx:445,state=0,signingEnforced=false,usage=1]
14:50:16.156 [main] DEBUG jcifs.util.transport.Transport - Connecting Transport0
14:50:16.156 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Connecting in state 1 addr xx.xx.xx
14:50:16.162 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Using SMB2 only negotiation
14:50:16.176 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Negotiation response on Transport0 :jcifs.internal.SmbNegotiation@42baa7b1
14:50:16.176 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Signature negotiation enforced false (server false) enabled false (server true)
14:50:16.180 [main] DEBUG jcifs.smb.SmbTransportImpl - Establishing new session SmbSession[credentials=xactsites,targetHost=xx.xx.xx,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
14:50:16.183 [main] DEBUG jcifs.smb.SmbTreeImpl - treeConnect: unc=\\xx.xx.xx\TEST03,service=?????
14:50:16.184 [main] DEBUG jcifs.smb.SmbSessionImpl - sessionSetup: xactsites
14:50:16.184 [main] DEBUG jcifs.smb.SmbSessionImpl - Remote host is xx.xx.xx
14:50:16.387 [main] DEBUG jcifs.smb.NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.2.840.48018.1.2.2, 1.3.6.1.4.1.311.2.2.10],mic=null]
14:50:16.401 [main] DEBUG jcifs.smb.SmbTransportImpl - Breaking on error command=SMB2_SESSION_SETUP,status=More data is available.,flags=0x0009,mid=1,wordCount=0,byteCount=0
14:50:16.789 [main] DEBUG jcifs.smb.NtlmContext - Sign key is 47E832B2004EF3D347EA9F414A311184
14:50:16.789 [main] DEBUG jcifs.smb.NtlmContext - Verify key is 7BA5004DE5B9F80C0D838247080DBB91
14:50:16.789 [main] DEBUG jcifs.smb.NtlmContext - Seal key is 52EDD88F73123AC30144E5657EA56DB8
14:50:16.790 [main] DEBUG jcifs.smb.NtlmContext - Server seal key is A78B076A443E59506B71FEF8DE36D883
14:50:16.790 [main] DEBUG jcifs.smb.NtlmContext - Digest 9D3708148F6B578C9DC8FEEB158F4A58
14:50:16.790 [main] DEBUG jcifs.smb.NtlmContext - Truncated 9D3708148F6B578C
14:50:16.790 [main] DEBUG jcifs.smb.NtlmContext - Encrypted 48A02B44214F6A2E
14:50:16.790 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list [1.3.6.1.4.1.311.2.2.10]
14:50:16.790 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list encoded 300C060A2B06010401823702020A
14:50:16.790 [main] DEBUG jcifs.smb.SpnegoContext - Out Mech list MIC 0100000048A02B44214F6A2E00000000
14:50:16.795 [main] DEBUG jcifs.smb.SmbSessionImpl - Context is established
14:50:16.819 [main] DEBUG jcifs.smb.SmbTreeImpl - Sending VALIDATE_NEGOTIATE_INFO
14:50:16.829 [main] DEBUG jcifs.smb.SmbTreeImpl - Secure negotiation OK
14:50:16.829 [main] DEBUG jcifs.smb.SmbTreeConnection - Switching tree
14:50:16.830 [main] DEBUG jcifs.smb.SmbTreeConnection - Acquired tree on switch SmbTree[share=TEST03,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
14:50:16.831 [main] DEBUG jcifs.smb.SmbTreeConnection - Tree connection no longer in use, release tree SmbTree[share=TEST03,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
14:50:16.831 [main] DEBUG jcifs.smb.SmbTreeImpl - Usage dropped to zero, release session
14:50:16.831 [main] DEBUG jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport0[0.0.0.0<00>/xx.xx.xx:445,state=3,signingEnforced=false,usage=1]
14:50:16.837 [main] DEBUG jcifs.smb.SmbTreeImpl - Reacquire session
14:50:16.837 [main] DEBUG jcifs.smb.SmbSessionImpl - Reacquire transport
14:50:16.837 [main] DEBUG jcifs.smb.SmbTreeConnection - Acquire tree on first usage SmbTree[share=TEST03,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=1]
14:50:16.843 [main] DEBUG jcifs.internal.smb2.create.Smb2CreateRequest - Opening 
14:50:16.854 [Transport0] DEBUG jcifs.internal.smb2.create.Smb2CreateResponse - Opened : 3A03000000000A000100000000000000
14:50:16.854 [Transport0] DEBUG jcifs.smb.SmbTransportImpl - Compound next command 0 read size 736 remain 736
14:50:16.860 [main] DEBUG jcifs.smb.SmbTransportImpl - Error code: 0x80000006 for Smb2QueryDirectoryRequest
14:50:16.862 [main] DEBUG jcifs.smb.SmbTreeConnection - Not retrying
jcifs.smb.SmbException: 0x80000006
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1438)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1549)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1520)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
	at jcifs.smb.DirFileEntryEnumIterator2.fetchMore(DirFileEntryEnumIterator2.java:142)
	at jcifs.smb.DirFileEntryEnumIteratorBase.advance(DirFileEntryEnumIteratorBase.java:148)
	at jcifs.smb.DirFileEntryEnumIteratorBase.next(DirFileEntryEnumIteratorBase.java:215)
	at jcifs.smb.DirFileEntryEnumIteratorBase.next(DirFileEntryEnumIteratorBase.java:34)
	at jcifs.smb.FileEntryAdapterIterator.advance(FileEntryAdapterIterator.java:70)
	at jcifs.smb.FileEntryAdapterIterator.next(FileEntryAdapterIterator.java:121)
	at jcifs.smb.FileEntryAdapterIterator.next(FileEntryAdapterIterator.java:32)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:292)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1184)
	at org.test.smb2.JcifsNG.main(JcifsNG.java:41)
14:50:16.862 [main] DEBUG jcifs.smb.DirFileEntryEnumIterator2 - End of listing
jcifs.smb.SmbException: 0x80000006
	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1438)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1549)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1520)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
	at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:399)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:314)
	at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
	at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
	at jcifs.smb.DirFileEntryEnumIterator2.fetchMore(DirFileEntryEnumIterator2.java:142)
	at jcifs.smb.DirFileEntryEnumIteratorBase.advance(DirFileEntryEnumIteratorBase.java:148)
	at jcifs.smb.DirFileEntryEnumIteratorBase.next(DirFileEntryEnumIteratorBase.java:215)
	at jcifs.smb.DirFileEntryEnumIteratorBase.next(DirFileEntryEnumIteratorBase.java:34)
	at jcifs.smb.FileEntryAdapterIterator.advance(FileEntryAdapterIterator.java:70)
	at jcifs.smb.FileEntryAdapterIterator.next(FileEntryAdapterIterator.java:121)
	at jcifs.smb.FileEntryAdapterIterator.next(FileEntryAdapterIterator.java:32)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:292)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1184)
	at org.test.smb2.JcifsNG.main(JcifsNG.java:41)
14:50:16.863 [main] DEBUG jcifs.internal.smb2.create.Smb2CloseRequest - Closing 3A03000000000A000100000000000000 ()
14:50:16.867 [Transport0] DEBUG jcifs.internal.smb2.create.Smb2CloseResponse - Closed 3A03000000000A000100000000000000 ()
14:50:16.868 [main] DEBUG jcifs.smb.SmbTreeConnection - Tree connection no longer in use, release tree SmbTree[share=TEST03,service=null,tid=1,inDfs=false,inDomainDfs=false,connectionState=2,usage=2]
14:50:16.868 [main] DEBUG jcifs.smb.SmbTreeImpl - Usage dropped to zero, release session
14:50:16.868 [main] DEBUG jcifs.smb.SmbSessionImpl - Usage dropped to zero, release connection Transport0[0.0.0.0<00>/xx.xx.xx:445,state=3,signingEnforced=false,usage=1]`

**Comment by myoldprojects** [comment]
Here is a screen shot that show the current difference between jcifs-ng and smbj


![image](https://user-images.githubusercontent.com/15364687/45849588-bc783400-bcef-11e8-937d-0533d18f0556.png)

**Comment by mbechler** [comment]
The stacktrace you are seeing there is just debugging for the STATUS_NO_MORE_FILES, which is normal. You can see that response code in the smbj exchange as well.

**Comment by myoldprojects** [comment]
Got it, thanks for the clarification.
